### ISSUE TITLE
[Main menu] aspetto

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#1]
- [x] Di default, all'apertura del sistema lascerei il menu sempre espanso, oppure bisogna includere nella pagina una indicazione su dove andare e cosa fare. Quando si apre il sistema non è immediatamente apparente cosa bisogna fare.

- [x] Allineare le voci Logout, Help, Settings e Administration a partire dal basso del menu, separandoli dalle voci Ontology, KG, e Dataset

- [x] Aggiungere una icona che rappresenti l'utente attualmente connesso

- [x] E' previsto uno scroll verticale in caso ad esempio ci siano aperte diverse ontologie, KG, e Dataset, e lo spazio verticale non sia sufficiente?

- [ ] La Small Icon di Monolith è da modificare

**Comment by giacomoronconiobda** [comment]
Username aggiunto dopo Logout

**Comment by valeriosantarelli** [comment]
Allego la nuova versione della small icon e chiudo la issue.

[logo-piccolo.svg.zip](https://github.com/obdasystems/monolith/files/3227761/logo-piccolo.svg.zip)
