### ISSUE TITLE
[Ontology - Documentation] Entity Property Cards

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#10]
- [ ] Dentro le Entity Property Cards, ovvero le card delle proprietà di classi, ruoli, attributi (ad esempio SuperClasses per una classe), quando si va sopra ad una superclasse con il mouse, dovrebbe uscire tipo tooltip, l’assioma corrispondente serializzato in OWL (Functional Style Syntax) dell'ontologia.

- [x] Dentro le Entity Property Cards non vengono visualizzate le espressioni complesse (renderizzate semplicemente come stringhe al momento ovviamente)

**Comment by roodsey** [comment]
@giacomoronconiobda @valeriosantarelli occorre esplicitare tali richieste in termini di path e verbo HTTP corrispondenti

**Comment by roodsey** [comment]
Piuttosto che cambiare le strutture dati e il flusso dei servizi, conviene ricostruire queste informazioni lato applicativo: mi tolgo dalla issue

**Comment by valeriosantarelli** [comment]
Facciamo così: dato che la funzionalità non è cruciale, la sposto alla milestone successiva, così questa issue la chiudiamo (cosa già fatta da Giacomo peraltro), e poi in un secondo momento decidiamo qual'è il modo più opportuno per gestire la nuova funzionalità.
