### ISSUE TITLE
[KG - Info] Numero di triple

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#100]
Il numero di triple in un KG non viene correttamente riportato. Dice sempre 0.

**Comment by giacomoronconiobda** [comment]
Il numero mi viene restituito dal server, giro a @roodsey

**Comment by valeriosantarelli** [comment]
Il numero di triple viene contato quando viene riavviato Tomcat, quindi se carico un dataset il numero di triple che vedo sarà comunque obsoleto.
Il conteggio dovrebbe avvenire al momento del caricamento di un nuovo set di triple dentro un KG, oppure al limite sommando le triple dei vari file che sono stati importati (quest'ultima informazione viene visualizzata correttamente).

**Comment by roodsey** [comment]
Eseguito fix. Occorre verificare il refresh della pagina con le card dei KG: a fronte dell'aggiunta di un nuovo KG, il dato sulle triple degli altri viene poi mostrato correttamente. 
@giacomoronconiobda

**Comment by valeriosantarelli** [comment]
Questa issue risulta risolta, ma non mi pare che la soluzione sia molto efficace.
Se non capisco male, il numero visualizzato (anche nella pagina Info del KG) viene aggiornato solamente quando viene caricato un nuovo KG, diverso da quello in oggetto.

Se quindi non carico mai un secondo KG, continuerò a vedere per sempre 0 come numero di triple.

**Comment by giacomoronconiobda** [comment]
Penso sia un problema di cache di mws

**Comment by giacomoronconiobda** [comment]
@roodsey quale stato del KG? La chiamata che restituisce il numero di triple del KG è la seguente:
```
/knowledgeGraph?iri={iri}
```

**Comment by giacomoronconiobda** [comment]
@roodsey quale stato del KG? La chiamata che restituisce il numero di triple del KG è la seguente:
```
/knowledgeGraph?iri={iri}
```

**Comment by giacomoronconiobda** [comment]
Ho visto ora l'esistenza dell'oggetto `KGStatus` che forse è un po' ridondante rispetto l'oggetto `KnowledgeGraph`. @roodsey li lasciamo entrambi?

**Comment by roodsey** [comment]
Sì, perché KGStatus in teoria può essere chiamato anche mentre si caricano gli store

**Comment by giacomoronconiobda** [comment]
Ok, però allora bisogna aggiornare KnowledgeGraph a fronte di un import. La issue penso parli di questo (il numero di triples in `KGStatus` non lo uso mai)

**Comment by roodsey** [comment]
Risolto: aggiornavo solo lo stato, ora aggiorno tutti e due i valori. Questa informazione replicata non è il massimo, ma per importazione di KG con molte tuple, occorrerà fare riferimento allo status (se uno vuole ad esempio vedere il progresso)
