### ISSUE TITLE
[KG - Import] Ristrutturazione pagina di import

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#111]
Ristrutturare la pagina di Import dei knowledge graphs, sulla falsa riga di quello che fanno in GraphDB.

Elenco i punti salienti:
- Caricamento in due step dei file rdf, il primo sul server, e poi il secondo dentro il KG
- Catalogo di file caricati, con flag (o indicazione di qualche tipo) di file caricato o meno
- Implementazione quindi di servizi per importare e/o cancellare un file sul server
- finestra di configurazione dell'import, con target named graph da definire al momento del caricamento
- informazioni su impostazioni di caricamento delle triple e delle dimensione (in triple) del file

Di seguito screenshot per dare l'idea:

<img width="1189" alt="Schermata 2019-06-13 alle 14 36 49" src="https://user-images.githubusercontent.com/8250758/59494162-ddd80c00-8e8c-11e9-9536-d2b76e2a7e94.png">

<img width="1097" alt="Schermata 2019-06-13 alle 14 36 57" src="https://user-images.githubusercontent.com/8250758/59494172-e16b9300-8e8c-11e9-9e75-902d36374fd6.png">

**Comment by giacomoronconiobda** [comment]
Mock up completato, assegno @roodsey per l'implementazione servizi
