### ISSUE TITLE
[Mapping Editor] Create/Upload Mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#117]
Modificare la pagina di caricamento di un mapping introducendo due opzioni al posto di "Add Mapping":

1. Create Mapping: questa funzionalità permette di creare un nuovo file di mapping. Una volta scelta, dovrebbe uscire un Drawer in cui inserire il nome, la versione, la descrizione, e la scelta del data source tra quelli noti al sistema
2. Upload Mapping: questa funzionalità permette di importare un file di mapping. Una volta scelto il mapping, dovrebbe uscire un Drawer in cui nome, versione e descrizione sono precompilati, e permette di scegliere il data source (aggiungendo a quelli noti al sistema anche quello presente nel file di mapping)

**Comment by giacomoronconiobda** [comment]
Per fare questo ci servono nuovi servizi, @roodsey tu avevi già fatto qualcosa a riguardo o dobbiamo far un altro foglio excel?

**Comment by roodsey** [comment]
Aggiunto query param "create" alla rotta 
@Path("/owlOntology/{name}/version/mapping")
Se presente e diverso da stringa vuota il contenuto del file viene decodificato base64 e deserializzato nell'oggetto NewMappingFIleInfo aggiunto alle risorse (file excel non allineato).

Nel campo "databaseConnectionName" del JSON si può passare il nome di una sorgente dati esistente (viene cercata per l'utente che crea il mapping e se non trovata viene restituito un errore). Il valore del campo in questo campo viene controllato per primo.

Alternativamente si può passare un oggetto newDatabaseConnection, che verrà utilizzato per creare una nuova datasourcentryinfo per l'utente (utilizzando il campo "newDatabaseConnectionDescription" come descrizione.

La rotta provvede alla serializzazione di un file XML vuoto, contenente solo le informazioni di base provviste fino ad ora. (la serializzazione non è tuttora implementata)

**Comment by roodsey** [comment]
Ho completato l'implementazione delle POST per la creazione di viste e mapping (sia per classe che per proprietà). Effettuo il deploy: si può iniziare a testare.
