### ISSUE TITLE
[Ontology - Navigation] Distribuzione assiomi (partecipazione obbligatoria)

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#118]
La presente non è propriamente una segnalazione di bug o altro, però credo sia il caso di chiarire quella che è attualmente una ambiguità nel sistema: la distribuzione degli assiomi di tipizzazione e partecipazione nelle card di Ontology Navigation.

Allo stato attuale, il comportamento del sistema è il seguente: gli assiomi di partecipazione obbligatoria (SubClassOf(class ObjectSomeValueFrom(role owl:Thing)) vengono riportati, nella pagina di una classe, sia nella card SubClasses che nella card Object/Data Properties. Potete vedere un esempio negli screenshot del mio commento alla issue #77 

La nostra intenzione iniziale era leggermente diversa: suddividere gli assiomi in modo da non creare ridondanze, mettendo le partecipazioni obbligatorie nella card Object/Data Properties, e gli assiomi di tipizzazione nella pagina dell'Object o Data Property, nella card Domain/Range.

Ragionando su come fosse il modo corretto di eliminare questa ambiguità, mi sto sempre più convincendo che dovremmo attenerci ad una suddivisione meramente sintattica degli assiomi, ed essere più allineati possibile a quanto fanno gli altri strumenti classici di OWL (in particolare Protégé).

In particolare quindi il mio suggerimento sarebbe questo:
- TUTTI gli assiomi SubClassOf vanno a finire dentro la card SubClasses della pagina delle Class
- TUTTI gli assiomi Object/Data Property Domain/Range vanno a finire dentro la card Object/Data Properties della pagina della Class, e dentro la card Domain/Range delle pagine di Object/Data Property

In pratica eliminiamo del tutto il concetto di "partecipazione obbligatoria", che è una cosa che non esiste nè in OWL nè in Protégé (dove in effetti nella pagina delle classi non vengono riportate nemmeno le tipizzazioni di ruoli e attributi). 

Ovviamente le altre opzioni sono o lasciare così com'è, oppure modificare in modo da attenerci all'intenzione iniziale (appunto suddividere gli assiomi in modo da non creare ridondanze, mettendo le partecipazioni obbligatorie nella card Object/Data Properties, e gli assiomi di tipizzazione nella pagina dell'Object o Data Property, nella card Domain/Range).

Che ne pensate?

**Comment by savo-fabio** [comment]
Sono d'accordo con quanto suggerisce Valerio: 
- TUTTI gli assiomi SubClassOf vanno a finire dentro la card SubClasses della pagina delle Class
- TUTTI gli assiomi Object/Data Property Domain/Range vanno a finire dentro la card Object/Data Properties della pagina della Class, e dentro la card Domain/Range delle pagine di Object/Data Property

Forse potremmo aggiunggere a fianco di tali assiomi delle frasi tra parentesi del tipo: 
mandatory partecipation, domain typing, range typing, ecc. Giusto per semplificare la lettura. Con la nuova suddivisione in tab del modulo di navigazione dell'ontoloiga mi sembra esserci spazio a sufficienza.

**Comment by valeriosantarelli** [comment]
Si, si possono certamente introdurre tutta una serie di strumenti per agevolare l'interpretazione del contenuto delle card, ad esempio tooltips, info buttons, frasi tra parentesi, etc. etc.
Questo ovviamente a prescindere dalla politica che adottiamo.

**Comment by valeriosantarelli** [comment]
Non ricordo se questo era stato implementato o meno. Per il momento chiudo e metto in quarantena.
