### ISSUE TITLE
[Cards] popup

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#123]
Inserire in generale sulle card un pulsante (magari in alto a destra nella card) che faccia in modo di produrre una finestra popup (modale) con il contenuto della card.
Questo è utile per tutte quelle situazioni in cui il contenuto della card è grande, e si deve scrollare o vedere una preview parziale.

In sostanza una soluzione analoga a quella proposta per le descrizioni nella issue #9

**Comment by giacomoronconiobda** [comment]
Specificare in quali casi si vuole rendere una card fullscreen, la soluzione generale mi sembra troppo drastica

**Comment by valeriosantarelli** [comment]
Per il momento si può soprassedere a questa issue.
