### ISSUE TITLE
[Ontology - Endpoint] "Full SPARQL" Button per attivazione EQL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#125]
Inserire un toggle button a fianco a quello di Reasoning con etichetta "Full 
SPARQL". 
Di default il bottone dovrebbe essere su "ON" (assumendo che il motore EQL sia stato integrato), ma l'utente può spegnerlo. Questa azione dovrebbe comportare un qualche warning che il frammento supportato di SPARQL è più ristretto (UCQ).

Naturalmente questo intervento è subordinato all'aggiungere il supporto alle query EQL.
Quello che dovrebbe succedere in sostanza è che la query SPARQL viene parsata prima con il nostro parser: se l'esito è positivo, viene eseguita; se l'esito è negativo, viene parsata dal parser EQL (se il pulsante FULL SPARQL è ON, altrimenti messaggio di errore) e in caso di parsing corretto, viene eseguita.

**Comment by giacomoronconiobda** [comment]
Bisogna aggiungere il query param alla chiamata /owlOntology/{name}/version/mapping/{mapID}/query/start

**Comment by roodsey** [comment]
Con l'integrazione del motore EQL la scelta effettuata è di utilizzare full SPARQL senza soluzione di continuità in base a quanto richiesto dalla query. 
Questa issue pertanto non sussiste più.
