### ISSUE TITLE
Mapping creato, non visualizzato

### ISSUE THREAD

**Issue by roodsey** [obdasystems/monolith#126]
A seguito della creazione di un file di mapping per il concetto "Accesso" dell'ontologia "ACI_Open_Data" versione "http://lod.aci.it/ontology/1.0.2". Il file di mapping creato ha ID "pillo" versione "1.1.0". CLiccando sul tab "Ontology Mappings" e selezionando il concetto ".../Accesso" (il primo della lista), il sistema restituisce un errore "n.state.data is null" e il mapping non viene visualizzato. Notare che il mapping è correttamente creato nel file XML.

**Comment by valeriosantarelli** [comment]
Più in generale, il sistema restituisce un errore quando si cerca di visualizzare qualsiasi mapping.
