### ISSUE TITLE
[Ontology] Cannot create new ontology on Safari

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#128]
Il drawer per la creazione di una nuova ontologia non funziona su Safari (non si vedono i pulsanti sotto).

<img width="1434" alt="Schermata 2019-06-22 alle 17 28 19" src="https://user-images.githubusercontent.com/8250758/59965809-41101100-9513-11e9-87e4-968910d41fc2.png">

**Comment by giacomoronconiobda** [comment]
Mi manca un mac per poterlo correggere. :)
