### ISSUE TITLE
[Ontology - Endpoint] Creazione KG da CONSTRUCT query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#136]
Se scelgo di creare un nuovo Knowledge Graph a partire dai risultati di una CONSTRUCT, quando premo OK sul drawer, dopo aver inserito tutti i metadati del nuovo KG, il KG viene creato, ma il sistema restituisce il drawer aperto invece di riportarmi alla pagina dell'endpoint oppure a quella del nuovo KG.
In pratica sembra che il nuovo KG non sia stato creato (quando in effetti lo è stato).

<img width="560" alt="Schermata 2019-06-30 alle 09 42 25" src="https://user-images.githubusercontent.com/8250758/60393844-fcd8ce00-9b1b-11e9-9157-a28d48a8d618.png">

**Comment by valeriosantarelli** [comment]
Stessa cosa per il Drawer di aggiunta di un nuovo mapping.

**Comment by giacomoronconiobda** [comment]
In generale il pattern di creazione delle card è questo:
1. click su + 
2. compilazione form nel drawer
3. si chiude il drawer e appare la nuova card

Se capisco bene qui si vuole cambiare il pattern cambiando il punto 3. in:

3. si chiude il drawer e si apre la card appena creata.

Questo pattern deve avvenire su tutte le card + drawer?

**Comment by valeriosantarelli** [comment]
No, credo che il comportamento ora sia quello corretto: si chiude il drawer e appare la nuova card.
