### ISSUE TITLE
[Home Page] Ontologie/KG eliminati

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#138]
Una ontologia o KG che viene eliminata continua a essere mostrata nella home page.
Ovviamente se poi si sceglie viene generato un errore.

**Comment by giacomoronconiobda** [comment]
Traduco: le ontologie eliminate devono essere eliminate anche dalla chiamata lastLoadedOntologie

**Comment by roodsey** [comment]
E quindi la 174 non era affatto l'ultima...
