### ISSUE TITLE
[Ontology - Mapping] Database privacy

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#14]
E' necessario introdurre una separazione, proprio a livello fisico, tra i mapping e i parametri di connessione al database. Per evidenti motivi di privacy e di sicurezza, non è possibile che i parametri di connessione al database siano scritti dentro il file di Mapping (come ci ha già evidenziato ACI, e come ci ha già prospettato ISTAT).

Bisogna quindi creare, forse solo a livello di interfaccia, un concetto di Connessione, che si può creare (una o più, note solo all'utente connesso) e quindi associare ad un file di Mapping.

In questo modo, quando Mastro si avvia, lo può fare con il mapping a cui è stata associata una connessione (altrimenti restituisce un segnale di errore), ma quando si ispeziona, si scarica, etc. il file di mapping, non sono presenti riferimenti ai parametri di connessione al database, che sono dati sensibili.

**Comment by roodsey** [comment]
Realizzato un meccanismo di store dei dati sensibili per la connessione al DB nel file 
`$MASTRO_HOME/mastro.datasources`

Il contenuto del file è strutturato in JSON secondo l'esempio che segue:
```
{
  "dataSourceInfoEntries" : [ {
    "id" : "S1",
    "description" : "test data source",
    "dataSourceUsername" : "utente-mastro",
    "jdbcUrl" : "jdbc:mysql://localhost/books",
    "jdbcDriver" : "com.mysql.jdbc.Driver",
    "jdbcUsername" : "root",
    "jdbcPassword" : "the-password"
  } ]
}
```
Nel file di mapping sarà sufficiente inserire l'elemento che segue:
`<dataSource name="S1" />`
Aggiunta ai webservices la rotta `/datasource` corredata dei verbi GET, PUT, POST e DELETE per permettere l'inserimento di credenziali da Monolith.
Lascio la issue aperta e la assegno a @giacomoronconiobda per avviare il lavoro di creazione delle strutture di immissione delle credenziali da memorizzare
