### ISSUE TITLE
Disabilitare autocomplete del browser 

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#143]
Capire su quali Input bisogna disabilitare l'autocomplete del browser.

`<Input autoComplete="off"/>`

**Comment by valeriosantarelli** [comment]
Non ho la minima idea di cosa si stia parlando.
Contestualizzare la issue (perlomento dicendo se è un bug, un enhancement, o altro), e magari fornire un esempio o qualcosa che mi aiuti a capire.

**Comment by valeriosantarelli** [comment]
Domanda: questa issue è rilevante anche nel caso di implementazione di Monolith come applicazione Desktop tramite Electron?
