### ISSUE TITLE
[Ontology - Mapping] Controllo di validità del mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#15]
Non viene effettuato, al momento del caricamento di un nuovo mapping, un controllo di validità rispetto all'ontologia: ho provato a caricare il file di mapping di ISTAT sull’ontologia Books, e me l’ha fatto fare. Successivamente, quando ho provato a ispezionare i mapping, il sistema restituiva errori.

In un ambiente che al momento non permette di fare editing credo che per forza si debba imporre che la specifica sia corretta. In un secondo momento, quando permetteremo almeno di fare editing dei mapping, si potrebbe pensare ad introdurre tutte le funzioni di mapping analysis, ed eventualmente di correzione della specifica.

**Comment by roodsey** [comment]
Aggiunto parametro di query "check" alla rotta POST per il caricamento dei mapping (/owlOntology/{name}/version/mapping/). Quando il parametro è presente e posto a "true" si effettua il controllo sui mappng inviati tramite la POST. In caso di mapping corretti il metodo continua a restituire l'oggetto Mapping; viceversa, in caso di errore il metodo restituisce un oggetto di tipo MappingsCheckResult che contiene una lista di errori rilevati nel file di mapping.

**Comment by roodsey** [comment]
Rimane da integrare la funzionalità nell'interfaccia

**Comment by valeriosantarelli** [comment]
Al caricamento di un file di mapping con riferimento ad altre ontologie, viene correttamente visualizzato il messaggio di errore ma poi il file di mapping viene comunque caricato.

Screenshot dei mapping attualmente caricati per l'ontologia IMBD su mws-dev:

<img width="1109" alt="Schermata 2019-05-28 alle 00 05 40" src="https://user-images.githubusercontent.com/8250758/58440736-9d327180-80dc-11e9-8462-73a178e0b1d0.png">

**Comment by roodsey** [comment]
Domanda 1): chi ha fatto il deploy della nuova versione? Mi risulta che il WAR depoyato attualmente risale al 22 maggio. 
Domanda 2): nel repository "/opt/mastro-home" di OBDATEST ci sono solo due ontologie (BOOKS e HALLO_MARK)... di IMDB nessuna traccia

**Comment by valeriosantarelli** [comment]
Allego la specifica movie

[movie.zip](https://github.com/obdasystems/monolith/files/3226369/movie.zip)

Non so chi abbia fatto il deploy (se qualcuno), forse ho testato prematuramente il fix. Dovremmo mettere in piedi un meccanismo per indicare se e su che istanza ogni issue chiusa può essere verificata.

**Comment by roodsey** [comment]
Per la cronaca: ho appena fatto il deploy della versione corrente di MWS
