### ISSUE TITLE
[Footer] Versioni

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#153]
Inserire nel footer (prima di "OBDA Systems @ 2018 - anno attuale):

- la versione di Monolith
- la versione di Jena che si sta usando nella sezione KG
- la versione di Grapholscape caricata dentro Monolith

Per aiutare il lavoro di test, tutti i rilasci interni di Monolith dovrebbero prevedere una nuova versione, tipo 0.2.1, 0.2.2, 0.2.3.
Non importa se arriviamo a una versione 0.2.165, basta che siamo sempre in grado di capire quale versione stiamo utilizzando, e fare eventualmente riferimento nelle issue che si aprono/chiudono.

**Comment by roodsey** [comment]
Creata la rotta /jena/version per recuperare la versione della libreria di jena-tdb utilizzata a runtime.
Per le versioni di Monolith e Grapholscape occorre ingaggiare i rispettivi sviluppatori.
In altre parole #giroaronconi @giacomoronconi
