### ISSUE TITLE
[Home Page] Mastro

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#156]
Nella Home Page, prevedere di visualizzare le seguenti informazioni in apposite card (oppure in altra forma, poi capiremo meglio dove metterle):

Mastro
- Versione
- Connection URL
- Running Mastro Instances

Si potrebbe ripristinare la riga in fondo (sotto quelle di Recent Ontologies e Recent KGs), da dedicare a queste card, e poi di fianco una card per il tutorial, nella speranza che prima o poi ci sia.

**Comment by roodsey** [comment]
Aggiunte le rotte seguenti:

- /mastro/version: restituisce una stringa contenuta nella property "mastro.version" del file "mastro.info.properties": tale file viene automaticamente popolato da Maven in fase di build del progetto con il valore dell'elemento "project.version" del pom.xml di mastro-gui-api
- /mastro/instances: restituisce una lista di oggetti MastroID

**Comment by valeriosantarelli** [comment]
Le informazioni da mostrare sono attualmente mostrare, ma in modo un pò "sparpagliato".
La versione di Mastro sta nel footer, l'indirizzo sta sul pop-up che compare quando si va sopra il pulsante logout, e le istanze di Mastro sono visualizzabili nella pagina Endpoint.
Secondo voi va bene così, oppure sarebbe il caso comunque di prevedere uno spazio nella home page per Mastro?

**Comment by giacomoronconiobda** [comment]
Secondo me non serve la home di Mastro le informazioni sono sparpagliate perchè raggruppate ad altre cose:

- utente/connessione
- tutte le versioni nel footer
- endoint runnng nella rispettiva pagina

**Comment by valeriosantarelli** [comment]
Questa si può chiudere.
