### ISSUE TITLE
[Ontology - Mapping] mapping metadata

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#17]
- [x] I mapping dovrebbero avere i seguenti meta-dati: Nome, Versione, Descrizione, Data creazione, Data Ultima Modifica. Tutti questi dovrebbero essere riportati nella Mapping Card (ora c'è nome e descrizione). Questo ovviamente va supportato sia a livello Monolith che a livello di plug-in di Protégé (almeno finchè non ce ne liberiamo definitivamente).

- [x] Un mapping può avere al massimo una descrizione (lo decidiamo noi imponendolo nella struttura del file XML dei mapping, quindi non c'è bisogno che in Mapping Info, la Card description contenga una tabella.

- [x] Nella Mapping Card, i tre tasti in basso hanno un comportamento non omogeneo, nonostante sia presentino nello stesso modo: Info è solo un hover, e non può essere premuto, gli altri due invece possono essere premuti. Forse si potrebbero distinguere in qualche modo? (non è cruciale comunque)

- [x] Sempre nella Mapping Card, per omogeneità con quanto fatto in Ontology Documentation, userei il termine "Metrics" invece di "Info"

**Comment by valeriosantarelli** [comment]
Punti 2, 3, 4 OK

**Comment by roodsey** [comment]
Rappresentate ID, VERSION e DESCRIPTION dei mapping aggiungendo il seguente elemento al file XML:

```
<mappingsMetadata id="MAP_01" version="1.0.2">
    <description>Description of mappings MAP_01 version 1.0.2</description>   
</mappingsMetadata>
```
