### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#174]
Nella log mostrato ci sono due cose da aggiustare:

- vengono visualizzate in chiaro le credenziali per tutti gli utenti noti all'applicazione. Questo non credo sia molto auspicabile.

<img width="498" alt="Schermata 2019-12-11 alle 12 13 22" src="https://user-images.githubusercontent.com/8250758/70616859-b1b90000-1c0f-11ea-858f-2d2397761616.png">

- vengono ripetute molte volte delle righe vuote, rendendo il log inutilmente lungo.

<img width="636" alt="Schermata 2019-12-10 alle 17 06 42" src="https://user-images.githubusercontent.com/8250758/70616894-c3020c80-1c0f-11ea-9384-e6ff894f2df6.png">

**Comment by roodsey** [comment]
Prima issue chiusa nell'anno 2020!

**Comment by valeriosantarelli** [comment]
> Prima issue chiusa nell'anno 2020!

E ovviamente anche l'ultima!

**Comment by roodsey** [comment]
Questa è una speranza... ma temo sia vana
