### ISSUE TITLE
Logo Monolith nel Main Menu quando evidenziato

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#176]
Il logo di Monolith quando si è nella home page si vede male, perchè il colore di una parte della M e il colore di highlight nel menu sono lo stesso.

Bisogna trovare un colore diverso per uno dei due, oppure un meccanismo diverso di evidenziamento.

<img width="178" alt="Schermata 2019-12-10 alle 16 32 31" src="https://user-images.githubusercontent.com/8250758/70617635-4ec86880-1c11-11ea-8ffb-0933f76662e0.png">

**Comment by giacomoronconiobda** [comment]
Cambio colore evidenziamento

**Comment by valeriosantarelli** [comment]
Direi che va bene.
