### ISSUE TITLE
[Ontology - Mapping] Ontology Mapping Tab

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#18]
- [x] Nel titolo della pagina, invece che solo il nome del predicato, scrivere “Mappings for xyz"

- [x] Colorare o evidenziare in qualche modo il nome delle viste dentro i mapping, e renderlo cliccabile (che riporti alla pagina della vista stessa ovviamente)

- [x] Per il mapping di un ruolo o attributo, dentro la riga Head, scrivere espressamente Domain e Range.
Ad esempio:
Domain: http://www.obdasystems.com/demo/superheroes/character_{ch_id} 
Range:   http://www.obdasystems.com/demo/superheroes/ability_{ab_name}

**Comment by valeriosantarelli** [comment]
Punti 1 e 4 OK

**Comment by giacomoronconiobda** [comment]
#19

**Comment by giacomoronconiobda** [comment]
Legata alla #19
