### ISSUE TITLE
[Ontology - Navigation] Description e Metrics

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#182]
Attualmente la card Description copre tutta la larghezza della pagina, in modo probabilmente poco utile. 

Si potrebbe ridurre la dimensione della card (tipo 2/3 della pagina) e mettere una card Metrics di fianco, in cui riportare delle statistiche riguardanti l'entità selezionata. Ad esempio il numero di mapping, in quanti assiomi è coinvolti, quante sottoclassi o superclassi ha, etc. etc.

**Comment by valeriosantarelli** [comment]
Nella card è visibile solamente una statistica (per le classi le SubClasses, per le object properties le SubObjectProperties, e per le data properties le SubDataProperties).

**Comment by giacomoronconiobda** [comment]
https://github.com/obdasystems/monolith/commit/6a4b2d014c161f58f3805361b3eefea7811ce12a

**Comment by valeriosantarelli** [comment]
Riporto sotto una lista più o meno esaustiva (occhio alle lettere maiuscole...)

-  Metrics per Classi
- [ ] Super Classes
- [ ] Sub Classes
- [ ] Disjoint Classes
- [ ] Equivalent Classes
- [ ] Disjoint Unions (questo al momento è vuoto)
- [ ] Object Properties
- [ ] Data Properties
- [ ] Individuals
- [ ] Annotations
- [ ] Mappings (inteso come numero di mapping per questa entità

- Metrics per Object Property
- [ ] Domain
- [ ] Range
- [ ] Super Object Properties
- [ ] Sub Object Properties
- [ ] Disjoint Object Properties
- [ ] Equivalent Object Properties
- [ ] Inverse Object Properties
- [ ] Object Property Characteristics
- [ ] Annotations
- [ ] Mappings

- Metrics per Data Property
- [ ] Domain
- [ ] Range
- [ ] Super Data Properties
- [ ] Sub Data Properties
- [ ] Disjoint Data Properties
- [ ] Equivalent Data Properties
- [ ] Object Property Characteristics
- [ ] Annotations
- [ ] Mappings

- Metrics per Individuals
- [ ] Classes
- [ ] Same As
- [ ] Different

**Comment by giacomoronconiobda** [comment]
Due osservazioni: 
- i campi "Mappings" non possono essere riempiti: il file di mapping non è univoco dentro l'ontology navigation
- i campi vuoti denotano un valore null restituito da mws. Non sono sicuro dell'interpretazione, potrebbe essere unimplemented oppure vuoto. Sarebbe meglio indagare.

Procedo con il renaming e l'ordinamento degli altri.

**Comment by valeriosantarelli** [comment]
> Due osservazioni:
> 
> * i campi "Mappings" non possono essere riempiti: il file di mapping non è univoco dentro l'ontology navigation
> * i campi vuoti denotano un valore null restituito da mws. Non sono sicuro dell'interpretazione, potrebbe essere unimplemented oppure vuoto. Sarebbe meglio indagare.
> 
> Procedo con il renaming e l'ordinamento degli altri.

Sulla prima hai ragione (lo sapevo eh, volevo vedere se eri attento.. :D)
Ok sul secondo.

**Comment by valeriosantarelli** [comment]
@giacomoronconiobda potresti aprire una issue a @roodsey riguardo i campi vuoti, così magari gli indichi anche le chiamate che risultano vuote? Così questo lo chiudiamo una volta per tutte

I campi che al momento sono vuoti sono:

- Disjoint Unions per le classi
- Inverse Properties per le object properties

**Comment by giacomoronconiobda** [comment]
fatto #245
