### ISSUE TITLE
[SQL Views] Pulsante New Mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#183]
Rimuovere dalla pagina delle SQL Views il pulsante di creazione di un nuovo mapping. Se si vuole creare un nuovo mapping, si va nella pagina dei mapping dell'elemento scelto, e se ne aggiunge uno da lì.
Attualmente peraltro il pulsante è rotto, porta ad una pagina vuota.

Questa issue è subordinata all'introduzione del nuovo Mapping Editor #162

**Comment by giacomoronconiobda** [comment]
Non dovrebbe sussistere dopo nuova visualizzazione mapping assertions
