### ISSUE TITLE
Pulsantoni Card Add XXX

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#184]
Rimuovere da ovunque i pulsantoni a forma di Card "Add xxx".

Sostituirli con una barra di ricerca con di fianco un pulsante "+" (come quello per aggiungere una SQL View" da mostrare in cima alla pagina, che funge da campo di ricerca, e anche da pulsante di aggiunta di una nuova cosa nella pagina.
Possiamo valutare insieme se questa soluzione è ragionevole o meno.

Implementare la funzionalità di ricerca nel seguente modo (scrivendo la parte in virgolette nel testo del campo):
- [x] Mapping dentro SQL Views -> "Search by Ontology Entity"
- [x] Mapping dentro Ontology Mappings -> "Search by SQL View"
- [x] Ontology card dentro Ontologies -> "Search by Ontology name"
- [ ] Ontology Version card dentro Ontology Versions -> "Search by Ontology Version"

**Comment by giacomoronconiobda** [comment]
L'ho fatto anche Knowledge Graph

**Comment by valeriosantarelli** [comment]
Per Ontology Versions è rimasto il pulsante grosso perchè si può trascinare dentro un file giusto?
Per me va bene, poi vediamo se usandolo la cosa crea problemi.
