### ISSUE TITLE
Tab query tra una sessione e l'altra

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#188]
Chiudere tutti i tab delle query aperti nella precedente sessione di lavoro quando si inizia una nuova sessione.

**Comment by giacomoronconiobda** [comment]
Che si intende per sessione? Devo eliminare le informazioni quando si fa logout?

**Comment by valeriosantarelli** [comment]
secondo me si, quando si fa logout oppure si spegne il server.

**Comment by giacomoronconiobda** [comment]
Ok per il logout. Se dobbiamo azzerare le tab anche dopo lo spegnimento del server le tab aperte dovrebbe tenerle salvate il server o inventare un modo per far "scadere" le tab

**Comment by valeriosantarelli** [comment]
> Ok per il logout. Se dobbiamo azzerare le tab anche dopo lo spegnimento del server le tab aperte dovrebbe tenerle salvate il server o inventare un modo per far "scadere" le tab
In effetti forse allo spegnimento del server non è necessario.
Ad esempio pgAdmin non lo fa mi pare: se il browser è aperto e si spegne il server sotto, il browser non è che cambia, rimane lì appeso.
Stessa cosa per GraphDB.

**Comment by valeriosantarelli** [comment]
Questa issue è una replica della #300 
Chiudo
