### ISSUE TITLE
Errore esecuzione query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#189]
La query "special_edition_books" della specifica Books, reperibile nel query catalog presente qui: https://github.com/obdasystems/OBDA-Specifications/tree/master/Books/1.0.1

non termina l'esecuzione su Monolith, ma anzi fa freezare l'applicazione.

Se eseguita sul plug-in di Protégé, la query termina correttamente dopo circa 5 secondi.

**Comment by roodsey** [comment]
Testata con mapping version 1.0.2 (cartella 1.0.1 di github) funziona
