### ISSUE TITLE
[Ontology - Mapping] SQL Views Tab

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#19]
- [x] Scorporare il nome della view dalla prima card in alto, e utilizzarlo come titolo della pagina. Nella prima card si può lasciare quindi solo la descrizione della vista e la query SQL

- [x] Nelle card degli ontology mappings, aggiungere l'ID del mapping e renderlo cliccabile, in modo da riportare direttamente alla pagina del mapping. Ora c'è il nome del predicato, e correttamente è cliccabile, però non c'è modo di andare alla pagina proprio del mapping.

- [x] Aggiungere la possibilità di fare girare la query della vista in modalità preview (come nel plug-in)

**Comment by giacomoronconiobda** [comment]
@valeriosantarelli il meccanismo di ridirezionamento tra mapping e viste non penso sia molto utile almeno da viste a mapping. Infatti nella pagina dei Mapping non ci sono informazioni in più rispetto a quelle presenti nella pagina delle viste. Inoltre non esiste il concetto di ID del mapping se ricordi.

**Comment by valeriosantarelli** [comment]
> @valeriosantarelli Inoltre non esiste il concetto di ID del mapping se ricordi.
Come non esiste l'id di un mapping? Non l'abbiamo previsto tra le risorse?
Non credo possiamo farne a meno, se c'è più di un mapping per un predicato come si distinguono?

<img width="531" alt="Schermata 2019-04-05 alle 11 01 21" src="https://user-images.githubusercontent.com/8250758/55616470-2fc82b80-5792-11e9-8660-313d10099dcd.png">
