### ISSUE TITLE
Rendering by entityID

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#191]
E' possibile eliminare questa opzione?

Non riesco ad immaginarmi per quale motivo qualcuno vorrebbe vedere i predicati elencati con il loro ID interno, e a maggior ragione crea confusione rispetto alle altre modalità di rendering, dato che non è chiaro cosa significhi l'"ID" di una Entity.

**Comment by giacomoronconiobda** [comment]
Rendere by entity id è utile per il debug

**Comment by valeriosantarelli** [comment]
Se al primo release ufficiale di Monolith ci sarà ancora render by entityID, ti denuncio.
Ti scateno contro tutta la potenza legale di OBDA Systems.
