### ISSUE TITLE
Pannello Admin

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#194]
Introdurre un pannello Admin, accessibile da una voce nel menu principale (sopra a Settings, e visibile ovviamente per l'utenza amministratrice, ovvero mastro), che preveda le seguenti funzionalità (poi le aggiungiamo man mano che ci vengono in mente):

- [x] creazione di un nuovo utente
- [x] cancellazione di un nuovo utente
- [x] modifica diritti ad un utente
- [x] monitoraggio dello stato di esecuzione delle query

**Comment by giacomoronconiobda** [comment]
Inizierei a fare il mockup. Pensi sia ragionevole un layout a Card tipo Ontologies: una Card per utente?

**Comment by valeriosantarelli** [comment]
> Inizierei a fare il mockup. Pensi sia ragionevole un layout a Card tipo Ontologies: una Card per utente e drawer per modifica?
> 
> Dopodichè dobbiamo iniziare a modellare le risorse. Forse possiamo partire dall'oggetto che abbiamo già definito: `com.mwsx.model.User`

Beh oddio forse gli utenti potrebbero essere troppi per un layout a card...forse potrebbe essere meglio una cosa tipo quella che c'è per i Denial o come gli Endpoints? Quindi elenco sulla sinistra con l'aggiunta tramite drawer, e sulla destra poi quando si sceglie un utente vengono fuori le sue info.

**Comment by giacomoronconiobda** [comment]
Possiamo fare le card più piccole. Mi sembra ci siano poche informazioni per utente da metterel tutte in una pagina

**Comment by valeriosantarelli** [comment]
Non potremmo invece fare una cosa del genere(ovviamente con le opportune informazioni su ciascuna riga)?

![image](https://user-images.githubusercontent.com/8250758/81051074-66a2d080-8ec1-11ea-9974-9519e6fa4ec3.png)

![image](https://user-images.githubusercontent.com/8250758/81051097-702c3880-8ec1-11ea-82f7-397977ddf034.png)

**Comment by giacomoronconiobda** [comment]
Solo se mettiamo una colonna `gay' con un grado che puòl andare da 0 a 5

**Comment by valeriosantarelli** [comment]
Che naturalmente sarà sempre 5.

**Comment by giacomoronconiobda** [comment]
Ho aggiunto la parte di permissions al mock up. Fatemi sapere se devo cambiare qualcosa

**Comment by valeriosantarelli** [comment]
Qualche micro-osservazione al mock-up:

- [ ] la P di Permissione maiuscola nel titolo del tab 
- [ ] si può allungare il menu in alto verso sinistra così non rimane lo spazio vuoto prima di Users
- [ ] Domain, actions, e permissions con al prima lettera maiuscola nella riga di intestazione della tabella
- [ ] secondo me la barra di ricerca dentro il ruolo (dove c'è scritto Search permissions) si può togliere, non so quanto significativo fare filtri lì dentro

**Comment by giacomoronconiobda** [comment]
La barra la lascerei per puro estetismo così è uguale all'altra. Per quanto riguarda le colonne di User? Ci convince la modifica dentro la tabella? Vogliamo mettere un tasto submit?

**Comment by valeriosantarelli** [comment]
Ma lo scope della ricerca quale sarebbe? Tutt'e tre i campi, oppure solo il campo Resource? Comunque vabbè per il momento lasciamolo, basta che il comportamento del filtro sia chiaro. Se risulta poco comprensibile lo toglieremo oppure metteremo dei filtri sulle singole colonne.

Si, il tasto submit ce lo metterei. In pratica se si fa una modifica nella riga, viene abilitato il tasto submit, così è chiaro quando c'è una modifica da salvare o meno.

**Comment by valeriosantarelli** [comment]
Se prevediamo di mettere la password degli utenti dentro la tabella, prevederei anche il classico tasto con l'occhiolino per mostrarla in chiaro (magari previa l'inserimento della password).

**Comment by giacomoronconiobda** [comment]
Mock up completato
