### ISSUE TITLE
[Query Catalog] Collassato

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#202]
Dobbiamo trovare una cosa migliore da far vedere dentro il query catalog quando è collassato.

Attualmente si vede solo una cosa del genere:

<img width="123" alt="Schermata 2019-12-19 alle 09 53 23" src="https://user-images.githubusercontent.com/8250758/71159203-818fe380-2245-11ea-88c4-83b21635a5f7.png">

che ovviamente fa schifo.

Una idea potrebbe essere di lasciare la Scritta Query Catalog, ma in verticale (ovviamente con il testo ruotato) e solo il pulsante di espansione/collasso in basso.

**Comment by giacomoronconiobda** [comment]
Dei numeri sequenziali? Magari li facciamo vedere anche a menu aperto...

Il gio 19 dic 2019 09:55 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
La cosa che non mi piace tanto è che la lista dovrebbe essere una lista numerata quindi, mentre tutte le altre liste dentro i vari alberi non lo sono: mi piaceva l'idea di avere una iconcina di fianco a tutte le cose nelle varie liste, come è adesso per concetti, ruoli, e attributi.

Se lasciassimo solo l'iconcina, e mettessimo comunque sull'hover in popup il nome della query?
Questo forse si potrebbe fare anche a menu aperto, così risolviamo anche il problema dei nomi delle query lunghe che non si leggono:

<img width="282" alt="Schermata 2019-12-19 alle 23 26 41" src="https://user-images.githubusercontent.com/8250758/71215105-226ab700-22b7-11ea-891f-1b9a76fe886b.png">

**Comment by valeriosantarelli** [comment]
La mia proposta di lasciare l'iconcina è orribile. La resa è brutta, e temo sia poco utilizzabile.

Contro-proposte:
a) lasciamo il Query Catalog non collassabile
b) lo facciamo collassare tramite shortcut da tastiera (tipo Command-B di Visual Studio)
