### ISSUE TITLE
Modifica di una datasource non registrata

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#204]
Se viene modificata una datasource già associata ad un mapping, il sistema non sembra accorgersene.

Ad esempio, avevo creato la datasource "imdb" per il db di movie ontologie, non inserendo una password perchè avevo lasciato la password di root su mysql vuota. 
Avevo poi creato il mapping associandolo a quella datasource.
Ho poi settato la password di root per la connessione a mysql, e modificato di conseguenza la datasource "imdb", impostando la password.

Quando vado però sulla pagina dell'endpoint, al momento di caricare la pagina, il sistema restituisce un errore perchè sta cercando di collegarsi al database senza password di autenticazione:
<img width="1438" alt="Schermata 2020-01-10 alle 11 29 47" src="https://user-images.githubusercontent.com/8250758/72146834-97ed1300-339d-11ea-958e-ebb10c705e93.png">

**Comment by giacomoronconiobda** [comment]
Penso sia un problema del server, #giroaroodsey

**Comment by roodsey** [comment]
@valeriosantarelli verificare se la issue è ancora valida

**Comment by valeriosantarelli** [comment]
Credo che in effetti la issue non sia più valida, avendo inserito il concetto di endpoint.

Ho fatto questo:
- creato un datasource con parametri (password) sbagliata
- provato ad avviare l'endpoint, e giustamente il sistema ha dato errore
- dalla pagina di SPARQL il sistema dice di avviare un endpoint dato che non ce n'è alcuno che sta girando
- sono tornato sul datasource, ho corretto i parametri, e avviato l'endpoint
- ho provato a fare una query, e ha dato risultati

A questo punto chiudo, se serve si riapre
