### ISSUE TITLE
Endpoint e SPARQL: rifiniture estetiche

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#205]
- [ ] Rimuovere il popup sull'hover nel pannello delle query quando si va sopra l'endpoint selezionato (ora è vuoto)
<img width="455" alt="Schermata 2020-01-20 alle 11 35 22" src="https://user-images.githubusercontent.com/8250758/72720322-f7a3a500-3b79-11ea-9664-601a542c1f54.png">

- [x] Chiamare la voce del menu che attualmente si chiama "Endpoint" invece "SPARQL" (nel menu Ontology)

- [x] Nel menu principale, per la voce Endpoint, al posto dell'orrida "M" (o in attesa di disegnare un logo per Mastro) usare un logo tipo fulmine (che è poi richiamato dall'icona con la lente di ingrandimento con il fulmine che usiamo per la pagina delle query). Tipo questo: https://fontawesome.com/icons/bolt?style=solid

- [x] Nella pagina dell'endpoint, in fondo c'è un elemento di sfondo della pagina che in realtà è a un livello sopra, quindi quando si fa scroll verso il basso, nasconde il box dei mapping e datasource
<img width="1293" alt="Schermata 2020-01-20 alle 11 46 06" src="https://user-images.githubusercontent.com/8250758/72720586-9af4ba00-3b7a-11ea-81b4-8ba1a487beb8.png">

- [x] Nella pagina delle query, se ci si arriva e non c'è manco un endpoint già attivo, far comparire un avviso che rimanda alla pagina di Endpoint e dice di andarlo a creare.

- [ ] L'icona "play" vicino al nome dell'endpoint nella lista di endpoints compare solo quando l'endpoint è attivo. Dovrebbe essere un link alla pagina di endpoint? Oppure serve a qualcos'altro?

**Comment by giacomoronconiobda** [comment]
1) il popover fa vedere la descrizione. Ora aggiungo anche il mapping e la datasource se c'è

**Comment by valeriosantarelli** [comment]
> 1. il popover fa vedere la descrizione. Ora aggiungo anche il mapping e la datasource se c'è

Ok, vediamo come viene, non vorrei che fosse troppa roba da far vedere.

**Comment by giacomoronconiobda** [comment]
L'icona play marca nella lista gli endpoint running
