### ISSUE TITLE
Ontologie senza Graphol

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#210]
Gestire la situazione in cui l'ontologia non è stata caricata i graphol.

Ci sono diverse possibilità, dal disabilitare il pulsante Graphol dell'ontology menu, a far comparire un messaggio del tipo "No Graphol diagram provided, please go to the Navigation page to inspect the ontology", o qualsiasi altra cosa.

Al momento esce il messaggio di errore, e la pagina rimane in stato di caricamento all'infinito.

**Comment by giacomoronconiobda** [comment]
Implemento l'auto direzionamentoa Navigation. Se si vuole togliere l'elemento bisogna aggiungere questa informazione all'oggetto Ontology
