### ISSUE TITLE
POST/PUT Mapping Assertion

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#214]
Definire le rotte per l'aggiunta/modifica di un mapping assertion data:

- ontologia
- mapping
- codice sql del mapping da convertire in datalog per Mastro. Il codice può essere anche un oggetto specifico vista la presenza di un parser lato JS
- descrizione

**Comment by roodsey** [comment]
Revisione delle strutture dati di rappresentazione dei mapping incorso per permettere l'utilizzo in fase di GET tanto quanto in fase di POST/PUT
