### ISSUE TITLE
[Ontology - Endpoint] pulsanti nell'area della query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#22]
- [x] Piazzamento dei pulsanti intorno all'area di scrittura della query SPARQL:
Mettere il pulsante di avvio di Mastro a destra del menu a tendina di scelta dei mapping (va fatta prima la scelta poi premuto il pulsante, quindi da sinistra a destra il menu e poi il pulsante).
Spostare Run/Stop in basso a sinistra sotto l'area della query (quindi sotto la descrizione), spostare Store in catalog in basso a destra sotto l’area della query, e scrivere Reasoning a fianco al pulsante Toggle reasoner (identico a Stardog) e trovare una icona (oppure scrivere Choose Mapping) da mettere a fianco al file di mapping. Deve essere evidente cosa bisogna fare prima di eseguire la query, e a cosa servono i vari bottoni.

- [x] Modificare l'interazione quando si avvia Mastro. Va bene un pulsante di avvio, ma quando l'avvio è terminato con successo, deve uscire un messaggio trionfale (tipo pop-up anche) che confermi all'utente che Mastro è partito, non passare direttamente ad un pulsante con accezione negativa. Altrimenti non si capisce se l'operazione è andata o meno a buon fine.

- [x] Inibire il pulsante Run se Mastro non è avviato sul mapping attualmente scelto nel menu a tendina.

**Comment by giacomoronconiobda** [comment]
@roodsey  il server mi risponde 500 quando faccio GET su uno status di Mastro che non è running. :1st_place_medal:

**Comment by roodsey** [comment]
> @roodsey il server mi risponde 500 quando faccio GET su uno status di Mastro che non è running. 1st_place_medal

necessarie indicazioni per riprodurre l'errore

**Comment by valeriosantarelli** [comment]
Riguardo il punto 3: attenzione che il pulsante Run non viene abilitato automaticamente una volta che Mastro è avviato. E' necessario cambiare la scelta del mapping nel menu a tendina, e poi tornare sul mapping su cui è stato avviato Mastro per fargli registrare il cambiamento e abilitare il pulsante Run (testato su Books). Se invece c'è un solo mapping nel menu a tendina (ad esempio Superheroes), il pusante Run non viene abilitato proprio.

**Comment by valeriosantarelli** [comment]
Se Mastro viene stoppato dopo essere stato avviato, il pulsante Run rimane attivo. Allego screenshot in cui si vede il pulsante Run abilitato, ma Mastro non è avviato.

<img width="1026" alt="Schermata 2019-04-05 alle 10 38 30" src="https://user-images.githubusercontent.com/8250758/55615173-ffcb5900-578e-11e9-9c4b-b8eb4feeaafe.png">
