### ISSUE TITLE
Gestione driver JDBC

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#223]
Prendendo spunto dal fatto che dopo aver aggiornato la mia versione di MySQL, né il plugin di Protégé né Monolith erano in grado di connettervisi (jdbc driver troppo vecchio), potremmo ragionare su una gestione differente dei driver rispetto a quella attuale.
In pratica potremmo lasciare che sia l'utente a caricare i driver che vuole, senza doverli includere nel package di Mastro. Manuel mi diceva che Ontop fa una cosa del genere: forse di suo ha dentro solo quello di MySQL, ma certamente non altri, tipo Oracle, SQL Server, etc.
Tra l'altro la licenza del driver di Oracle non è completamente libera come quella di MySQL e Postgres, quindi non credo che possiamo infilarla dentro Mastro come dipendenza senza menzionare la licenza da qualche parte.

**Comment by giacomoronconiobda** [comment]
Non so quanto sia "sicuro" poter aggiungerere dei jar con delle rotte REST. Penso porti il codice ad essere facilmente attaccabile. Forse la cosa migliore è mettere una cartella nella mastro home dove il sistemista può mettere i driver che servono agli utenti.

**Comment by giacomoronconiobda** [comment]
Per quanto riguarda la release i driver JDBC verranno messi in una cartella lib dall'amministratore del sistema e inclusi nel class path con cui si lancia mws

**Comment by giacomoronconiobda** [comment]
Volevo togliere dal pom di mastro i driver JDBC. @mnamici dobbiamo aggiungere in qualche modo le dipendenze Al build deployato sul server, hai in mente già una soluzione?

**Comment by mnamici** [comment]
Dato che i driver non saranno parte né delle api di mastro, né dei servizi, e che questi ultimi vengono rimpiazzati ad ogni build credo la soluzione migliore sia farli fornire dall'application server, tomcat nel nostro caso.

Per quanto riguarda la distribuzione concordo con quanto sopra, anche se chiamerei la cartella `jdbc` e non `lib`, per renderlo esplicito. L'utente li copia manualmente nella cartella e lo script di avvio li inserisce nel classpath. Lato interfaccia si potrebbe prevedere un semplice feedback sui driver trovati nel classpath con relativa versione (ottenibili tramite il metodo `java.sql.DriverManager.getDrivers()`) da restituire attraverso una rotta REST.

**Comment by giacomoronconiobda** [comment]
Stiamo per rimuovere i driver jdbc da Mastro. Per far funzionare correttamente le istanze di mws  dovranno essere aggiunti nei classpath i driver che si desidera utilizzare. Siete tutti d'accordo?

**Comment by giacomoronconiobda** [comment]
Mi sembra di notare che **h2** viene utilizzato per le query eql quindi si tratterebbe di togiere solo **Mysql** e **Postgres**

**Comment by giacomoronconiobda** [comment]
https://stackoverflow.com/questions/1839671/finding-installed-jdbc-drivers

**Comment by roodsey** [comment]
Vorrei capire se abbiamo reale urgenza di rimuovere le dipendenze JDBC dai progetti: non stiamo ancora facendo rilasci pubblici, ma solo mirati per i progetti che abbiamo. Non avere i driver più comuni nei build al  momento ci crea solo difficoltà: fatemi sapere se ravvedete problemi nel posporre questa rimozione.

**Comment by roodsey** [comment]
Ho committato oggi una prima versione di data source manager generico: per utilizzarlo, al momento, è sufficiente passare nel campo driver per la creazione del data source manager una stringa fatta così:
```
generic:driver_class_name
```
ad esempio:
```
generic:com.mysql.cj.jdbc.Driver
```
Il mapping manager provvederà ad istanziare il data source manager generico.
Per utilizzare la funzionalità da Monolith occorre modificarne i sorgenti in modo da permettere testo libero nella casella scelta del driver JDBC (cosa da fare solo nelle proprie installazioni locali, ma che permette di fare test da parte di tutti, cosa fondamentale visto l'impatto della modifica).
Aprire il file "monolith/src/pages/settings/DatasourceForm.js" esostituire la porzione di codice
```
<Form.Item label="JDBC Driver"
                name='jdbcDriver'
                rules={[{ required: true, message: 'Please enter datasource JDBC Driver' }]}>
                <Select placeholder='Please select JDBC driver' onSelect={this.onSelect}>
                  {this.state.drivers.map(i => <Select.Option key={i} value={i}>{i}</Select.Option>)}
                </Select>
</Form.Item>
```
con la seguente:
```
<Form.Item label="JDBC Driver"
                name='jdbcDriver'
                rules={[{ required: true, message: 'Please enter datasource JDBC Driver' }]}>
                <Input placeholder="Please enter JDBC Driver" />
</Form.Item>
```
e commentare l'importazione del controllo "select" alla riga 3 dello stesso file:
```
Form, Button, Col, Row, Input, //Select,
```

**Comment by roodsey** [comment]
Mi rimuovo dalla issue, i futuri interventi per la correzione di bug andranno canalizzati in issue diverse, specifiche per i bug.

**Comment by valeriosantarelli** [comment]
> Vorrei capire se abbiamo reale urgenza di rimuovere le dipendenze JDBC dai progetti: non stiamo ancora facendo rilasci pubblici, ma solo mirati per i progetti che abbiamo. Non avere i driver più comuni nei build al momento ci crea solo difficoltà: fatemi sapere se ravvedete problemi nel posporre questa rimozione.

@roodsey 
Non so se questo commento è ancora attuale oppure è stato sovrascritto da quelli successivi, comunque la situazione è la seguente.
I progetti in cui dovremo a breve (giugno/luglio) utilizzare Monolith sono sia ISTAT che INAIL, e per tutt'e due questi progetti dovremo poter consegnare una versione dell'applicazione che non viola le licenze di distribuzione dei driver che dovremmo utilizzare, che sono rispettivamente quelli di Oracle e Impala.
Se per il momento (o anche per sempre) ci fa comodo tenere dentro Mastro i driver di Postgres e MySQL non ci sono problemi formali, dato che sono open source, solo di gestione degli aggiornamenti (cosa che non facciamo mai...). Però non so quanto senso abbia mantenere una gestione ibrida dei driver, da un punto di vista tecnico non sono in grado di valutare se ha senso.

**Comment by valeriosantarelli** [comment]
@roodsey @giacomoronconiobda 

Non so se può essere in qualche modo di aiuto, ma se è problematico far individuare al sistema i driver che sono presenti se vengono semplicemente copiati dentro una cartella, riporto quanto fatto ad esempio da Ontop, in cui si richiede di registrare esplicitamente i driver che si vuole usare.

Ad esempio (dalla documentazione di Ontop):

> Protege -> Preferences -> JDBC Drivers tab -> Add
Description: Denodo
Class name: com.denodo.vdp.jdbc.Driver
Driver File (jar): browse to /.../DenodoPlatform7.0/tools/client-drivers/jdbc/denodo-vdp-jdbcdriver.jar

> Register the H2 JDBC driver: go to "Preferences", "JDBC Drivers" and add an entry with the following information
Description: h2
Class Name: org.h2.Driver
Driver file (jar): /path/to/h2/bin/h2-1.4.196.jar

Non so se per gestire questo tipo di meccanismo, Ontop debba essere già predisposto per "conoscere" questi driver o meno, comunque mi sembrava una cosa utile da riportare. Ovvero, non facciamoci problemi nel chiedere, se occorre, all'utente di registrare tramite interfaccia di Monolith esplicitamente i driver che vuole usare.

**Comment by giacomoronconiobda** [comment]
Questa è la soluzione proposta da Marco dove in pratica uno deve scrivere
la classe del JDBC driver. Un'altra soluzione potrebbe essere avere una
lista di driver noti e vedere se a runtime se sono inclusi nel class path

Il ven 24 apr 2020, 21:37 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by giacomoronconiobda** [comment]
Ho fatto una prova con [reflections](https://mvnrepository.com/artifact/org.reflections/reflections/0.9.12) e sembra funzionare. I driver trovati sono:
```
0: "com.mysql.cj.jdbc.Driver"
1: "com.mysql.cj.jdbc.NonRegisteringDriver"
2: "org.apache.tomcat.dbcp.dbcp2.PoolingDriver"
3: "org.h2.Driver"
4: "com.mysql.jdbc.Driver"
5: "org.postgresql.Driver"
```

**Comment by giacomoronconiobda** [comment]
La soluzione trovata è questa:

- Sono stati rimossi mysql e postgres dal pom di Mastro
- Per continuare a usare i driver jdbc quando si lancia mws in debug in eclipse o intellij sul server bisogna aggiungerli nel classpath di tomcat
- C'è un nuovo build (0.2.4) con il quale è possibile aggiungere/modificare i driver jdbc (c'è una cartella apposita in cui si possono mettere i jar e modificare il file `drivers` aggiungendo opportunamente le classi dei driver che si vogliono usare

@roodsey
