### ISSUE TITLE
Problema scaricamento dell'ontologia approssimata Books

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#227]
Allora, ho approfondito la questione, e credo di aver capito qual'è il problema.
Nell'importazione di una ontologia dal file Graphol, c'è un errore nel gestire le IRI che terminano con il # (ovvero tutte quelle di default in pratica).
Il cancelletto infatti viene rimosso dalla IRI (vedere screenshot sotto per confronto tra OWL esportato da Eddy, con i cancelletti, e OWL esportato da Monolith, senza i cancelletti).

<img width="1100" alt="Schermata 2020-02-01 alle 11 24 20" src="https://user-images.githubusercontent.com/8250758/73590688-91a60e80-44e5-11ea-8ca6-8579d406d0f5.png">

Di conseguenza, vengono generati assiomi di questo tipo:
DataPropertyRange(:name <http://www.w3.org/2001/XMLSchemastring>)
che sono errati, e che quindi Hermit non riesce a gestire in fase di approssimazione.

Non mi è ancora del tutto chiaro per quale motivo Mastro riesca ad avviarsi senza riscontrare questo problema, ma sicuramente l'errore di Hermit in fase di scaricamento della versione approssimata dell'ontologia dipende da questo.

**Comment by valeriosantarelli** [comment]
@NonnonePalmiro ho riscontrato questo problema (credo) nel parser Graphol-OWL che sta dentro Mastro, potresti verificare?

**Comment by NonnonePalmiro** [comment]
@valeriosantarelli Se domani sei in dipartimento mi spieghi bene, perchè sinceramente non ho capito bene nè quale sia la problematica segnalata sul ticket, nè a quale parser tu stia facendo riferimento

**Comment by valeriosantarelli** [comment]
> @valeriosantarelli Se domani sei in dipartimento mi spieghi bene, perchè sinceramente non ho capito bene nè quale sia la problematica segnalata sul ticket, nè a quale parser tu stia facendo riferimento

Ne riparliamo lunedì, domani non credo di esserci causa influenza.

**Comment by NonnonePalmiro** [comment]
@valeriosantarelli Penso di aver capito a cosa facciate riferimento. Domani do un'occhiata e vedo se riesco a risolvere

**Comment by NonnonePalmiro** [comment]
Ho verificato il comportamento del parser che avevo scritto io, it.uniroma1.dis.mastro.parserit.uniroma1.dis.mastro.parser.GraphOLParser,  dando in input il file 
[books.graphol.txt](https://github.com/obdasystems/monolith/files/4165411/books.graphol.txt)
 dentro Mastro ed ho ottenuto l'ontologia 
[ontology.owl.txt](https://github.com/obdasystems/monolith/files/4165407/ontology.owl.txt) che mi sembra essere corretta. Dunque non credo che il problema segnalato sia da attribuire al parser in questione.

**Comment by valeriosantarelli** [comment]
Si, sembra corretto anche a me.

@giacomoronconiobda riusciamo ad isolare il processo che genera l'ontologia OWL che viene scaricata? Perché noto delle cose un pò strane:
- se scarico il file in Functional Syntax, gestisce in modo scorretto i datatypes:
Prefix(:=<http://www.obdasystems.com/books/>)
Prefix(owl:=<http://www.w3.org/2002/07/owl>)
Prefix(rdf:=<http://www.w3.org/1999/02/22-rdf-syntax-ns>)
Prefix(xml:=<http://www.w3.org/XML/1998/namespace>)
**Prefix(xsd:=<http://www.w3.org/2001/XMLSchema>)**
**Prefix(rdfs:=<http://www.w3.org/2000/01/rdf-schema>)**

**Declaration(Datatype(<http://www.w3.org/2000/01/rdf-schemaLiteral>))
Declaration(Datatype(<http://www.w3.org/2001/XMLSchemastring>))**
 
- se scarico il file in Turtle o RDF/XML, la definizione dei prefissi mi sembra corretta, ma avviene comunque quella dichiarazione strana:
RDF xmlns="http://www.obdasystems.com/books/"
     xml:base="http://www.obdasystems.com/books/"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     **xmlns:xsd="http://www.w3.org/2001/XMLSchema#"**
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">
    <owl:Ontology rdf:about="http://www.obdasystems.com/books/">
        <owl:versionIRI rdf:resource="1.0"/>
    </owl:Ontology>

    // Datatypes
   <rdfs:Datatype rdf:about="http://www.w3.org/2000/01/rdf-schemaLiteral"/>
    <rdfs:Datatype rdf:about="http://www.w3.org/2001/XMLSchemastring"/>

**Comment by valeriosantarelli** [comment]
@NonnonePalmiro abbiamo scoperto qual'era il problema: originariamente Eddy non salvava i cancelletti dentro le IRI Standard. Credo che Manuel abbia fixato la cosa. Tanto è vero che se apro una ontologia vecchia in Eddy (senza i cancelletti) e la salvo, lui ce li mette.
In sostanza, era tutta colpa di Aswhin.
