### ISSUE TITLE
Query report

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#228]
Ci sono un paio di cose che mi sembra non vadano nella sezione del Query Report dell'Endpoint SPARQL.

I seguenti fenomeni li ho riscontrati facendo girare una query che impiega un pò di tempo, tipo 5 minuti, non so se questo possa essere un motivo di errore.

- Gli SQL Rewritings non vengono visualizzati se non al termine della query, nonostante siano stati prodotti dopo pochi secondi di esecuzione
- Nel primo pannello, Query Info, non vengono registrate le query Optimized
<img width="258" alt="Schermata 2020-02-05 alle 16 18 23" src="https://user-images.githubusercontent.com/8250758/73854742-41a3b080-4833-11ea-88fc-352d582d06e4.png">

Infine, il pulsante "Download Query Report" non fa nulla (forse non è proprio implementato?)

**Comment by giacomoronconiobda** [comment]
Query Optimized registrate, manca da risolvere la questione dei rewritings che arrivano vuoti fincheè la query non finisce. #giro @roodsey

**Comment by roodsey** [comment]
@valeriosantarelli allegare query er specifica

**Comment by valeriosantarelli** [comment]
La query è la seguente:
[query.txt](https://github.com/obdasystems/monolith/files/4212803/query.txt)

La specifica è movieontology, ti posso allegare l'ontologia e i mapping, ma il database va tirato su, sono diversi giga. Vi ho girato il link alla cartella su drive dove sta, vedete se riuscite a scaricarlo, in caso contrario dovete chiedere a Manuel che è il proprietario della cartella.

[movie_mappings.xml.zip](https://github.com/obdasystems/monolith/files/4212828/movie_mappings.xml.zip)
[movieontology.owl.zip](https://github.com/obdasystems/monolith/files/4212832/movieontology.owl.zip)

**Comment by roodsey** [comment]
Come lo screenshot mostra (esecuzione della classe com.mwsx.unit.JerseyAPIsTestQueryReport.java) le riscritture vengono rilevate istantaneamente: la tripla di valori contiene numero di risposte, numero di riscritture, tempo trascorso rispettivamente.

![image](https://user-images.githubusercontent.com/20337479/77224558-444e3100-6b67-11ea-88b8-4264b54687df.png)

Resta da verificare se il pannello del query report viene opportunamente aggiornato in polling.

**Comment by giacomoronconiobda** [comment]
Come mostra il seguente screencast:
[Screencast from 23-03-2020 11:00:09.zip](https://github.com/obdasystems/monolith/files/4368409/Screencast.from.23-03-2020.11.00.09.zip)
Il polling viene eseguito correttamente ma l'oggetto EndpointStatus restituito dalle chiamate ha sempre la seguente struttura quando in stato RUNNING:

```
{
status: "RUNNING"
percentage: 99
numOntologyRewritings: 1
numHighLevelQueries: 2
numOptimizedQueries: 1
numLowLevelQueries: 0
executionTime: -1
numResults: 0
hasError: false
}
```

**Comment by roodsey** [comment]
Sul pulsante "Download query report" coinvolgo @giacomoronconiobda : in generale mettiamo controlli nell'interfaccia solo quando sono implementati.
Creo ragionevolmente che lo scaricamento del query report possa essere demandato ad una milestone successiva (@valeriosantarelli )

**Comment by valeriosantarelli** [comment]
Si, assolutamente, sposto alla 0.3.0 creando una issue dedicata, per adesso togliamo il pulsante e basta.

**Comment by giacomoronconiobda** [comment]
Non ho capito: devo togliere il pulsante in generale i c'è qualche rotta disponibile in tal senso?

**Comment by valeriosantarelli** [comment]
Credo che non ci siano rotte disponibili al momento, verranno generate per il rilascio 0.3.0, quindi per il momento si può togliere il pulsante.
