### ISSUE TITLE
Test SQL View

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#231]
Non so se il meccanismo di test della query SQL in una View è implementato o meno.

Se si, sto riscontrando un comportamento errato, come si evince dallo screenshot sotto.

La tabella interrogata è in realtà vuota, ma i risultati mostrati sono errati sia nei dati che nei campi.

<img width="950" alt="Schermata 2020-02-16 alle 11 19 52" src="https://user-images.githubusercontent.com/8250758/74602976-9efaf580-50ae-11ea-8aaf-e2b25c1665e3.png">

**Comment by roodsey** [comment]
Mi pare si tratti di un risultato stubbato #giroaronconi
