### ISSUE TITLE
Mapping Manager nel Cache Manager

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#235]
Il Mapping Manager viene messo dentro il Cache Manager ma non viene aggiornato.
Il fenomeno che ho riscontrato è che se provo a creare una SQL View identica due volte, il sistema dà giustamente errore perchè riconosce che l'ID è ripetuto.
Se però poi riprovo a caricare il file di mapping avendolo corretto, continua a dare lo stesso errore.

Per risolvere si deve cambiare ID del mapping.

**Comment by roodsey** [comment]
Verificare e in caso di funzionamento chiudere.

**Comment by valeriosantarelli** [comment]
Chiudo per ora, se vengono fuori problemi riapriamo.
