### ISSUE TITLE
Clear All messaggi di errore

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#236]
Sarebbe molto utile avere un pulsante di Clear All che fa sparire tutti i messaggi di errore (nel caso ce ne sono molti).

**Comment by giacomoronconiobda** [comment]
Dove lo mettiamo questo pulsante?

**Comment by valeriosantarelli** [comment]
Diverse opzioni:
- su ogni messaggio di errore
- dentro un boxino sopra a tutti i messaggi di errore
- dentro un boxino sotto a tutti i messaggi di errore
- da qualche altra parte che al momento non mi sovviene
