### ISSUE TITLE
[Ontology - Endpoint] default query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#24]
Nella query di default dentro l’area di SPARQL, mettere solo i prefissi (la query che c’è adesso non viene gestita da Mastro), stando attenti a mettere tutti i prefissi dell'ontologia (attualmente non succede).

**Comment by giacomoronconiobda** [comment]
Mancano il servizio e le risorse per i prefissi

**Comment by roodsey** [comment]
Specificare PATH e verbo HTTP

**Comment by giacomoronconiobda** [comment]
Path:` /owlOntology/{name}/version/prefixes`
Method: `GET`
Params: `version={String}`
Response: `List<Prefix>`

`Prefix = {
    prefix: String,
    iri: String
}`

**Comment by roodsey** [comment]
Dando per scontato che si tratti dei prefissi contenuti nel file di mapping, ho cambiato la rotta in
`/owlOntology/{name}/version/mapping/{ID}/prefixes`
Inoltre, la dicitura prefix/iri non è adeguata: ho optato per name/namespace, così come avviene nel file XML dei mapping di Mastro.

Ad esempio in "rdf:type" avremo che "rdf:" è il nome, "http://www.w3c.org/rdf/" è il namespace.
