### ISSUE TITLE
Descrizione delle SQL Views

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#241]
Al momento non sono (credo) supportate.
Se aggiungo una descrizione ad una SQL View e salvo, poi non me la fa vedere.

Lo segno come bug ma probabilmente è una enhancement.

**Comment by roodsey** [comment]
Implementato il salvataggio delle descrizioni lato codice.
Rimane da verificare se i dati vengono passati e raccolti correttamente da Monolith.

**Comment by giacomoronconiobda** [comment]
Verificato, funziona tutto.
