### ISSUE TITLE
Nuova datasource

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#245]
Quando creo una nuova datasource, per visualizzare la card corrispondente nel Datasource catalogue, devo refreshare la pagina.

Volevo #girarearonconi ma @giacomoronconiobda mi ha detto di #girarearuzzi.
Lascio a @giacomoronconiobda la motivazione del perchè è un problema da #girarearuzzi.

**Comment by giacomoronconiobda** [comment]
Subito dopo la POST faccio una GET ma questa non restituisce la nuova datasource. Se la GET viene fatta dopo un po' la datasource compare. Penso sia un problema di sincronizzazione della POST (forse ritorna anche se non è stata ancora creata la risorsa)

**Comment by roodsey** [comment]
Devi assicurarti di fare la GET solo dopo che la POST è terminata, cosa che non credo riuscirà a garantirti nessuno, vista la natura asincrona di alcune chiamate HTTP. TI posso solo suggerire di metter una piccola pausa prima della GET. Per quanto mi riguarda la datasource viene creata correttamente.
