### ISSUE TITLE
Datasource dei default per un mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#246]
Sarebbe comunque comodo poter assegnare una datasource "di default" per un mapping.
Questo non significa blindare un mapping ad una particolare datasource, ma quando ad esempio si stanno scrivendo le SQL Views, è scomodo dover ogni volta selezionare la datasource per poterle testare.
Può anche essere una informazione che viene persa al momento di fare il logout, non deve essere assolutamente persistente.

**Comment by roodsey** [comment]
Per quanto mi riguarda la questione deve essere gestita da Monolith: l'utente seleziona una datasource per creare una vista e la datasource selezionata rimane quella fino ad una nuova selezione. Non trattandosi di informazione persistente non deve essere gestita da MWS, ma viene di volta in volta passata da monolith durante le chiamate.

**Comment by valeriosantarelli** [comment]
> Per quanto mi riguarda la questione deve essere gestita da Monolith: l'utente seleziona una datasource per creare una vista e la datasource selezionata rimane quella fino ad una nuova selezione. Non trattandosi di informazione persistente non deve essere gestita da MWS, ma viene di volta in volta passata da monolith durante le chiamate.

Si, forse in effetti è meglio fare così piuttosto che assegnare il datasource di default al mapping: semplicemente rimane scelta quella selezionata per ultima.

**Comment by valeriosantarelli** [comment]
Sto riscontrando un errore.
Se definisco la datasource di default per un mapping, e poi provo a aggiungere una SQL View, ottengo questo errore:

index.js:1446 TypeError: Cannot read property 'name' of undefined
    at AddSQLView.js:55
    at Array.find (<anonymous>)
    at AddSQLView._this.loadedDatasources (AddSQLView.js:55)
    at MastroApi.js:1005

**Comment by valeriosantarelli** [comment]
Anzi, più in generale, una volta definito il datasource di default, non riesco ad aprire la pagina dei mapping. Mi dà questo errore:

let defaultDatasources = JSON.parse(localStorage.getItem('defaultDatasources')) || []
  81 | 
> 82 | let defaultDatasource = defaultDatasources.find(i => 
     | ^  83 |   i.ontology.name === this.props.match.params.ontologyName &&
  84 |   i.ontology.version === decodeURIComponent(this.props.match.params.ontologyVersion) &&
  85 |   i.mappingID === this.props.match.params.mappingID
