### ISSUE TITLE
Tab Templates

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#249]
Nella pagina dei mapping, aggiungere il tab Templates.

Strutturalmente sarebbe simile a quelli di SQL Views, quindi con un albero di templates.
Cliccando sull'albero, nella parte destra della pagina vengono mostrati (oltre al template), tutti i mapping che usano quel template.
Premendo sul pulsante Add Mappint (+) viene fuori la form di editing di un mapping, con il template già compilato.

Domanda: ha senso permettere di aggiungere un template direttamente da questa schermata, senza necessariamente usarlo in un mapping?

**Comment by giacomoronconiobda** [comment]
Si, i template vengono usati per gestire la ABOX del file OWL quindi potrebbe essere utile.

**Comment by giacomoronconiobda** [comment]
Manca la rotta per fare la POST di un template. Non penso abbia senso permettere la DELETE e la PUT perchè non si capisce bene quali siano le ripercussioni sui mapping.

**Comment by roodsey** [comment]
Aggiunta la rotta 
```
POST /owlOntology/{name}/version/mapping/{ID}/template
```
il nuovo template viene passato come stringa nel body della POST

**Comment by valeriosantarelli** [comment]
@giacomoronconiobda @roodsey Credo che la delete vada permessa, eventualmente inibendola per quei template che sono effettivamente utilizzati nei mapping.
Così com'è adesso, se mi sbaglio a definire un template (oppure se ne ho aggiunto uno solo per fare una prova) non posso cancellarlo.

Vi sembra ragionevole?

**Comment by giacomoronconiobda** [comment]
Forse se il template non è usato da nessun mapping si. Se invece viene usato non dovrebbe essere possibile secondo me

**Comment by roodsey** [comment]
Aggiunta rotta 
```
DELETE /owlOntology/{name}/version/mapping/{ID}/template
```
il vecchio template viene passato come parametro di query (il body nelle DELETE non dovrebbe mai esserci, in accordo al paradigma REST)
