### ISSUE TITLE
Mapping Templates per mapping creato da zero

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#252]
Per il mapping in allegato (lo stesso che genera l'errore riportato qui #232 ), non viene mostrato nella pagina Mapping Info alcun template.
La cosa non si verifica per un mapping caricato già completo invece.

[ISTAT.mappings.zip](https://github.com/obdasystems/monolith/files/4239825/ISTAT.mappings.zip)

**Comment by valeriosantarelli** [comment]
Problema analogo nel tab Templates dell'Help del Mapping Editor. I template ci sono nel mapping, ma non vengono visualizzati.

![Schermata 2020-02-25 alle 15 36 05](https://user-images.githubusercontent.com/8250758/75257013-a58f1880-57e4-11ea-90c9-a0d099f7ab9c.png)

**Comment by giacomoronconiobda** [comment]
Non riscontrato dopo la risoluzione della #232

**Comment by valeriosantarelli** [comment]
Riapro, il problema si presenta ancora (non so se era sparito e ora è ricomparso, oppure c'è sempre stato).

Allego specifica per riprodurre l'errore.

[ONTO_n1110864384.zip](https://github.com/obdasystems/monolith/files/4476406/ONTO_n1110864384.zip)

**Comment by giacomoronconiobda** [comment]
Se provi a riavviare tomcat si vedono? Penso sia un problema di cache dell'oggetto MappingInfo

**Comment by valeriosantarelli** [comment]
No...ho riavviato, e non si vedono (sempre provato su wolf).

**Comment by giacomoronconiobda** [comment]
L'array dei template della rotta 
```
 '/owlOntology/' + name + '/version/mapping/' + mapping + '/info'
```
è vuoto, coinvolgo @roodsey
