### ISSUE TITLE
Template associati a Ontology entities

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#256]
Sarebbe molto utile nel Mapping Editor visualizzare i template, invece che (oppure in aggiunta a) una lista piatta di template, distribuiti per Ontology entity nel cui mapping sono utilizzati.

In poche parole, è più utile se si sta facendo un mapping di un certo concetto, sapere qual'è il template associato ad esempio al suo concetto padre, oppure nel caso di un ruolo, quali sono i template associati al dominio e range del ruolo stesso.

Ovviamente il sistema non deve ragionare sull'ontologia per ricavare questi template, basterebbe il solito albero di classi, obj prop e data prop, che cliccando su una entity, vengono fuori i template (eventualmente prevedendo anche una opzione "all").

**Comment by roodsey** [comment]
Ho bisogno che @giacomoronconiobda delinei le rotte necessarie

**Comment by giacomoronconiobda** [comment]
Penso si possa usare la rotta che già c'è: 
```
"/owlOntology/{name}/version/mapping/{ID}/assertions/{entityID}"
```
