### ISSUE TITLE
Creazione dei path e delle risorse per la gestione delle dependencies

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#259]
Il tentativo di generare una Key ha prodotto l'errore riportato sotto.

Allego ontologia e mapping, la vista su cui ho tentato di creare la key è "Tipi_relazione_view".

[Archivio.zip](https://github.com/obdasystems/monolith/files/4250604/Archivio.zip)

EDIT: al momento di testare la issue non erano ancora state create le rotte per la generazione di Keys, quindi è un enhancement da implementare.

**Comment by giacomoronconiobda** [comment]
Non capisco cosa tu intenda. Le risorse per creare le key ancora non esistono. La traccia è la stessa della #263 quindi non c'entra niente. Più che bug è un enhancement per le rotte delle dependencies.

**Comment by valeriosantarelli** [comment]
Ok, potrei aver incollato la traccia sbagliata per errore. Modifico la issue.
