### ISSUE TITLE
[Ontology - Endpoint] Costruct Query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#26]
Al momento è garantito il supporto alle query con la CONSTRUCT?

**Comment by giacomoronconiobda** [comment]
:no_good_man:

**Comment by valeriosantarelli** [comment]
Ehm...ok. Che passi bisogna fare per supportarle?

**Comment by roodsey** [comment]
Al momento non c'è supporto per la CONSTRUCT

**Comment by valeriosantarelli** [comment]
Ok, chiudiamo questo milestone senza supporto alla Construct.
Nel prossimo dovremo prevedere di aggiungerlo.
