### ISSUE TITLE
Implementare creazione Inclusion

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#261]
Il tasto di salvataggio di una nuova Inclusion Dependency non fa nulla.
Assumo che non sia stato ancora implementato, ma apro la issue lo stesso per tenerne traccia (così poi aggiungo alla documentazione).

Nell'implementarlo, ricordiamoci di verificare che le due viste scelte (Included e Including) non siano la stessa).

**Comment by giacomoronconiobda** [comment]
Mancano da definire oggetti e rotte

**Comment by giacomoronconiobda** [comment]
Duplicato #259
