### ISSUE TITLE
Condizione nella where interpretata come Join

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#262]
La query SQL nell'Ontology Mapping nello screenshot viene interpretata come errata dal parser.
In pratica pensa che sto provando a fare un join implicito nella where, quando invece sto cercando di imporre l'uguaglianza tra due campi nella stessa tabella.

<img width="825" alt="Schermata 2020-02-26 alle 10 11 45" src="https://user-images.githubusercontent.com/8250758/75330011-eb99ba00-5880-11ea-8e21-6bebbbcc434e.png">

Non so se l'imposizione di fare solo join espliciti sia una strada percorribile.
In questo caso il problema è più facile da individuare perchè è sulla stessa tabella, ma credo si potrebbe riproporre anche su più tabelle.

**Comment by valeriosantarelli** [comment]
Everything seems fucked nella where :)

<img width="447" alt="Schermata 2020-03-02 alle 16 57 06" src="https://user-images.githubusercontent.com/8250758/75693250-f7cdaf00-5ca6-11ea-8aa5-b4e5efa8bbea.png">
<img width="691" alt="Schermata 2020-03-02 alle 16 57 27" src="https://user-images.githubusercontent.com/8250758/75693254-f8fedc00-5ca6-11ea-93a1-ba771d3b7702.png">

**Comment by giacomoronconiobda** [comment]
Allega il file di mapping please

Il lun 2 mar 2020 16:58 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
[ISTAT.mappings.zip](https://github.com/obdasystems/monolith/files/4276889/ISTAT.mappings.zip)

Eccolo: cerca il mapping per Persona_nata_morta

**Comment by giacomoronconiobda** [comment]
Anche l'ontologia pera favore

Il lun 2 mar 2020 18:28 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
[ISTAT.owl.zip](https://github.com/obdasystems/monolith/files/4276964/ISTAT.owl.zip)
Tiè
