### ISSUE TITLE
PUT mapping assertion non modifica la mapping assertion by entity

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#265]
Errore forse analogo a quanto segnalato nella issue #263 

Ho un errore anche quando provo a generare il seguente mapping:

>         <ontologyPredicateComplexMapping id="M27_persona_maggiorenne">
            <concept string="http://www.datiopen.istat.it#Persona_maggiorenne">
                <template>http://www.datiopen.istat.it#persona-{cod_individuo}</template>
            </concept>
            <viewAtomsConjunction>
                <viewAtom>GREATER_EQUAL_THAN(eta,'18'^^xsd:integer)</viewAtom>
                <viewAtom>IS_NULL(eta_decesso)</viewAtom>
                <viewAtom>persona_view(cod_individuo,data_nascita,data_morte,cod_famiglia,cod_grado_istruzione,comune_nascita,nazione_nascita,genere,genere_nascita,intestatario_foglio_famiglia,cod_com_residenza_attuale,data_inizio_val_res_attuale,apolide,eta,eta_decesso,cod_prov_nascita,cod_prov_res_attuale)</viewAtom>
            </viewAtomsConjunction>
        </ontologyPredicateComplexMapping>

<img width="1068" alt="Schermata 2020-02-26 alle 11 33 47" src="https://user-images.githubusercontent.com/8250758/75336741-f60d8100-588b-11ea-94ea-6af1d3b13050.png">

**Comment by giacomoronconiobda** [comment]
Non riesco a riprodurre l'errore

**Comment by valeriosantarelli** [comment]
Sei riuscito a ricreare esattamente in mapping indicato nella issue senza problemi? In caso, mi allegheresti il file di mapping generato?

**Comment by giacomoronconiobda** [comment]
[ISTAT.mappings.zip](https://github.com/obdasystems/monolith/files/4275484/ISTAT.mappings.zip)

**Comment by valeriosantarelli** [comment]
Non so se è un problema solo mio, ma quando cerco di definire un maggiore uguale, mi prende solo il maggiore.

![Schermata 2020-03-04 alle 16 53 20](https://user-images.githubusercontent.com/8250758/75897332-b240eb80-5e38-11ea-9589-0047661d388a.png)
![Schermata 2020-03-04 alle 16 53 26](https://user-images.githubusercontent.com/8250758/75897340-b3721880-5e38-11ea-9851-a20cce17aba9.png)

**Comment by giacomoronconiobda** [comment]
Sei sicuro che c'è ancora questo problema? penso sia legato alla issue che ha chiuso oggi marco. Io non ho questo problema
![Screenshot from 2020-03-04 23-15-19](https://user-images.githubusercontent.com/36189778/75928154-1631d700-5e6e-11ea-9f0d-5c7a31219972.png)

**Comment by giacomoronconiobda** [comment]
Ah no aspe, penso che il problema ci sia ancora nell'update di un mapping (PUT) per vedere i risultati della modifica bisogna riavviare il server

**Comment by roodsey** [comment]
Il modo con cui scrivete e commentate le issue è da denuncia. 
Per quello che sono riuscito a comprendere (a fatica) posso solo dire lato servizi l'aggiornamento avviene in modo corretto: test eseguito in TestBooksQueryJerseyClient.mappingUpdate();

**Comment by giacomoronconiobda** [comment]
Forse ti sei scordato di commitarlo il test, non c'è nella classe che hai
detto. Sei sicuro che le chiamate utilizzate nel test sia quella utilizzata
da Monolith (getMappingByEntityID)?

Il giorno gio 5 mar 2020 alle ore 16:29 Marco Ruzzi <
notifications@github.com> ha scritto:

**Comment by roodsey** [comment]
Committato

**Comment by giacomoronconiobda** [comment]
Marco ho fatto girare il tuo test e ho riscontrato l'errore anche li. Ho notato che però tu stampavi solo l'oggetto che usavi per fare la PUT ma non gli oggetti ritornati dalla successiva GET. 
```PUT:
{
  "currentEntity" : {
    "entityIRI" : "http://www.obdasystems.com/books/E_Book",
    "entityID" : "CL_1",
    "entityPrefixIRI" : ":E_Book",
    "entityRemainder" : "E_Book",
    "entityLabels" : [ ],
    "entityType" : "CLASS"
  },
  "iri" : {
    "shortIRI" : "ma:M_NEW_01",
    "extendedIRI" : "http://mass/M_NEW_01"
  },
  "mappingDescription" : "mapingdexcription the new description",
  "id" : "M_NEW_01",
  "mappingBody" : {
    "viewAtoms" : [ {
      "name" : "THE_VAISTA",
      "terms" : [ "a" ],
      "view" : {
        "sqlViewHead" : [ "a" ],
        "sqlViewID" : "THE_VAISTA",
        "sqlViewDescription" : "the description of view",
        "sqlViewCode" : "SELECT 1 as a"
      }
    }, {
      "name" : "THE_VAISTA_BIS",
      "terms" : [ "a", "b" ],
      "view" : {
        "sqlViewHead" : [ "a", "b" ],
        "sqlViewID" : "THE_VAISTA_BIS",
        "sqlViewDescription" : "the description of view",
        "sqlViewCode" : "SELECT 1 as a, 2 as b"
      }
    } ],
    "bip" : null
  },
  "template" : {
    "template" : "http://lillo/{a}/{b}",
    "terms" : [ "a", "b" ]
  },
  "rangeTemplate" : null
}Mar 06, 2020 10:15:53 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 14 * Sending client request on thread main
14 > GET http://localhost:8989/mws/rest/mwsx/owlOntology/ONTO_n989298058/version/mapping/books_mappings/assertions/CL_1?version=http%3A%2F%2Fwww.obdasystems.com%2Fbooks%2F1.0
14 > Accept: application/json
14 > X-MONOLITH-SESSION-ID: 704cee34-c5d4-4242-afb4-2e3515a0add5

Mar 06, 2020 10:15:53 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 14 * Client response received on thread main
14 < 200
14 < Access-Control-Allow-Credentials: true
14 < Access-Control-Allow-Headers: origin, access-control-allow-origin, content-type, accept, authorization, x-requested-with,X-MONOLITH-SESSION-ID
14 < Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
14 < Access-Control-Allow-Origin: *
14 < Access-Control-Expose-Headers: X-MONOLITH-SESSION-ID
14 < Content-Length: 1423
14 < Content-Type: application/json
14 < Date: Fri, 06 Mar 2020 09:15:52 GMT

GET: 

{
  "currentEntity" : {
    "entityIRI" : "http://www.obdasystems.com/books/E_Book",
    "entityID" : "CL_1",
    "entityPrefixIRI" : ":E_Book",
    "entityRemainder" : "E_Book",
    "entityLabels" : [ ],
    "entityType" : "CLASS"
  },
  "iri" : {
    "shortIRI" : "obda:m_EBook_1",
    "extendedIRI" : "http://www.obdasystems.com/mappings/m_EBook_1"
  },
  "mappingDescription" : null,
  "id" : "m_EBook_1",
  "mappingBody" : {
    "viewAtoms" : [ {
      "name" : "book_view",
      "terms" : [ "code", "title", "type" ],
      "view" : {
        "sqlViewHead" : [ "code", "title", "type" ],
        "sqlViewID" : "book_view",
        "sqlViewDescription" : null,
        "sqlViewCode" : "SELECT bk_code as code, bk_title as title, bk_type as type\nFROM tb_books"
      }
    } ],
    "bip" : [ {
      "name" : "EQUALS",
      "terms" : [ "type", "'E'^^xsd:string" ],
      "view" : null
    } ]
  },
  "template" : {
    "template" : "http://www.obdasystems.com/books/book-{code}",
    "terms" : [ "code" ]
  },
  "rangeTemplate" : null
}
{
  "currentEntity" : {
    "entityIRI" : "http://www.obdasystems.com/books/E_Book",
    "entityID" : "CL_1",
    "entityPrefixIRI" : ":E_Book",
    "entityRemainder" : "E_Book",
    "entityLabels" : [ ],
    "entityType" : "CLASS"
  },
  "iri" : {
    "shortIRI" : "obda:M_NEW_01",
    "extendedIRI" : "http://www.obdasystems.com/mappings/M_NEW_01"
  },
  "mappingDescription" : "mapingdexcription the new description",
  "id" : "M_NEW_01",
  "mappingBody" : {
    "viewAtoms" : [ {
      "name" : "THE_VAISTA",
      "terms" : [ "a" ],
      "view" : {
        "sqlViewHead" : [ "a" ],
        "sqlViewID" : "THE_VAISTA",
        "sqlViewDescription" : "the description of view",
        "sqlViewCode" : "SELECT 1 as a"
      }
    } ],
    "bip" : [ ]
  },
  "template" : {
    "template" : "http://lillo/{a}",
    "terms" : [ "a" ]
  },
  "rangeTemplate" : null
}
```

**Comment by roodsey** [comment]
Prego verificare e chiudere in caso risultati positivi

**Comment by valeriosantarelli** [comment]
Allora, ho provato a modificare un mapping già esistente e a salvare, e ha funzionato.

Nello specifico, da questo:

SELECT book_view.code AS code 
FROM book_view 
WHERE book_view.type = 'E'

a questo:

SELECT book_view.code AS code 
FROM book_view 
WHERE book_view.type <> 'E'

e altre variazioni di questo genere. Quindi credo che si possa chiudere.
