### ISSUE TITLE
Visualizzazione delle Inclusions

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#266]
Credo che dovremmo trovare una soluzione diversa per la visualizzazione delle Inclusions.
La modalità a tabella con una riga per campo va bene in fase di editing, ma mi sembra assolutamente poco chiara poi per visualizzare le Inclusions.

Potrebbe essere dovuto ad una scelta di colori non ottimali, ma al momento non credo si capisca molto:
<img width="859" alt="Schermata 2020-02-26 alle 21 03 15" src="https://user-images.githubusercontent.com/8250758/75393737-030f8c00-58ef-11ea-9ecd-d4ab77c7947a.png">

Una idea potrebbe essere quella di far vedere una inclusione per riga, generando una tabella di questo tipo:

Included | Including
-- | --
V1(x1,x2,x3) | V2(y1,y3,y6)

con magari la possibilità di visualizzare le due Views (tipo col pulsante dell'occhio, come per le password).

**Comment by giacomoronconiobda** [comment]
Vorrei evitare di "parlare" datalog in monolith. Che cosa c'è di poco chiaro nella tabella? L'hover sulla vista per vedere l'SQL si puo comunque fare

**Comment by valeriosantarelli** [comment]
Forse come dicevo nel commento potrebbe essere un problema di layout.
Al momento non si capisce proprio che si sta vedendo una tabella, i confini della tabella non sono definiti, e il colore di sfondo delle righe è lo stesso del colore di sfondo del componente.

Comunque la notazione Tabella(colonna, colonna, colonna) non è necessariamente solo Datalog.

Ad esempio le foreign key, che sono simili strutturalmente alle inclusione, vengono mostrate così in Datagrip e Postgres:

<img width="702" alt="Schermata 2020-03-02 alle 15 46 38" src="https://user-images.githubusercontent.com/8250758/75689205-1466e880-5ca1-11ea-8c67-4e49cf096d6e.png">
<img width="590" alt="Schermata 2020-03-02 alle 16 07 16" src="https://user-images.githubusercontent.com/8250758/75689208-15981580-5ca1-11ea-880c-bdaa84289f68.png">
