### ISSUE TITLE
Cancellazione di un Mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#267]
Se si sta provando a cancellare un Ontology Mapping per una classe (da verificare se anche obj prop e data prop) che ha un figlio nell'ontologia, la cancellazione non sortisce alcun effetto.

Ad esempio, provare con il mapping della classe :Book nell'ontologia Books.

**Comment by giacomoronconiobda** [comment]
Sembra che il comportamento si riscontra con tutti i mapping che sono già nel file e non che vengono creati con l'editor. La chiamata viene fatta in maniera corretta lato Monolith, giro a @roodsey

**Comment by roodsey** [comment]
L'eliminazione funziona, non viene però ricaricato il file di mapping nuovo. Verrà risolta con il lavoro su #235
