### ISSUE TITLE
Invalidamento di Mappings e Constraints dopo eliminazione SQL View

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#268]
E' necessario gestire le conseguenze dell'eliminazione di una SQL View.

- Ontology Mappings non più validi
- Constraints non più validi

Questo deve essere gestito lato interfaccia evidenziando i mapping/constraints che non sono più validi, e lato server permettendo di salvare un mapping "mal formato", in modo da non generare errori alle successive riaperture.

Eventualmente si potrebbe anche pensare ad una opzione a scelta dell'utente sul comportamento da adottare: 

- ti faccio cancellare la view e ti mostro la roba non più valida (quindi da correggere)
- non ti faccio cancellare la view se coinvolta in altri mapping/constraints
- ti faccio cancellare la view, e faccio DROP CASCADE sui mapping/constraints (questa opzione deve essere premessa però da 100 warning perchè molto pericolosa)

**Comment by giacomoronconiobda** [comment]
Stavo pensando che la rimozione di una SQL view è un'operazione che si puo anche demandare a dopo che è stata rimossa da tutti i mapping. Quindi forse il primo bullet di valerio si può demandare a una futura versione. Quindi 2 sole opzioni (un po' come si comporta SQL):
1. drop cascade
2. do not drop

**Comment by giacomoronconiobda** [comment]
Il problema è un po' più complesso quando si tratta di modifica della segnatura della vista. Anche se penso che in una versione futura si possa fare un refactoring (come fa sql per i constraint)

**Comment by valeriosantarelli** [comment]
> Stavo pensando che la rimozione di una SQL view è un'operazione che si puo anche demandare a dopo che è stata rimossa da tutti i mapping. Quindi forse il primo bullet di valerio si può demandare a una futura versione. Quindi 2 sole opzioni (un po' come si comporta SQL):
> 
> 1. drop cascade
> 2. do not drop

Per me va bene prevedere queste due opzioni per ora.

**Comment by valeriosantarelli** [comment]
> Il problema è un po' più complesso quando si tratta di modifica della segnatura della vista. Anche se penso che in una versione futura si possa fare un refactoring (come fa sql per i constraint)

Questa funzione però temo sia indispensabile. In qualche modo bisogna permettere di farlo.

**Comment by giacomoronconiobda** [comment]
Penso che si possa chiudere questa
