### ISSUE TITLE
Download di query results: varie segnalazioni

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#271]
- [ ] individuare un metodo ragionevole di chiamare i file esportati con i risultati delle query. Al momento usa una stringa alfanumerica, che concatena al nome della query presa dal tab della query stessa (quindi anche tipo new_1):
`abilities_28280de4-e62f-4291-bb75-2ae678766a76.csv`
Forse si può semplicemente togliere la parte di codice e lasciare solo il nome del tab?
- [ ] bisognerebbe inibire la possibilità di fare il download dei risultati in caso di query ASK: non credo che scaricare un csv con scritto solo TRUE o FALSE sia molto utile

**Comment by roodsey** [comment]
**Primo punto**
Il nome "abilities_28280de4-e62f-4291-bb75-2ae678766a76.csv" è già un nome ragionevole. Contiene l'ID della query nel catalogo, più un codice relativo all'esecuzione della query. Faccio notare che tale codice è essenziale in quanto la query può essere modificata nell'editor e cambiata prima di essere valutata: tenere lo stesso ID per tutti gli esport potrebbe portare a perdere dati (sovrascrittura). In alternativa si può mostrare un dialogo per chiedere all'utente di specificare il nome del file. La rotta "/endpoint/{name}/query/{queryID}/exportFile" contiene il parametro di query (opzionale) "fileName" per passare tale valore a MWS.

**Secondo punto**
Da devolvere all'applicativo, anche se non ne vedo davvero il bisogno.

**Comment by valeriosantarelli** [comment]
Io forse preferirei un timestamp dell'esecuzione piuttosto che il codice dell'esecuzione.

Ad ogni modo se pensate che vada bene così lasciamolo così.

**Comment by roodsey** [comment]
Va bene, ho modificato il nome del file esportato utilizzando un timestamp "yyyyMMdd_hhmmss" timestamp. Continuerei comunque a permettere la possibilità di far scegliere all'utente il nome del file (che è la cosa che accade di solito, in modo da poter scegliere anche la posizione del file salvato)
