### ISSUE TITLE
Alias in mapping SQL su Edit

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#273]
Se si scegliere di editare un ontology mapping già definito, l'SQL Code viene ricaricato facendo vedere, ad esempio nella Where, invece dei valori dei campi, x1, x2, etc.

Questo ovviamente crea confusione, ed è anche sbagliato se si interpreta veramente la vista come SQL. Vedere screenshot sotto (la vista persona_view ovviamente non ha un campo "x7").

Bisognerebbe trovare il modo di far rivedere il campo con il nome che ha nella view.

<img width="797" alt="Schermata 2020-03-02 alle 16 50 43" src="https://user-images.githubusercontent.com/8250758/75692759-4a5a9b80-5ca6-11ea-9fe1-6979cdc994be.png">

**Comment by giacomoronconiobda** [comment]
Sarebbe comodo in casi come questo avere anche gli oggetti json che passa
mastro. Si possono prendere dal pannello network del browser

Il lun 2 mar 2020 16:54 Valerio Santarelli <notifications@github.com> ha
scritto:
