### ISSUE TITLE
Tab SQL View Constraints

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#274]
Dobbiamo trovare una organizzazione diversa per mostrare i vincoli.
Secondo ma la visualizzazione dei singoli vincoli va bene, è che le pagine a questo punto sono praticamente vuote.
O cliccando succede qualcosa che riempie la pagina, oppure mettiamo tutto in un'unica schermata, oppure qualcos'altro, non so....

Al momento non ho una proposta pronta, sono solo riuscito ad identificare il problema :)

![Schermata 2020-03-04 alle 16 48 11](https://user-images.githubusercontent.com/8250758/75896916-0ac3b900-5e38-11ea-89c7-4d0aa7ab205f.png)
![Schermata 2020-03-04 alle 16 48 17](https://user-images.githubusercontent.com/8250758/75896919-0bf4e600-5e38-11ea-83ea-11deba5306ca.png)

**Comment by giacomoronconiobda** [comment]
Prova ad aprire le inclusion di Aci la pagina sarà pure troppo fitta

Il mer 4 mar 2020 16:50 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Mi allegheresti owl (o graphol) e mappings ACI? Non mi ritrovo più i mapping che fanno scopa con il graphol che ho io.

Anzi, sarebbe da metterli proprio su github in un progetto dedicato privato.

**Comment by giacomoronconiobda** [comment]
[aciobda.zip](https://github.com/obdasystems/monolith/files/4289885/aciobda.zip)

**Comment by valeriosantarelli** [comment]
Ah ok ahahah ho capito che intendi.
In effetti vista così il problema non si pone (sempre meglio fare i test con specifiche serie!).

A questo punto forse si potrebbe giusto rendere la pagina un pochino più interattiva, mettendo, sia per Inclusions che per Keys:
- il nome della vista cliccabile, che riporta alla pagina della vista stessa
- la vista che viene fuori in hover sul nome della stessa

In pratica lo stesso identico comportamento che c'è dentro gli Ontology Mappings
