### ISSUE TITLE
[Ontology - Endpoint] Query Catalog

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#28]
- [x] Se il nome della query è molto lunga crea problemi sia nel catalogo che come titolo del tab: fissare una lunghezza massima oppure troncare con i puntini alla fine

- [ ] Quando si salva una query nel catalogo, bisognerebbe essere reindirizzato di nuovo sul tab della query che è appena stata salvata

- [x] Bug: il sistema va in errore se si sceglie come ID uno già esistente. Bisogna inserire un meccanismo di verifica.

**Comment by giacomoronconiobda** [comment]
Non riesco a capire la 2: quando salvo il tab viene rinominato con il nome salvato...

**Comment by valeriosantarelli** [comment]
Si, ora sto avendo anche io il comportamento corretto. Ieri quando l'ho provato a fare in pratica salvava correttamente, ma riportava sul primo tab. Per il momento ok allora

**Comment by giacomoronconiobda** [comment]
Quanto mi piacciono i bug non deterministici, soprattutto quando non si riescono a riprodurre :sunglasses:

**Comment by valeriosantarelli** [comment]
Il comportamento della issue 2 è il seguente: quando viene salvata la query nel catalogo, viene riaperto anche un nuovo tab con l'ultima query aperta dal catalogo

**Comment by valeriosantarelli** [comment]
@roodsey Riguardo la issue 3: ora il sistema chiede se si vuole sovrascrivere la query esistente nel catalogo (correttamente). Se la risposta è si, la query vecchia però non viene sovrascritta.

**Comment by roodsey** [comment]
I metodi del catalogo sono stati collaudati e risultano tutti funzionanti, compreso l'aggiornamento di una query: il problema risiede lato interfaccia., Assegno la issue a @giacomoronconiobda
