### ISSUE TITLE
[Ontology - Endpoint] Query Report

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#29]
- [x] Il count dei risultati nel View Rewritings tab (quello che esce nel pop-up) non funziona. Restituisce sempre 0.

- [x] C’è uno strano effetti di salto nella pagina quando si passa da un tab all’altro (se i tab sono popolati).

- [x] Scrivere Download Query Report sul pulsante, perché credo che solo con Download non si capisca molto bene, ci si aspetta di scaricare i risultati della query

- [x] Usare la dicitura "View Rewriting" invece di "Mapping Rewriting" e "SQL Rewriting" invece di "View Rewriting"

**Comment by valeriosantarelli** [comment]
Punto #2 OK
Punto #3 OK, ma sposterei il pulsante fuori dalla tabella (direi sotto). Così è un pò strano perchè si vede solo nel primo tab il pulsante.
Punto #5 OK

**Comment by valeriosantarelli** [comment]
Punto 1 OK
Punto 2 OK
Punto 3 OK
Punto 5 OK

**Comment by roodsey** [comment]
Sul plugin di protege come li stiamo visualizzando? SQL? In caso contrario, manca la funzionalità lato mastro.

**Comment by valeriosantarelli** [comment]
No, sempre join tra viste/built-in predicates.
Se bisogna implementare una nuova funzionalità non consideriamola a priorità alta, non è sicuramente una cosa cruciale.

<img width="719" alt="Schermata 2019-04-12 alle 15 06 41" src="https://user-images.githubusercontent.com/8250758/56039475-a9cd5700-5d34-11e9-947a-5ae90bbb0c21.png">

**Comment by roodsey** [comment]
Ok, melgio spostarla alla prossima milestone... ci pensate voi?

**Comment by valeriosantarelli** [comment]
Si, ci penso io.
