### ISSUE TITLE
Problemi CSS dopo aggiornamento ANTD 4 (2)

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#293]
- Form del login

<img width="969" alt="Schermata 2020-03-10 alle 16 16 05" src="https://user-images.githubusercontent.com/8250758/76327673-9206a600-62ea-11ea-8811-fa49e626d27a.png">

==============================
Nuove segnalazioni

- Riga bianca sui tab (si può togliere direttamente)
<img width="606" alt="Schermata 2020-03-10 alle 17 52 48" src="https://user-images.githubusercontent.com/8250758/76337781-2297b300-62f8-11ea-9d71-a891ede1b235.png">

<img width="689" alt="Schermata 2020-03-10 alle 17 51 51" src="https://user-images.githubusercontent.com/8250758/76337887-49ee8000-62f8-11ea-8588-d1424baaf04f.png">

- barra di scroll verticale su SQL Views dentro Menu Help (va un pochino dentro l'area di testo)
<img width="522" alt="Schermata 2020-03-10 alle 17 52 10" src="https://user-images.githubusercontent.com/8250758/76337839-36dbb000-62f8-11ea-90fa-be3cdb05f5d2.png">

- pulsanti Help e Cancel appiccicati
<img width="689" alt="Schermata 2020-03-10 alle 17 51 51" src="https://user-images.githubusercontent.com/8250758/76337879-4529cc00-62f8-11ea-8b3a-adb631bb3cd1.png">

**Comment by giacomoronconiobda** [comment]
Il colore che vedi è di default del browser per le form autocompilate. Non
penso posso farci niente...

Il giorno mar 10 mar 2020 alle ore 16:17 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by valeriosantarelli** [comment]
Ammazza che brutto....
Prima dell'aggiornamento però non era così. Vabbè se si può intervenire bene, altrimenti pazienza

**Comment by valeriosantarelli** [comment]
Modifico la issue per segnalare un altro paio di cosette.

**Comment by giacomoronconiobda** [comment]
Quello che possiamo fare è togliere l'autocomplete del browser, che in effetti non mi piace molto

**Comment by giacomoronconiobda** [comment]
Ho trovato un temporary workaround
