### ISSUE TITLE
Ontologia mancante

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#294]
Per motivi che non mi sono per niente chiari, una delle ontologie su cui stavo facendo i test di Monolith (ISTAT in particolare) non viene visualizzata.

Se vedete lo screenshot sotto, noterete che nella mastro home ci sono 5 ontologie, ma solo 4 vengono mostrate nel catalogo di ontologie di Monolith. Quella evidenziata è quella mancante.
Vi allego tutta la mia mastro_home, non sapendo che altro tipo di supporto poter dare, dato che non registro messaggi di errore nè dalla console del browser nè da Tomcat.

<img width="1385" alt="Schermata 2020-03-10 alle 17 08 30" src="https://user-images.githubusercontent.com/8250758/76335364-b2d3f900-62f4-11ea-9390-7733489bf567.png">

[mastro-home.zip](https://github.com/obdasystems/monolith/files/4313550/mastro-home.zip)

**Comment by roodsey** [comment]
Se ti fosse possibile mi puoi zippare la mastro-home e inviarmela? Thanks

**Comment by valeriosantarelli** [comment]
E' in allegato alla issue. Sono sempre un passo avanti.

**Comment by roodsey** [comment]
il problema è dovuto ad un errore di codifica di un carattere dell'ontologia ISTAT: ho notato che nel repository c'è il file Graphol, me lo puoi allegare alla issue? (voglio usare proprio il tuo e non quello caricato nel repository)

**Comment by valeriosantarelli** [comment]
[POC1-Final.graphol.zip](https://github.com/obdasystems/monolith/files/4314043/POC1-Final.graphol.zip)

Eccolo. La cosa strana è che è scomparsa all'improvviso, come se l'errore fosse stato generato lavorando sui mapping, l'ontologia è sempre la stessa, e ci ho lavorato per diversi giorni dentro Monolith.

**Comment by giacomoronconiobda** [comment]
Ho riscontrato un problema simile anche io anche con altre ontologie. Non
penso dipenda dalla specifica.

Il mar 10 mar 2020 19:16 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Ma dopo le ultime modifiche quindi? Così almeno proviamo a circoscrivere il problema...

**Comment by giacomoronconiobda** [comment]
La prima volta mi è successo la settimana scorsa (ancora non c'era
emergenza corona virus, quindi non è un problema di ontologie immuno
depresse)

Il giorno mer 11 mar 2020 alle ore 08:40 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by valeriosantarelli** [comment]
Ok. Cerchiamo però di segnalarle queste cose sennò rischiamo di portarcele appresso per mesi, o peggio ancora, rilasciare lo strumento con un bug potenzialmente devastante come questo.

**Comment by giacomoronconiobda** [comment]
L'avevo già segnalato al CTO direttamente che mi era accanto quando è
successo. Pensavamo fosse un problema mio non un bug.

Il giorno mer 11 mar 2020 alle ore 10:47 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by valeriosantarelli** [comment]
Ah. What we have here is failure to communicate...

**Comment by roodsey** [comment]
L'errore deriva dalla presenza di un file ".DS_Store" nella cartella "ISTAT", indice di intervento manuale con Finder nella cartella repository (cosa che va evitata, piuttosto utilizziamo il Terminal, che non lascia tali file in giro).

NB le segnalazioni fatte a voce finiscono nel dimenticatoio prim ancora che si finsca di riferirle

**Comment by roodsey** [comment]
Se fate update, l'ontologia ISTAT comparirà

**Comment by roodsey** [comment]
Verificate e in caso di risoluzione chiudete la issue voi

**Comment by valeriosantarelli** [comment]
> L'errore deriva dalla presenza di un file ".DS_Store" nella cartella "ISTAT", indice di intervento manuale con Finder nella cartella repository (cosa che va evitata, piuttosto utilizziamo il Terminal, che non lascia tali file in giro).
> 
> NB le segnalazioni fatte a voce finiscono nel dimenticatoio prim ancora che si finisca di riferirle
Ah ok, meno male. Sicuramente allora ho fatto o compressione o copia e incolla di qualche file dentro la cartella dell'ontologia dal Finder, senza modificare i file stessi.

Ora provo e se è risolto chiudo tutto.

**Comment by valeriosantarelli** [comment]
E' tornata, alive and kicking. Chiudo.
