### ISSUE TITLE
Query report per query EQL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#306]
Più che una issue è una domanda:

In caso di esecuzione di una query EQL, siamo in grado di produrre le stesse informazioni relativamente al query report che produciamo per una query normale?
Quindi Ontology/View/SQL Rewritings (quali e quanti)?

Se si ok, quando sarà implementato ce li mettiamo e ok.
Altrimenti, forse sarebbe il caso di prevedere un tab dentro il report query in cui possiamo scrivere SOLO le informazioni che produciamo sia per le query normali sia per le query EQL (quindi ad esempio numeri di risultati e tempo di esecuzione), e spostare le informazioni che possiamo produrre solo per le query normali in un altro spazio espandibile.

Il punto è che pare brutto prevedere per tutte le query degli spazi da riempire con info che possiamo produrre solo per determinati tipi di query. Che ne pensate?

**Comment by giacomoronconiobda** [comment]
Secondo me si può aggiungere un tab SPARQL Tables in cui ci sono le query congiuntuve che vanno a creare le SPARQL tables

**Comment by valeriosantarelli** [comment]
> Secondo me si può aggiungere un tab SPARQL Tables in cui ci sono le query congiuntuve che vanno a creare le SPARQL tables

Ok, ma poi come rappresentiamo i risultati di unfolding e rewriting per ciascuna SPARQL table?

**Comment by giacomoronconiobda** [comment]
Tutti insieme no? Anche ora non sappiamo quale rewriting viene da quale
riscrittura sull'ontologia. Nel caso EQL non sapremo neanche da quale
SPARQL table viene la riscrittura sull'ontologia. Mi sembra in linea con il
resto dei rewritings

Il giorno ven 27 mar 2020 alle ore 22:09 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by valeriosantarelli** [comment]
Ok, a questo punto buttiamo tutto insieme, in attesa di un'idea migliore.
Creo una issue dedicata e chiudo questa.
