### ISSUE TITLE
Download Ontologia Approssimata

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#31]
Fornire un servizio e un bottone per esportare l'ontologia approssimata

**Comment by roodsey** [comment]
@giacomoronconiobda @valeriosantarelli indicare path e verbo HTTP corrispondente a cui collegare il servizio richiesto

**Comment by giacomoronconiobda** [comment]
UPDATE aggiunto parametro

`/owlOntology/{name}/version `
`GET`
`FileInfo` 
`version={String}, format={Functional Syntax, RDF/XML, Turtle, Graphol}, approximated={Boolean}`

**Comment by roodsey** [comment]
Rotta aggiunta e servizio implementato, ove possibile.

**Comment by valeriosantarelli** [comment]
Riapro per l'implementazione lato interfaccia.

E' necessario capire dove è il caso di aggiungere il bottone di download per l'ontologia approssimata.

**Comment by giacomoronconiobda** [comment]
aggiunto pulsante/menu download in ontology info
