### ISSUE TITLE
Bug EQL count

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#317]
Nella specifca Books la seguente query genera 31 risultati:
```
select ?x where {?x a :Book}
```
Mentre la corrispettiva count resituisce 27 risultati:
```
select (count(?x) as ?count) where {?x a :Book}
```
Dopo un attenta analisi effettuaata collettivamente per mezzo skype si pensa ce il bug sia dovuto al fatto che il reasoning nella query non EQL non sia attivato.

**Comment by valeriosantarelli** [comment]
Ho riprovato la query count su books dopo il commit 3343 su mastro, e ora il risultato è corretto.
Chiudo e quaranteno, appena possibile provo a fare altri test.
