### ISSUE TITLE
Errore visualizzazione rewriting

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#319]
Il tentativo di visualizzare i rewriting della query spielberg su imdb produce il seguente errore:

index.js:1446 Parse error on line 5:
.../name>  ?Spielberg, Steven .    ?title0
-----------------------^
Expecting 'IRIREF', 'PNAME_NS', 'VAR', '(', 'INTEGER', 'NIL', '[', 'BLANK_NODE_LABEL', 'ANON', 'DECIMAL', 'DOUBLE', 'BOOLEAN', 'STRING_LITERAL1', 'STRING_LITERAL2', 'STRING_LITERAL_LONG1', 'STRING_LITERAL_LONG2', 'INTEGER_POSITIVE', 'DECIMAL_POSITIVE', 'DOUBLE_POSITIVE', 'INTEGER_NEGATIVE', 'DECIMAL_NEGATIVE', 'DOUBLE_NEGATIVE', 'PNAME_LN', got 'INVALID'
console.<computed> @ index.js:1446
index.js:1446 Error: Parse error on line 5:
.../name>  ?Spielberg, Steven .    ?title0
-----------------------^
Expecting 'IRIREF', 'PNAME_NS', 'VAR', '(', 'INTEGER', 'NIL', '[', 'BLANK_NODE_LABEL', 'ANON', 'DECIMAL', 'DOUBLE', 'BOOLEAN', 'STRING_LITERAL1', 'STRING_LITERAL2', 'STRING_LITERAL_LONG1', 'STRING_LITERAL_LONG2', 'INTEGER_POSITIVE', 'DECIMAL_POSITIVE', 'DOUBLE_POSITIVE', 'INTEGER_NEGATIVE', 'DECIMAL_NEGATIVE', 'DOUBLE_NEGATIVE', 'PNAME_LN', got 'INVALID'
    at Parser.parseError (SparqlParser.js:3580)
    at Parser.parse (SparqlParser.js:3686)
    at Parser.parser.parse (sparql.js:36)
    at format (OntologyRewritings.js:25)
    at OntologyRewritings.convertData (OntologyRewritings.js:94)
    at MastroApi.js:1078

**Comment by giacomoronconiobda** [comment]
L'errore è dovuto alla query sparql sintatticamente sbagliata passata da mws. Ho catchato l'errore in modo che non venga formattata una query sparql sbagliata. Giro a @roodsey per risolvere l'errore lato servizi
La chiamata è:

 ```
'/endpoint/' + endpointName + '/query/' + executionID + '/ontologyRewritings'
```
