### ISSUE TITLE
Utente basic/advanced

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#320]
Implementare la possibilità di caratterizzare un utente come basic oppure advanced.
Ovviamente l'utente stesso può modificare questa impostazione.

Questa funzionalità rientra nel contesto più ampio di gestione degli utenti, quindi la rimando alla milestone 0.3.

**Comment by roodsey** [comment]
Credo che la issue sia focalizzata in modo impreciso: non è l'utente ad essere "basic" o "advanced", ma l'interfaccia di Monolith. In generale un utente ha il suo ruolo e da solo non deve poterlo cambiare.

**Comment by valeriosantarelli** [comment]
Quindi in pratica l'utente può avere ruolo admin/basic (ed eventualmente altri se servono), e può scegliere se visualizzare l'interfaccia basic o avanzata?
Per me va bene, l'importante credo sia che anche un utente admin può scegliere di vedere l'interfaccia basic (e ovviamente un utente non admin quella advanced).

**Comment by roodsey** [comment]
Dobbiamo evitare di confondere i ruoli/privilegi con eventuali profili di visualizzazione dell'interfaccia. Sono due cose diverse. In particolare, dato un ruolo si può definire una modalità di visualizzazione adeguata che mostri solo le funzionalità attivabili da utenti con quel ruolo. A livello di servizi implementerò sempre i controlli, ma mostrare pulsanti che l'utente non può premere non è una cosa bellissima

**Comment by valeriosantarelli** [comment]
Allora questa issue la chiudo, faccio riferimento alla issue #180 per la scelta dell'interfaccia direttamente nel Tab Rendering, e la gestione di utenti e profili sarà indipendente da questa scelta.
