### ISSUE TITLE
Query advanced

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#321]
Implementare l'interfaccia per le query da eseguire in modalità advanced.
Ricapitolando, funzionalmente le cose dovrebbero andare così:

- Esecuzione in modalità basic: i pulsanti toggle che ci sono ora non vengono visualizzati, si vede solo Run/Stop e i pulsanti per il catalogo

- Esecuzione in modalità advanced:
--- scelta di esecuzione in modalità CQ o EQL
--- scelta di attivazione del reasoning nelle diverse modalità
--- funzione di verifica del profilo della query (CQ o EQL)
--- altro?

Prevederei nel query tab un unico pulsante toggle che attiva o disattiva la modalità di query answering advanced (tipo con etichetta Advanced Query Mode), visualizzabile SOLO per gli utenti che si dichiarano advanced.

In attesa di avere implementato la gestione degli utenti, e quindi la possibilità per un utente di dichiararsi Advanced o meno, prevederei questa interfaccia per tutti gli utenti ovviamente.

**Comment by giacomoronconiobda** [comment]
Marco mi sembra parlava di due toggle reasoning, Uno per le cq uno per le
eql.

Il mar 24 mar 2020, 11:21 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Si, la funzionalità "scelta di attivazione del reasoning nelle diverse modalità" si traduce immagino in due toggle buttons, uno per CQ e uno per EQL.

**Comment by giacomoronconiobda** [comment]
Mancano da definire i paramentri della rotta start query

**Comment by valeriosantarelli** [comment]
Mi aggiungo alla issue per modificare la documentazione una volta completata l'interfaccia.

**Comment by giacomoronconiobda** [comment]
Mock up completoe pushato

**Comment by giacomoronconiobda** [comment]
Aggiungere query param alle 4 rotte per far partire le query e collegarle a monolith.

**Comment by roodsey** [comment]
aggiungere i parametri di query
- advanced = true / false (default)
- querySemantics = CQ / UCQ
- expandSparqlTables = true (default) / false

alle rotte
/endpoint/{name}/query/start
/endpoint/{name}/query/{queryID}/start
/endpoint/{name}/cquery/start
/endpoint/{name}/cquery/{queryID}/start

**Comment by roodsey** [comment]
Parametri aggiunti e propagati alle classi sottostanti: implementazione in corso

**Comment by roodsey** [comment]
Implementazione conclusa: richiesto aggiornamento di mastro-gui-api e mws

**Comment by valeriosantarelli** [comment]
L'esecuzione delle query in modalità CQ è corretta.

Books (CQ, No Reasoning) -> 27 risultati
Books (CQ, Reasoning) -> 31 risultati

L'esecuzione delle query in modalità EQL invece ha dei problemi. Sia con che senza reasoning, quando avvio la query, il sistema entra in uno stato di loop. Il log riporta sempre questo messaggio:

+[[[[[     E Q L     S E R V E R         S T A R T E D     ]]]]]
 -> 

+
* @@@@@ jdbc:h2:mem:eql_temp
[[[[[     E Q L     S E R V E R         S T A R T E D     ]]]]]
 -> 
+
*
+ @@@@@ jdbc:h2:mem:eql_temp
[[[[[     E Q L     S E R V E R         S T A R T E D     ]]]]]
 -> 

+
+ @@@@@ jdbc:h2:mem:eql_temp
+[[[[[     E Q L     S E R V E R         S T A R T E D     ]]]]]
 -> 

*
+ @@@@@ jdbc:h2:mem:eql_temp
[[[[[     E Q L     S E R V E R         S T A R T E D     ]]]]]
 ->

**Comment by valeriosantarelli** [comment]
Altra problematica: le query in modalità basic vengono eseguite di default senza il reasoning.

**Comment by giacomoronconiobda** [comment]
Io quando l'utente è basic non setto il parametro reasoning. Sbaglio Marco?

Il giorno sab 28 mar 2020 alle ore 10:37 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by valeriosantarelli** [comment]
Mi pare che stia funzionando tutto.

Ho fatto i testi con Books, query all_books, e tutto come previsto in modalità basic, e con le 4 combinazioni della modalità advanced.

A questo punto, e se emergono ulteriori problematiche le gestiremo.
