### ISSUE TITLE
Titolo della pagina Datasources

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#323]
Inserire il titolo "Datasources" nella pagina datasources, in modo analogo a quanto c'è per Ontologies, Knowledge Graphs, etc.

Valuterei anche se farlo pure per le pagine di Inclusions/Denials/Keys

**Comment by giacomoronconiobda** [comment]
Fatto in tutto ma non in Denial perchè lì il titolo è il nom del denial
