### ISSUE TITLE
Ridenominazione rotte rewritings

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#327]
Adottare questa ridenominazione per tutte le rotte riguardanti I rewritings di una query:

- view rewritings -> SQL rewritings
- mapping rewritings -> view rewritings

**Comment by roodsey** [comment]
OLD: /endpoint/{name}/query/{queryID}/viewRewritings
NEW:

OLD: /endpoint/{name}/query/{queryID}/mappingRewritings
NEW:
