### ISSUE TITLE
Errore avvio Monolith su Windows

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#330]
Dal primo test di Fabio.

Riscontra due problemi (partendo da uno stato in cui la mastro-home non esiste proprio):
- Monolith si avvia, ma quando cerca di creare una ontologia (non caricare una versione, proprio creare una ontologia), il sistema restituisce l'errore che riporto sotto.
- dalla mastro-home si vede che l'ontologia è in effetti stata creata; però a questo punto Monolith non riesce più ad avviarsi.

Assegno a @roodsey ma coinvolgo anche @giacomoronconiobda che ha seguito la prima parte della problematica con Fabio.

Allego la mastro-home creata: [mastro-home.zip](https://github.com/obdasystems/monolith/files/4382242/mastro-home.zip)

{"cause":null,"stackTrace":[{"methodName":"loadOntology","fileName":"MwsxOntologyManager.java","lineNumber":1062,"className":"com.mwsx.engine.MwsxOntologyManager","nativeMethod":false},{"methodName":"lambda$init$0","fileName":"MwsxOntologyManager.java","lineNumber":1093,"className":"com.mwsx.engine.MwsxOntologyManager","nativeMethod":false},{"methodName":"forEachRemaining","fileName":"Iterator.java","lineNumber":116,"className":"java.util.Iterator","nativeMethod":false},{"methodName":"forEachRemaining","fileName":"Spliterators.java","lineNumber":1801,"className":"java.util.Spliterators$IteratorSpliterator","nativeMethod":false},{"methodName":"forEach","fileName":"ReferencePipeline.java","lineNumber":580,"className":"java.util.stream.ReferencePipeline$Head","nativeMethod":false},{"methodName":"init","fileName":"MwsxOntologyManager.java","lineNumber":1090,"className":"com.mwsx.engine.MwsxOntologyManager","nativeMethod":false},{"methodName":"addOntology","fileName":"MwsxOntologyManager.java","lineNumber":383,"className":"com.mwsx.engine.MwsxOntologyManager","nativeMethod":false},{"methodName":"post__owlOntology_name","fileName":"MwsxService.java","lineNumber":298,"className":"com.mwsx.services.MwsxService","nativeMethod":false},{"methodName":"invoke0","fileName":"NativeMethodAccessorImpl.java","lineNumber":-2,"className":"sun.reflect.NativeMethodAccessorImpl","nativeMethod":true},{"methodName":"invoke","fileName":"NativeMethodAccessorImpl.java","lineNumber":62,"className":"sun.reflect.NativeMethodAccessorImpl","nativeMethod":false},{"methodName":"invoke","fileName":"DelegatingMethodAccessorImpl.java","lineNumber":43,"className":"sun.reflect.DelegatingMethodAccessorImpl","nativeMethod":false},{"methodName":"invoke","fileName":"Method.java","lineNumber":498,"className":"java.lang.reflect.Method","nativeMethod":false},{"methodName":"invoke","fileName":"ResourceMethodInvocationHandlerFactory.java","lineNumber":81,"className":"org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1","nativeMethod":false},{"methodName":"run","fileName":"AbstractJavaResourceMethodDispatcher.java","lineNumber":144,"className":"org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1","nativeMethod":false},{"methodName":"invoke","fileName":"AbstractJavaResourceMethodDispatcher.java","lineNumber":161,"className":"org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher","nativeMethod":false},{"methodName":"doDispatch","fileName":"JavaResourceMethodDispatcherProvider.java","lineNumber":160,"className":"org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker","nativeMethod":false},{"methodName":"dispatch","fileName":"AbstractJavaResourceMethodDispatcher.java","lineNumber":99,"className":"org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher","nativeMethod":false},{"methodName":"invoke","fileName":"ResourceMethodInvoker.java","lineNumber":389,"className":"org.glassfish.jersey.server.model.ResourceMethodInvoker","nativeMethod":false},{"methodName":"apply","fileName":"ResourceMethodInvoker.java","lineNumber":347,"className":"org.glassfish.jersey.server.model.ResourceMethodInvoker","nativeMethod":false},{"methodName":"apply","fileName":"ResourceMethodInvoker.java","lineNumber":102,"className":"org.glassfish.jersey.server.model.ResourceMethodInvoker","nativeMethod":false},{"methodName":"run","fileName":"ServerRuntime.java","lineNumber":309,"className":"org.glassfish.jersey.server.ServerRuntime$2","nativeMethod":false},{"methodName":"call","fileName":"Errors.java","lineNumber":271,"className":"org.glassfish.jersey.internal.Errors$1","nativeMethod":false},{"methodName":"call","fileName":"Errors.java","lineNumber":267,"className":"org.glassfish.jersey.internal.Errors$1","nativeMethod":false},{"methodName":"process","fileName":"Errors.java","lineNumber":315,"className":"org.glassfish.jersey.internal.Errors","nativeMethod":false},{"methodName":"process","fileName":"Errors.java","lineNumber":297,"className":"org.glassfish.jersey.internal.Errors","nativeMethod":false},{"methodName":"process","fileName":"Errors.java","lineNumber":267,"className":"org.glassfish.jersey.internal.Errors","nativeMethod":false},{"methodName":"runInScope","fileName":"RequestScope.java","lineNumber":317,"className":"org.glassfish.jersey.process.internal.RequestScope","nativeMethod":false},{"methodName":"process","fileName":"ServerRuntime.java","lineNumber":292,"className":"org.glassfish.jersey.server.ServerRuntime","nativeMethod":false},{"methodName":"handle","fileName":"ApplicationHandler.java","lineNumber":1139,"className":"org.glassfish.jersey.server.ApplicationHandler","nativeMethod":false},{"methodName":"service","fileName":"WebComponent.java","lineNumber":460,"className":"org.glassfish.jersey.servlet.WebComponent","nativeMethod":false},{"methodName":"service","fileName":"ServletContainer.java","lineNumber":386,"className":"org.glassfish.jersey.servlet.ServletContainer","nativeMethod":false},{"methodName":"service","fileName":"ServletContainer.java","lineNumber":334,"className":"org.glassfish.jersey.servlet.ServletContainer","nativeMethod":false},{"methodName":"service","fileName":"ServletContainer.java","lineNumber":221,"className":"org.glassfish.jersey.servlet.ServletContainer","nativeMethod":false},{"methodName":"handle","fileName":"ServletHolder.java","lineNumber":760,"className":"org.eclipse.jetty.servlet.ServletHolder","nativeMethod":false},{"methodName":"doFilter","fileName":"ServletHandler.java","lineNumber":1617,"className":"org.eclipse.jetty.servlet.ServletHandler$CachedChain","nativeMethod":false},{"methodName":"handle","fileName":"CrossOriginFilter.java","lineNumber":310,"className":"org.eclipse.jetty.servlets.CrossOriginFilter","nativeMethod":false},{"methodName":"doFilter","fileName":"CrossOriginFilter.java","lineNumber":264,"className":"org.eclipse.jetty.servlets.CrossOriginFilter","nativeMethod":false},{"methodName":"doFilter","fileName":"ServletHandler.java","lineNumber":1604,"className":"org.eclipse.jetty.servlet.ServletHandler$CachedChain","nativeMethod":false},{"methodName":"doHandle","fileName":"ServletHandler.java","lineNumber":545,"className":"org.eclipse.jetty.servlet.ServletHandler","nativeMethod":false},{"methodName":"nextHandle","fileName":"ScopedHandler.java","lineNumber":233,"className":"org.eclipse.jetty.server.handler.ScopedHandler","nativeMethod":false},{"methodName":"doHandle","fileName":"SessionHandler.java","lineNumber":1592,"className":"org.eclipse.jetty.server.session.SessionHandler","nativeMethod":false},{"methodName":"nextHandle","fileName":"ScopedHandler.java","lineNumber":233,"className":"org.eclipse.jetty.server.handler.ScopedHandler","nativeMethod":false},{"methodName":"doHandle","fileName":"ContextHandler.java","lineNumber":1296,"className":"org.eclipse.jetty.server.handler.ContextHandler","nativeMethod":false},{"methodName":"nextScope","fileName":"ScopedHandler.java","lineNumber":188,"className":"org.eclipse.jetty.server.handler.ScopedHandler","nativeMethod":false},{"methodName":"doScope","fileName":"ServletHandler.java","lineNumber":485,"className":"org.eclipse.jetty.servlet.ServletHandler","nativeMethod":false},{"methodName":"doScope","fileName":"SessionHandler.java","lineNumber":1562,"className":"org.eclipse.jetty.server.session.SessionHandler","nativeMethod":false},{"methodName":"nextScope","fileName":"ScopedHandler.java","lineNumber":186,"className":"org.eclipse.jetty.server.handler.ScopedHandler","nativeMethod":false},{"methodName":"doScope","fileName":"ContextHandler.java","lineNumber":1211,"className":"org.eclipse.jetty.server.handler.ContextHandler","nativeMethod":false},{"methodName":"handle","fileName":"ScopedHandler.java","lineNumber":141,"className":"org.eclipse.jetty.server.handler.ScopedHandler","nativeMethod":false},{"methodName":"handle","fileName":"HandlerList.java","lineNumber":59,"className":"org.eclipse.jetty.server.handler.HandlerList","nativeMethod":false},{"methodName":"handle","fileName":"HandlerWrapper.java","lineNumber":127,"className":"org.eclipse.jetty.server.handler.HandlerWrapper","nativeMethod":false},{"methodName":"handle","fileName":"Server.java","lineNumber":500,"className":"org.eclipse.jetty.server.Server","nativeMethod":false},{"methodName":"lambda$handle$1","fileName":"HttpChannel.java","lineNumber":386,"className":"org.eclipse.jetty.server.HttpChannel","nativeMethod":false},{"methodName":"dispatch","fileName":"HttpChannel.java","lineNumber":562,"className":"org.eclipse.jetty.server.HttpChannel","nativeMethod":false},{"methodName":"handle","fileName":"HttpChannel.java","lineNumber":378,"className":"org.eclipse.jetty.server.HttpChannel","nativeMethod":false},{"methodName":"onFillable","fileName":"HttpConnection.java","lineNumber":270,"className":"org.eclipse.jetty.server.HttpConnection","nativeMethod":false},{"methodName":"succeeded","fileName":"AbstractConnection.java","lineNumber":311,"className":"org.eclipse.jetty.io.AbstractConnection$ReadCallback","nativeMethod":false},{"methodName":"fillable","fileName":"FillInterest.java","lineNumber":103,"className":"org.eclipse.jetty.io.FillInterest","nativeMethod":false},{"methodName":"run","fileName":"ChannelEndPoint.java","lineNumber":117,"className":"org.eclipse.jetty.io.ChannelEndPoint$2","nativeMethod":false},{"methodName":"runTask","fileName":"EatWhatYouKill.java","lineNumber":336,"className":"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","nativeMethod":false},{"methodName":"doProduce","fileName":"EatWhatYouKill.java","lineNumber":313,"className":"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","nativeMethod":false},{"methodName":"tryProduce","fileName":"EatWhatYouKill.java","lineNumber":171,"className":"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","nativeMethod":false},{"methodName":"run","fileName":"EatWhatYouKill.java","lineNumber":129,"className":"org.eclipse.jetty.util.thread.strategy.EatWhatYouKill","nativeMethod":false},{"methodName":"run","fileName":"ReservedThreadExecutor.java","lineNumber":388,"className":"org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread","nativeMethod":false},{"methodName":"runJob","fileName":"QueuedThreadPool.java","lineNumber":806,"className":"org.eclipse.jetty.util.thread.QueuedThreadPool","nativeMethod":false},{"methodName":"run","fileName":"QueuedThreadPool.java","lineNumber":938,"className":"org.eclipse.jetty.util.thread.QueuedThreadPool$Runner","nativeMethod":false},{"methodName":"run","fileName":"Thread.java","lineNumber":745,"className":"java.lang.Thread","nativeMethod":false}],"localizedMessage":null,"message":null,"suppressed":[]}

**Comment by valeriosantarelli** [comment]
Confermo la problematica riscontrata su installazione su altra macchina Windows fatta da me.
L'errore avviene al momento di creazione dell'ontologia:

####################################################################################
 >> [METHOD] post__owlOntology_name
------------------------------------------------------------------------------------
 >> [PATH]   /owlOntology
------------------------------------------------------------------------------------
  [par] {
  "ontologyID" : "Books",
  "ontologyDescription" : null,
  "ontologyVersions" : [ ],
  "ontologyOwner" : {
    "name" : "mastro",
    "roles" : null
  },
  "ontologyDate" : 1585166278485
}
20:57:58.553 [qtp3728767-18] ERROR com.mwsx.services.MwsxService - -------------------  E R R O R      S T A R T  -------------------------
-------------------  E R R O R      S T A R T  -------------------------
java.lang.NullPointerException
	at com.mwsx.engine.MwsxOntologyManager.loadOntology(MwsxOntologyManager.java:1062)
	at com.mwsx.engine.MwsxOntologyManager.lambda$init$0(MwsxOntologyManager.java:1093)
	at java.util.Iterator.forEachRemaining(Unknown Source)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.mwsx.engine.MwsxOntologyManager.init(MwsxOntologyManager.java:1090)
	at com.mwsx.engine.MwsxOntologyManager.addOntology(MwsxOntologyManager.java:383)
	at com.mwsx.services.MwsxService.post__owlOntology_name(MwsxService.java:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309)

**Comment by giacomoronconiobda** [comment]
Mi sembra che nel codice ci sia un riferimento a un path del tipo "/info".
Forse bisogna usare la costante Java per il path separator File.separator

Il mer 25 mar 2020, 21:03 Valerio Santarelli <notifications@github.com> ha
scritto:
