### ISSUE TITLE
Errore avvio distribuzione Monolith su MacOS Catalina 10.15.1

### ISSUE THREAD

**Issue by NonnonePalmiro** [obdasystems/monolith#331]
Nel lanciare lo script di avvio per la distribuzione scaricabile da https://drive.google.com/drive/folders/1VusNdJaR-TKqkcAzAuqm340PGLSxOTaM?usp=sharing
mi viene ritornato il seguente errore: "Error: Unable to access jarfile mws-server-1.0.0.jar"

Assegno a Giacomo come suggerito da V.S. (Metto solo le iniziali onde evitare vendette trasversali...)

<img width="682" alt="Schermata 2020-03-25 alle 19 22 20" src="https://user-images.githubusercontent.com/46748150/77571668-01c18700-6ece-11ea-9366-69e7a950715d.png">

**Comment by valeriosantarelli** [comment]
Segnalo (anche per portare una testimonianza positiva contro le due negative di @savo-fabio e @NonnonePalmiro ahaha) che ho provato l'installazione su un secondo Mac (sistema operativo Mojave), e non ho riscontrato problemi.
In questa installazione, monolith si trova nella cartella home dell'utente. Quindi /Utenti/nomeutente/monolith0.1/

**Comment by giacomoronconiobda** [comment]
L'errore è dovuto al fatto che lo script viene lanciato da una cartella
diversa da quella dov'è lo script. Il file run.sh deve essere eseguito
dalla cartella dove sta quindi:

spostati con il comando cd dentro la cartella monolith 0.1 e poi si lancia
con ./run.sh

Non chiudete la issue così che nel prossimo build cerco di evitare che
questa eventualità si verifichi.

Il mer 25 mar 2020, 20:04 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by mnamici** [comment]
Se può essere utile nel frattempo allego lo script `run.sh` che sto usando per me, vale sia per Linux che per macOS e può essere lanciato da qualsiasi cartella.

[run.zip](https://github.com/obdasystems/monolith/files/4383928/run.zip)

**Comment by valeriosantarelli** [comment]
Confermo che lo script di Manuel funziona su macOS lanciato anche da una cartella diversa da quella di Monolith, però non carica l'icona di Monolith nella Dock bar (c'è quella generica di Java).

**Comment by mnamici** [comment]
Ora dovrebbe funzionare anche l'icona su macOS:

[run.tar.gz](https://github.com/obdasystems/monolith/files/4384290/run.tar.gz)

P.S. allego un tar.gz questa volta perché non so se zip preserva i permessi eseguibili così non c'e da fare `chmod +x` in caso.

**Comment by valeriosantarelli** [comment]
> Ora dovrebbe funzionare anche l'icona su macOS:
> 
> [run.tar.gz](https://github.com/obdasystems/monolith/files/4384290/run.tar.gz)
> 
> P.S. allego un tar.gz questa volta perché non so se zip preserva i permessi eseguibili così non c'e da fare `chmod +x` in caso.

Mi dà questo errore:
^CValerios-MBP:Desktop valeriosantarelli$ /Users/valeriosantarelli/monolith\ 0.1/run.sh sh
Using java from: /usr/bin/java
Errore: impossibile trovare o caricare la classe principale 0.1.resources.icons.icon_512@1x.png

**Comment by giacomoronconiobda** [comment]
maledetti spazi nei nomi delle cartelle!

**Comment by valeriosantarelli** [comment]
Senza spazi infatti funziona (vabbè quindi se gestiamo la presenza degli spazi possiamo usare questo di manuel no?)..

**Comment by giacomoronconiobda** [comment]
[run.zip](https://github.com/obdasystems/monolith/files/4386157/run.zip)

ho messo l'escape degli spazi. Grazie Manuel per lo script

**Comment by giacomoronconiobda** [comment]
@valeriosantarelli puoi provare se funziona lo script con gli spazi e in caso chiudi la issue? Grazie

**Comment by valeriosantarelli** [comment]
Valerios-MBP:monolith 0.1 valeriosantarelli$ ./run_mn.sh
Using java from: /usr/bin/java
Errore: impossibile trovare o caricare la classe principale 0.1.resources.icons.icon_512@1x.png"

**Comment by mnamici** [comment]
> Mi dà questo errore:
> ^CValerios-MBP:Desktop valeriosantarelli$ /Users/valeriosantarelli/monolith\ 0.1/run.sh sh
> Using java from: /usr/bin/java
> Errore: impossibile trovare o caricare la classe principale [0.1.resources.icons.icon_512@1x.png](mailto:0.1.resources.icons.icon_512@1x.png)

Mi ero dimenticato degli spazi, e causa pigrizia non ho testato prima sulla macchina virtuale :-P

> [run.zip](https://github.com/obdasystems/monolith/files/4386157/run.zip)
> 
> ho messo l'escape degli spazi. Grazie Manuel per lo script

L'espansione è un pò rognosa in questo caso, e visto che la versione di bash in macos non supporta gli array meglio usare una variabile secondaria.

Ora dovrebbe funzionare, spazi o meno.

[run.tar.gz](https://github.com/obdasystems/monolith/files/4386391/run.tar.gz)

**Comment by giacomoronconiobda** [comment]
io avevo provato pure così dovrebbe andare no?
[run.zip](https://github.com/obdasystems/monolith/files/4386541/run.zip)

**Comment by valeriosantarelli** [comment]
> > Mi dà questo errore:
> > ^CValerios-MBP:Desktop valeriosantarelli$ /Users/valeriosantarelli/monolith\ 0.1/run.sh sh
> > Using java from: /usr/bin/java
> > Errore: impossibile trovare o caricare la classe principale [0.1.resources.icons.icon_512@1x.png](mailto:0.1.resources.icons.icon_512@1x.png)
> 
> Mi ero dimenticato degli spazi, e causa pigrizia non ho testato prima sulla macchina virtuale :-P
> 
> > ho messo l'escape degli spazi. Grazie Manuel per lo script
> 
> L'espansione è un pò rognosa in questo caso, e visto che la versione di bash in macos non supporta gli array meglio usare una variabile secondaria.
> 
> Ora dovrebbe funzionare, spazi o meno.
> 
> [run.tar.gz](https://github.com/obdasystems/monolith/files/4386391/run.tar.gz)

Questa funziona.

**Comment by valeriosantarelli** [comment]
> io avevo provato pure così dovrebbe andare no?
> [run.zip](https://github.com/obdasystems/monolith/files/4386541/run.zip)

Mi dice questo:
Using java from: /usr/bin/java
Invalid maximum heap size: -Xmx512M -Xdock:icon='/Users/valeriosantarelli/monolith 0.1/resources/icons/icon_512@1x.png'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit

**Comment by giacomoronconiobda** [comment]
Manuel 2 - Giacomo 0

**Comment by valeriosantarelli** [comment]
Il premio come miglior smartworker OBDA Systems del mese va a @mnamici . Per pasqua, uovo di pasqua virtuale in premio a lui.
