### ISSUE TITLE
Errore connessione con database

### ISSUE THREAD

**Issue by savo-fabio** [obdasystems/monolith#332]
Dopo aver creato una sorgente di dati MySQL (MySQL Server 5.7) alla pressione del tasto "Test connection" il sistema restituisce il seguente errore: 

"The server time zone value 'ora solare Europa occidentale' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support."

Allego il contenuto della console. 
[log.txt](https://github.com/obdasystems/monolith/files/4386302/log.txt)

**Comment by valeriosantarelli** [comment]
Che versione di MySQL stai usando?
Il log ti dice qualcosa? Se si, incolla lo stacktrace.

**Comment by savo-fabio** [comment]
Ho aggiunto le informazioni richieste

**Comment by valeriosantarelli** [comment]
> Ho aggiunto le informazioni richieste

Alla issue? Io non le vedo, non è che non ti ha salvato le modifiche (o forse mi sto rincoglionendo a forza di stare dentro casa)?

**Comment by savo-fabio** [comment]
Non aggiornava il contenuto del file perchè troppo lungo. Ora dovrebbe andare

**Comment by roodsey** [comment]
Fabio, puoi provare ad inserire questa URL per la connessione JDBC? (abbi cura di specificare il giusto nome di database prima del punto interrogativo)
'''
jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
'''

**Comment by valeriosantarelli** [comment]
Per future reference: https://github.com/TdP-2019/materiale/blob/master/faq/timezone.md

**Comment by savo-fabio** [comment]
Con la stringa di connessione indicata da Marco il test di connessione viene eseguito correttamente.  

 

Da: Marco Ruzzi <notifications@github.com> 
Inviato: Thursday, March 26, 2020 10:43
A: obdasystems/monolith <monolith@noreply.github.com>
Cc: Domenico Fabio Savo <savo.fabio@gmail.com>; Author <author@noreply.github.com>
Oggetto: Re: [obdasystems/monolith] Errore connessione con database (#332)

 

Fabio, puoi provare ad inserire questa URL per la connessione JDBC? (abbi cura di specificare il giusto nome di database prima del punto interrogativo)
'''
jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
'''

**Comment by valeriosantarelli** [comment]
Ottimo, si può chiudere allora.

**Comment by giacomoronconiobda** [comment]
Giusto per documentazione ho riscontrato lo stesso errore per books su linux. L'ho fissato con la seguente stringa di connessione:
```
jdbc:mysql://localhost/books?serverTimezone=UTC
```
