### ISSUE TITLE
Problemi credenziali su chrome

### ISSUE THREAD

**Issue by NonnonePalmiro** [obdasystems/monolith#336]
Ogni volta che effettuo il login usando chrome, il browser segnala problemi di esposizione delle credenziali utilizzate

![Schermata 2020-03-26 alle 12 11 40](https://user-images.githubusercontent.com/46748150/77642209-97f0be00-6f5d-11ea-8f45-0bd745ecba64.png)

**Comment by valeriosantarelli** [comment]
E' una feature: Monolith promuove gli open data.

**Comment by NonnonePalmiro** [comment]
Ma infatti mi sono ben guardato dall'etichettarlo come Bug.

**Comment by giacomoronconiobda** [comment]
https://stackoverflow.com/questions/59410675/a-data-breach-on-a-site-exposed-your-password-message-sent-by-chrome-on-my-login

**Comment by valeriosantarelli** [comment]
Si può chiudere quindi questa issue?
