### ISSUE TITLE
Modifica profilo parser SQL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#343]
Modificare il profilo del parser SQL a seconda del driver jdbc scelto per la datasource di default del file di mapping.
Per evitare cose tipo questa (Postgresql):

![Schermata 2020-03-26 alle 18 16 46](https://user-images.githubusercontent.com/8250758/77700520-a8805300-6fb4-11ea-8971-09c716c14d1f.png)

**Comment by giacomoronconiobda** [comment]
ho fatto un test, anche se metto text/x-pgsql non piace lo stesso al parser di codemirror

**Comment by valeriosantarelli** [comment]
Ok, allora risolviamola così: si fa lo switch a seconda del driver scelto per il db di default nei mapping (se è stato definito), dopodichè permettiamo di fare il test e salvataggio della query anche se il parser riporta un errore.
