### ISSUE TITLE
Segnalazioni user test session con Fabio

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#345]
Diverse segnalazioni recepite durante 45 minuti di user test session con Fabio:

- [ ] la pagina degli Endpoints inizialmente è completamente vuota, e non si capisce bene cosa si deve fare (il pulsante + non è molto evidente). Forse quando non ci sono definiti Endpoints, si potrebbe inserire una scritta nella pagina di qualche tipo (poi pensiamo a definirla bene...)

- [x] nella creazione di un endpoint, se l'ontologia non ha versione, appare ancora la scritta NO_VERSION_PROVIDED

- [x] Quando si crea un Endpoint, appena creato, il suo stato risulta UNAVAILABLE. Questo ovviamente non è molto incoraggiante, si potrebbe sostituire UNAVAILABLE con STOPPED (ed eventualmente inserire un parametro di configurazione dentro settings o dentro la pagine di creazione dell'endpoint che permette di avviare l'endpoint non appena è creato)

- [x] questo è un piccolo bug: l'asterisco nel titolo del query tab non compare quando si modifica una query che è appena stata salvata in catalogo. Quindi: 1)aprire un nuovo tab; 2)scrivere una query; 3)salvarla nel catalogo; 4)modificarla -> non compare l'asterisco

- [x] serve evidenziare in modo più evidente che il sistema sta facendo qualcosa quando sta avviando un Endpoint oppure sta facendo il check della connection di un datasource. In particolare, in questo secondo caso, Fabio è subito entrato in modalità Maurizio, cliccando 10mila volte prima che arrivasse il messaggio "connection ok". Si potrebbe mettere una qualsiasi rotella/barra di stato/messaggio anche in modalità modale, che blocca il sistema finchè l'operazione non è completata.

- [x] nel tab delle query, mettere l'opzione CQ di default invece di EQL sul toggle (Fabio il 100% delle volte si è dimenticato di switchare su CQ)

- [x] non appena si apre la finestra del browser sulla pagina di login, esce il messaggio di Server Error (questo lo avevo notato anche io)

- [x] aggiungere nello spazio di Help quando si crea un Ontology Mapping anche la descrizione delle viste. A questo punto si potrebbe usare proprio una card, con sopra la descrizione e sotto il codice SQL.

- [x] per ovviare al problema di connessione al database con driver MySQL 8 su macchina Windows (che ovviamente non è un bug di Monolith, ma un problema di Windows/mysql), si potrebbe pensare di mettere un messaggio di supporto. In pratica, se il sistema operativo è Windows (abbiamo modo di controllarlo?) e si sceglie il driver MySQL, scrivere un messaggio sotto l'area della JDBC URL un messaggio di questo tipo: "If using localized Windows OS, please add serverTimezone parameter di JDBC URL, for example jdbc:mysql://localhost/db_name?user=root&password=root&serverTimezone=Europe/Rome." 

- [x] aumentare leggermente lo spazio, nella pagine delle Inclusione e Keys, tra la barra di search e il primo elemento della lista

**Comment by giacomoronconiobda** [comment]
1. C'è la stessa situazione per le viste e per i denial (lista a sinistra per selezionare/creare) ma anche per gli alberi dell'ontologia quando non c'è niente di selezionato. Dovremmo trovare una dicitura/comportamento comune penso.

**Comment by giacomoronconiobda** [comment]
3. Non è meglio una checkbox dentro la form?

**Comment by valeriosantarelli** [comment]
> 1. Non è meglio una checkbox dentro la form?

SI, va benissimo

**Comment by giacomoronconiobda** [comment]
4. Non sono d'accordo a bloccare il sistema rende tutto il meno fluido. Bisogna mettere la cosa cliccata in loading per le operazioni che prevedono un tempo di attesa (chiamata rest con il server). Aggiungo il loading al test connection

**Comment by valeriosantarelli** [comment]
Ok a non bloccare il sistema.
Quando dici "la cosa cliccata in loading", intendi com'è adesso il Run dell'endpoint? Perchè credo che il problema sia proprio che quello è poco evidente...la rotellina dentro il pulsante è molto piccola.

**Comment by valeriosantarelli** [comment]
> 1. C'è la stessa situazione per le viste e per i denial (lista a sinistra per selezionare/creare) ma anche per gli alberi dell'ontologia quando non c'è niente di selezionato. Dovremmo trovare una dicitura/comportamento comune penso.

Il suggerimenti di Fabio sarebbe il seguente:
- quando c'è una lista sempre per forza popolata (ad esempio in Navigation o in Ontology Mappings), fare in modo che una volta scelto un elemento, quando si lascia la pagina (tipo ci si sposta da Ontology a Mappings o SPARQL) e po ci si ritorna, rimane selezionato l'elemento. Come riferimento, anche Protégé e Mobi fanno così ad esempio.
- quando c'è una lista o una pagina che può essere vuota (ad esempio i Denials, gli Endpoints, le Datasources, i mapping di un un elemento, le Ontologie, etc. etc.) mettere, se la lista è vuota, un balloon (tipo quelli nello screenshot sotto) che punta al pulsante +, e dice "Oops, it seems like there are no ______ yet. Click on the Add _____ button to create the first one".
![Schermata 2020-03-27 alle 11 07 00](https://user-images.githubusercontent.com/8250758/77745315-56264d00-701b-11ea-914d-ed4ec038303b.png)

**Comment by giacomoronconiobda** [comment]
6. L'opzione di default è EQL perchè quando si è in modalità basic si prende sempre il ramo EQL

**Comment by giacomoronconiobda** [comment]
7. Non riesco a riprodurlo

**Comment by giacomoronconiobda** [comment]
> > 1. C'è la stessa situazione per le viste e per i denial (lista a sinistra per selezionare/creare) ma anche per gli alberi dell'ontologia quando non c'è niente di selezionato. Dovremmo trovare una dicitura/comportamento comune penso.
> 
> Il suggerimenti di Fabio sarebbe il seguente:
> 
> * quando c'è una lista sempre per forza popolata (ad esempio in Navigation o in Ontology Mappings), fare in modo che una volta scelto un elemento, quando si lascia la pagina (tipo ci si sposta da Ontology a Mappings o SPARQL) e po ci si ritorna, rimane selezionato l'elemento. Come riferimento, anche Protégé e Mobi fanno così ad esempio.
> * quando c'è una lista o una pagina che può essere vuota (ad esempio i Denials, gli Endpoints, le Datasources, i mapping di un un elemento, le Ontologie, etc. etc.) mettere, se la lista è vuota, un balloon (tipo quelli nello screenshot sotto) che punta al pulsante +, e dice "Oops, it seems like there are no ______ yet. Click on the Add _____ button to create the first one".
>   ![Schermata 2020-03-27 alle 11 07 00](https://user-images.githubusercontent.com/8250758/77745315-56264d00-701b-11ea-914d-ed4ec038303b.png)

Mi sembra una soluzione buona ma che poi ci fa prendere la strada dell'aiutare l'utente al primo utilizzo tramite tooltip. Cioè una volta che l'utente sa dov'è il bottone non è che glielo devi dire ogni volta

**Comment by valeriosantarelli** [comment]
> > > 1. C'è la stessa situazione per le viste e per i denial (lista a sinistra per selezionare/creare) ma anche per gli alberi dell'ontologia quando non c'è niente di selezionato. Dovremmo trovare una dicitura/comportamento comune penso.
> > 
> > 
> > Il suggerimenti di Fabio sarebbe il seguente:
> > 
> > * quando c'è una lista sempre per forza popolata (ad esempio in Navigation o in Ontology Mappings), fare in modo che una volta scelto un elemento, quando si lascia la pagina (tipo ci si sposta da Ontology a Mappings o SPARQL) e po ci si ritorna, rimane selezionato l'elemento. Come riferimento, anche Protégé e Mobi fanno così ad esempio.
> > * quando c'è una lista o una pagina che può essere vuota (ad esempio i Denials, gli Endpoints, le Datasources, i mapping di un un elemento, le Ontologie, etc. etc.) mettere, se la lista è vuota, un balloon (tipo quelli nello screenshot sotto) che punta al pulsante +, e dice "Oops, it seems like there are no ______ yet. Click on the Add _____ button to create the first one".
> >   ![Schermata 2020-03-27 alle 11 07 00](https://user-images.githubusercontent.com/8250758/77745315-56264d00-701b-11ea-914d-ed4ec038303b.png)
> 
> Mi sembra una soluzione buona ma che poi ci fa prendere la strada dell'aiutare l'utente al primo utilizzo tramite tooltip. Cioè una volta che l'utente sa dov'è il bottone non è che glielo devi dire ogni volta

Si. D'accordissimo.
E' una strada che infatti credo sia da percorrere: dei tooltip al primo utilizzo, e dei piccoli pulsanti "info" (come fa GraphDB) che possono anche rimanere sempre.
Non ho idea se siamo pronti a fare questo step adesso, si potrebbe intanto mettere i balloon che ci stanno sempre, poi raffiniamo la cosa.

**Comment by giacomoronconiobda** [comment]
Scusa ma questi balloon non sono i tooltip che già ci sono in hover? In pratica vogliamo che i tooltip siano sempre visibili?

**Comment by valeriosantarelli** [comment]
Si e no...concettualmente sono quelli, ovviamente con un messaggio più parlante.
Quelli che ci stanno adesso servono in pratica per decodificare l'icona, quelli che ci stiamo immaginando invece servono per far capire all'utente cosa deve fare nella pagina (quindi anche il messaggio è diverso).

**Comment by giacomoronconiobda** [comment]
E quindi se vai in hover ne compaiono due? Non è meglio mettere lo stesso
pulsante grande al centro quando c'è una pagina vuota? Comunque creerei una
issue apposita per questo problema.

Il ven 27 mar 2020, 15:58 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Ok creo una issue dedicata.

Riguardo la 7: hai provato facendo girare monolith dal build? Da lì me lo fa sempre, facendolo partire da codice non sempre.

**Comment by valeriosantarelli** [comment]
> 1. L'opzione di default è EQL perchè quando si è in modalità basic si prende sempre il ramo EQL

Scusa mi ero perso questo commento.
Non lo capisco però: che significa che si prende sempre il ramo EQL in modalità basic?
A prescindere comunque, io metterei CQ di default per l'interfaccia advanced: quella è la modalità nativa di Mastro, e in più vogliamo evitare che query CQ vengano eseguite in modalità EQL.

**Comment by giacomoronconiobda** [comment]
Io immagino EQL come la possibilità di estendere il linguaggio SPARQL:
1. EQL è acceso, faccio una CQ -> ramo CQ di mastro
2. EQL è acceso, faccio una query non CQ -> ramo EQL di mastro
3. EQL è spento, faccio una CQ -> ramo CQ di mastro
4. EQL è spento, faccio una query non CQ -> errore

Da utente mi aspetterei questo. Comunque lo metto su CQ di default

**Comment by giacomoronconiobda** [comment]
Io immagino EQL come la possibilità di estendere il linguaggio SPARQL:
1. EQL è acceso, faccio una CQ -> ramo CQ di mastro
2. EQL è acceso, faccio una query non CQ -> ramo EQL di mastro
3. EQL è spento, faccio una CQ -> ramo CQ di mastro
4. EQL è spento, faccio una query non CQ -> errore

Da utente mi aspetterei questo. Comunque lo metto su CQ di default.

**Comment by valeriosantarelli** [comment]
> Io immagino EQL come la possibilità di estendere il linguaggio SPARQL:
> 
> 1. EQL è acceso, faccio una CQ -> ramo CQ di mastro
> 2. EQL è acceso, faccio una query non CQ -> ramo EQL di mastro
> 3. EQL è spento, faccio una CQ -> ramo CQ di mastro
> 4. EQL è spento, faccio una query non CQ -> errore
> 
> Da utente mi aspetterei questo. Comunque lo metto su CQ di default.

Questa era la mia idea originale, però Marco suggeriva una cosa diversa: se si sceglie EQL, la query verrà valutata con EQL (pure se è CQ); se si sceglie CQ, la query viene ovviamente valutata EQ. Forse con il pulsante Toggle così com'è ora, è più intuitivo così, per com'era prima (Full SPARQL on/off) era come dicevi tu.

**Comment by giacomoronconiobda** [comment]
> Ok creo una issue dedicata.
> 
> Riguardo la 7: hai provato facendo girare monolith dal build? Da lì me lo fa sempre, facendolo partire da codice non sempre.

Il server error penso sia in realtà una session expired che si verifica se non si è fatto il logout da monolith e si è riavviato il server. Che faccio nascondo la notifica?

**Comment by valeriosantarelli** [comment]
> > Ok creo una issue dedicata.
> > Riguardo la 7: hai provato facendo girare monolith dal build? Da lì me lo fa sempre, facendolo partire da codice non sempre.
> 
> Il server error penso sia in realtà una session expired che si verifica se non si è fatto il logout da monolith e si è riavviato il server. Che faccio nascondo la notifica?

Ah può darsi. Io il logout non l'ho fatto proprio mai.
Forse si, si può nascondere se la notifica arriva prima che uno ha premuto il pulsante Login.

**Comment by giacomoronconiobda** [comment]
Chiudo che manca solo quella spostata

**Comment by valeriosantarelli** [comment]
questo è un piccolo bug: l'asterisco nel titolo del query tab non compare quando si modifica una query che è appena stata salvata in catalogo. Quindi: 1)aprire un nuovo tab; 2)scrivere una query; 3)salvarla nel catalogo; 4)modificarla -> non compare l'asterisco

Questo è fatto? Mi pare che vedo la stessa situazione di prima...

**Comment by giacomoronconiobda** [comment]
Mi sembrava di averlo risolto, ora lo ricontrollo

Il sab 28 mar 2020, 10:19 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by giacomoronconiobda** [comment]
A me compare l'asterisco. Forse faccio qualcosa di diverso oppure non hai pullato. Puoi ricontrollare e in caso mi mandi un video?

**Comment by valeriosantarelli** [comment]
Eccolo. Ho fatto aggiornamento e pull subito prima di fare la prova.
[asterico.mov.zip](https://github.com/obdasystems/monolith/files/4397262/asterico.mov.zip)

**Comment by giacomoronconiobda** [comment]
E non hai salvato una nuova query ma sovrascritto una query già slavata.

Il giorno sab 28 mar 2020 alle ore 15:14 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by giacomoronconiobda** [comment]
Puoi pullare quando vuoi, ora dovrebbe essere risolto

Il giorno sab 28 mar 2020 alle ore 17:45 Giacomo Ronconi <
ronconi@diag.uniroma1.it> ha scritto:
