### ISSUE TITLE
Tooltip/balloons

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#348]
Riporto qui la discussione riguardo il punto (1) della issue #345 , ovvero:

- la pagina degli Endpoints inizialmente è completamente vuota, e non si capisce bene cosa si deve fare (il pulsante + non è molto evidente). Forse quando non ci sono definiti Endpoints, si potrebbe inserire una scritta nella pagina di qualche tipo (poi pensiamo a definirla bene...)

Il suggerimenti di Fabio sarebbe il seguente:
- quando c'è una lista sempre per forza popolata (ad esempio in Navigation o in Ontology Mappings), fare in modo che una volta scelto un elemento, quando si lascia la pagina (tipo ci si sposta da Ontology a Mappings o SPARQL) e po ci si ritorna, rimane selezionato l'elemento. Come riferimento, anche Protégé e Mobi fanno così ad esempio.
- quando c'è una lista o una pagina che può essere vuota (ad esempio i Denials, gli Endpoints, le Datasources, i mapping di un un elemento, le Ontologie, etc. etc.) mettere, se la lista è vuota, un balloon (tipo quelli nello screenshot sotto) che punta al pulsante +, e dice "Oops, it seems like there are no ______ yet. Click on the Add _____ button to create the first one".
![Schermata 2020-03-27 alle 11 07 00](https://user-images.githubusercontent.com/8250758/77745315-56264d00-701b-11ea-914d-ed4ec038303b.png)

Riguardo questo secondo scenario bisogna trovare una soluzione di compromesso, che ovviamente non è far vedere due due tooltip in hover.
Si potrebbe:
1. far vedere il messaggio riportato sopra alla prima connessione, e poi il tooltip normale dalla seconda volta in poi
2. scrivere qualcosa o mettere un pulsante (elegantemente però) al centro della pagina

**Comment by giacomoronconiobda** [comment]
Ho provato una prima implementazione

**Comment by valeriosantarelli** [comment]
Commento a seconda delle varie pagine che ho visto:

- **Endpoint**: va bene, però toglierei a questo punto l'iconcina a foglia No Elements, che non serve
- **Datasources**: se non ci sono datasources, tanto per non far vedere la pagina vuota, potremmo mettere la scritta Create new datasource con il pulsante + sotto anche qui
- **Denials**: come per Endpoints, togliere il No Elements
- **Navigation/Ontology Mappings**: ci manca un "the"-> Select an entity from **the** entity tree; rimane da implementare il meccanismo che se avevo già selezionato un entity, mi riporta direttamente a quello
- **SQL Views**: ok, manca da implementare il meccanismo che se avevo già selezionato una view, mi riporta direttamente a quello (per questa cosa si può definire una issue a parte se serve)

**Comment by valeriosantarelli** [comment]
Per le pagine di Navigation, Ontology Mappings, e SQL View, è possibile fare queste due cose?
Se la seconda è complicata, si può rimandare alla milestone 0.4, vedi tu.

1) Togliere l'icona No Elements con la foglia
2) Implementare il meccanismo che se avevo già selezionato un Entity/Mapping/View, mi riporta direttamente a quello

**Comment by giacomoronconiobda** [comment]
Per la 2 dovrebbe essere già così se si naviga con il pulsante back

Il gio 16 apr 2020, 22:34 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Si, confermo.

Non navigando col pulsante back è molto più complicato?

**Comment by giacomoronconiobda** [comment]
Scusa ma non capisco come dici. Puoi fare un esempio pratico su books?

Il gio 16 apr 2020, 22:44 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
1. Login 
2. apro ontologia Books
3. dal menu scelgo Navigation
4. apre la sezione Navigation con la parte sinistra con gli alberi e la parte destra vuota
5. scelgo AudioBook, e mi popola la parte destra
6. clicco su SPARQL dal menu e vado sulla pagina delle query (faccio cose lì dentro)
7. clicco di nuovo su Navigation
8. apre la sezione Navigation con la parte sinistra con gli alberi e la parte destra vuota

L'ultimo punto dovrebbe essere "apre la sezione Navigation con la parte sinistra con gli alberi e la parte destra popolata con AudioBook".

**Comment by giacomoronconiobda** [comment]
Questa cosa è complicata, la postporrei alla 0.4.0

**Comment by valeriosantarelli** [comment]
Ok nessun problema, sposta pure alla 0.4.
