### ISSUE TITLE
Cancellazione di una Inclusion

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#353]
La cancellazione di una inclusion non sortisce alcun effetto (nè arrivano segnali di errore da console o server).

**Comment by giacomoronconiobda** [comment]
La chiamata viene fatta in modo corretto ma mi vierne restituito `false`. Chiedo a @roodsey di verificare.

**Comment by roodsey** [comment]
Verificato: il metodo funziona (si veda l'esempio JerseyAPIsTestDeleteInclusion353.java)

**Comment by valeriosantarelli** [comment]
Io continuo a non vedere nessuna reazione da parte del sistema quando premo "ok" sul messaggio di warning dopo aver cliccato sul cestino...
@giacomoronconiobda a te funziona?

**Comment by giacomoronconiobda** [comment]
Sembra che funzioni solo con le inclusion appena create. Penso sia un problema di cache.

**Comment by valeriosantarelli** [comment]
Cancellazioni di inclusioni con ID vengono effettuate correttamente.
