### ISSUE TITLE
Modifica di Versione e descrizione di una specifica di mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#354]
Permettere di modificare la versione e la descrizione di un file di mapping.

Ricordo che abbiamo deciso di far collassare il concetto di ID e di Versione in un unica cosa, che a livello di interfaccia verrà esposta come "Versione", mentre a livello di servizi può continuare a essere chiamata "ID".

La modifica della versione del mapping è necessaria dal momento in cui si permette di fare editing del mapping.

**Comment by giacomoronconiobda** [comment]
Aggiungere la rotta:
`PUT '/owlOntology/' + name + '/version/mapping/' + mappingID`

sulla falsa riga di 
`POST '/owlOntology/' + name + '/version/mapping`

Nota bene che poichè vogliamo anche la possibilità di rinominare cioè cambiare l'ID del mapping il path parm mappingID può essere diverso dal body.

**Comment by roodsey** [comment]
Manca l'indicazione su cosa viene passato nel body

**Comment by giacomoronconiobda** [comment]
Non è il body, ricordavo male. Avevi creato un query param `create` dove c'era l'encoding base 64 dell'oggetto NewMappingFileInfo (come puoi vedere dalla rotta già esistente `POST '/owlOntology/' + name + '/version/mapping`)
