### ISSUE TITLE
Duplicazione di una specifica di Mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#355]
Permettere di duplicare, imponendo un cambio di versione, una specifica intera di mapping.

Questo è utile per scopi di test e di editing, in quanto non prevediamo un meccanismo di salvataggio delle modifiche fatte, quindi potrebbe essere utile fare un backup all'interno del sistema del mapping che si sta modificando.

**Comment by giacomoronconiobda** [comment]
Aggiungere la rotta:
`POST '/owlOntology/' + name + '/version/mapping/' + mappingID + '/duplicate'`

che prende come body ID e descrizione del nuovo mapping e duplica il file identificato da mappingID

**Comment by roodsey** [comment]
Non mi è chiaro cosa aspettarmi in input nel body della chiamata

**Comment by giacomoronconiobda** [comment]
Come la #354, body vuoto e query param `create` dove c'era l'encoding base 64 dell'oggetto NewMappingFileInfo (come puoi vedere dalla rotta già esistente `POST '/owlOntology/' + name + '/version/mapping`)
