### ISSUE TITLE
Interfaccia quarantine dei Mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#357]
Interfaccia per #268 

- [x] Creare due sottovoci del tab Ontology Mappings, chiamati:
--- By Entity (identico a quello che c'è ora, ripristinando "All")
--- All Mappings (elenco piatto dei mapping, con solo campo Search e toggle per quarantenati)

- [x] Per i mapping, creare delle icone per i mapping di concetto, di ruolo, e di attributi. Ad esempio, una M maiuscola, con intersecato, in basso a destra, l'icona dell'entità. Vedi screenshot sotto.

![WhatsApp Image 2020-04-01 at 17 50 34](https://user-images.githubusercontent.com/8250758/78158419-81f16a80-7441-11ea-8f69-69e6719be96a.jpeg)

- [ ] nelle singole card dei mapping, evidenziare in rosso il nome delle viste cancellate (quello evidenziato nello screenshot sotto)

![Schermata 2020-03-31 alle 14 51 11](https://user-images.githubusercontent.com/8250758/78028365-32d30900-735f-11ea-81e0-0240bfb3396e.png)

- [x] prevedere la quarantena per mapping, views, inclusions e denials

**Comment by giacomoronconiobda** [comment]
Per l'ultimo punto bisogna coinvolgere Marco penso.

**Comment by giacomoronconiobda** [comment]
nelle singole card dei mapping, evidenziare in rosso il nome delle viste cancellate (quello evidenziato nello screenshot sotto) -> non ha più senso
