### ISSUE TITLE
[Ontology] ordine delle ontology cards

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#36]
E' necessario determinare l'ordine in cui vengono visualizzate le card delle ontologie (adesso mi pare un pò casuale).
Possibili soluzioni:

- ordine di inserimento (quindi quelle nuove sempre in coda)
- ordine alfabetico
- ordine deciso dall'utente tramite Settings (ma comunque i criteri questi sono...)

**Comment by giacomoronconiobda** [comment]
Aggiungere all'oggetto Ontology anche un campo long creationDate per fare ordinamento su data

**Comment by roodsey** [comment]
Valore aggiunto: ho effettuato una ristrutturazione del repository, una volta deployato il nuovo servizio occorrerà rigenerare il repository da capo.
