### ISSUE TITLE
Drawer editing SQL View

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#360]
- [x] una volta scelto un datasource dal menu a tendina non è più possibile cambiarlo

- [x] il drawer fa il cache le informazioni che scrivo. Ad esempio: scrivo il nome, scelgo il datasource, chiudo il drawer, lo riapro, e il nome è già inserito, e il datasource è già scelto (e non lo posso cambiare, vedi punto prima)

- [ ] se la query SQL non piace al parser, non è possibile definire una Key, nemmeno scrivendocela a mano

**Comment by giacomoronconiobda** [comment]
per la terza non so che fare, se non parsa come facio a sapere qual'è la segnatura della vista?

**Comment by valeriosantarelli** [comment]
Non si può in quel caso disattivare i check sulla form?
Cioè, se la query non piace al parser, io ci posso scrivere qualsiasi cosa nella form, al massimo sarà il server a restituire un errore?

**Comment by giacomoronconiobda** [comment]
Per come sono fatte le risorse non è possibile scrivere qualsiasi cosa. Ovvero per l'interfaccia la definizione di una key è basata sul **nome** della colonna, per il server è basata sulla **posizione**.

L'ultima parte del tuo commento non lo capisco, la definizione della vista (save) dovrebbe funzionare anche se non passa il parser.

**Comment by valeriosantarelli** [comment]
Scusa, intendevo di definire qualsiasi key...

Magari dopo sentiamoci anche con Marco e ragioniamo sul da farsi per questa cosa.

**Comment by giacomoronconiobda** [comment]
ok intanto mi mandi la vista in questione?

**Comment by valeriosantarelli** [comment]
Eccola
[view.txt](https://github.com/obdasystems/monolith/files/4419681/view.txt)

**Comment by giacomoronconiobda** [comment]
Ho trovato questa soluzione, suggerita da Marco:
Le chiavi si possono definire se la query è stata testata anche se l'sql ha degli errori per il parser.

Poi ho scoperto che il parser supporta il casting di postgres ::text ma l'errore è dovuto al fatto che quest'ultimo sta dentro un CASE THEN. Ho aperto una issue sul parser.
