### ISSUE TITLE
Versione di un mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#361]
Avendo fatto collassare il concetto di "versione" con il campo ID che c'era prima, bisognerebbe permettere almeno di utilizzare il carattere "." (il punto) all'interno della versione (al limite con un escape di qualche tipo). Adesso non è possibile.

![Schermata 2020-04-02 alle 12 20 16](https://user-images.githubusercontent.com/8250758/78238148-89198680-74dc-11ea-9eef-6f96795ce54b.png)

**Comment by giacomoronconiobda** [comment]
L'ho già risolta fai pull
