### ISSUE TITLE
[Ontology - Mapping] Visualizzazione di Mapping e SQL Views

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#37]
Ho caricato l'ontologie e mapping di ACI (domain ontology, non Open Data).
I mapping sono definiti per Oracle, e questo sembra dare problemi con il driver quando si cerca di aprire la pagina di un mapping o di una vista.
Probabilmente togliendo la logica della connessione del db dai mapping il problema viene risolto alla base, ma per ora segnalo l'errore restituito.

![Schermata 2019-04-05 alle 16 19 17](https://user-images.githubusercontent.com/8250758/55634714-52bd0480-57bf-11e9-903d-21c305509fc0.png)

**Comment by valeriosantarelli** [comment]
Allego anche ontologia e mapping
[aci_OntologiaMapping.zip](https://github.com/obdasystems/monolith/files/3048347/aci_OntologiaMapping.zip)

**Comment by roodsey** [comment]
L'errore è dovuto alla mancanza del driver JDBC oracle come dipendenza nel servizio deployato su Tomcat

**Comment by roodsey** [comment]
Apportate modifiche ai data source manager: la connessione viene creata solo la prima volta che viene richiesta. Si può usare qualsiasi mapping con qualsiasi driver: si potranno eseguire query solo su DSM con driver caricati come dipendenze.
