### ISSUE TITLE
Segnalazioni varie

### ISSUE THREAD

**Issue by roodsey** [obdasystems/monolith#371]
Lo so che con questo titolo non verrà mai presa in esame, comunque coinvolgo @valeriosantarelli e @giacomoronconiobda per valutare se applicare o no questi facili miglioramenti.

- [x] 1) il fatto che un endpoint sia running è poco evidente (la scritta potrebbe essere affiancata da un segno di spunta VERDE bello grosso
<img width="524" alt="Screenshot 2020-04-04 at 10 32 42" src="https://user-images.githubusercontent.com/20337479/78422780-2e119c00-7662-11ea-9d5b-7f34246e02c7.png">

- [x] 2) Quando si clicca "EDIT" su una SQLView, il pannello che esce è titolato "Add SQL View", potrebbe essere fuorviante
<img width="467" alt="Screenshot 2020-04-04 at 10 40 44" src="https://user-images.githubusercontent.com/20337479/78422796-56999600-7662-11ea-8478-1599265340bf.png">

- [ ] 3) Sarebbe utile avere la possibilità di ispezionare i risultati ottenuti valutando la SQLView sul DB, fin dal pannello di visualizzazione della view. Magari potrebbero anche essere utili informazioni sul numero di record contenuti nella view.
<img width="1505" alt="Screenshot 2020-04-04 at 10 41 25" src="https://user-images.githubusercontent.com/20337479/78422823-88126180-7662-11ea-8846-39e3bc628eff.png">

- [x] 4) il successo del test della connessine dati dovrebbe essere evidenziato con una icona VERDE
<img width="642" alt="Screenshot 2020-04-04 at 11 50 49" src="https://user-images.githubusercontent.com/20337479/78423999-c744b080-766a-11ea-835f-b397702499bc.png">

- [x] 5) la pagina dei valori di default per i parametri di configurazione di Mastro è da riporganizzare in modo da sfruttare meglio lo spazio: attualmente c'è molto spazio "sprecato" che costringe a scrollare per visualizzare tutti i parametri
<img width="1905" alt="Screenshot 2020-04-04 at 11 57 36" src="https://user-images.githubusercontent.com/20337479/78424162-c9f3d580-766b-11ea-90b0-0b1eef1f2ab2.png">

**Comment by valeriosantarelli** [comment]
Il punto 2 l'avevo in effetti notato, poi mi ero dimenticato di evidenziarlo. Sono d'accordo comunque.

Il punto 1 mi pare ragionevole.

Il punto 3 anche secondo me è corretto, nella misura in cui si affianca all'importazione di un limit automatico (tipo le prime 100 tuple) quando si fa il test della query durante la creazione della SQL View.

**Comment by roodsey** [comment]
Ho aggiunto un item e messo le checkbox

**Comment by giacomoronconiobda** [comment]
Il punto 3 non mi è chiaro. Domande:

1. Dove facciamo vedere i risultati? La pagina delle sql view è già molto piena
2. Dovrei fare la chiamata testQuery ogni volta che la pagina viene visitata? Non penso sia auspicabile in termini di performance visto che le query potrebbero essere pesanti.

**Comment by valeriosantarelli** [comment]
> Il punto 3 non mi è chiaro. Domande:
> 
> 1. Dove facciamo vedere i risultati? La pagina delle sql view è già molto piena
> 2. Dovrei fare la chiamata testQuery ogni volta che la pagina viene visitata? Non penso sia auspicabile in termini di performance visto che le query potrebbero essere pesanti.

1) E' possibile prevedere una finestra modale carina che fa vedere i risultati dalla query SQL nella SQL View? In effetti altrove non è chiaro dove mostrarli, c'è già un sacco di roba nella struttura dal componente
2)No no, la chiamata solo a comando: si mette un pulsate Evaluate Query (con icona a piacimento) dove indicato dalla freccia nella issue, e la query viene fatta girare solo se si preme il pulsante.

Ricordo che (a mio parere):

> Il punto 3 anche secondo me è corretto, nella misura in cui si affianca all'importazione di un limit automatico (tipo le prime 100 tuple) quando si fa il test della query durante la creazione della SQL View.

**Comment by giacomoronconiobda** [comment]
Quindi in pratica è uno short-cut per quello che già c'è con edit->test.

A questo punto la domanda è se non è stata selezionata la data source di default?


Per il limite automatico suggerisco apertura nuova issue

**Comment by valeriosantarelli** [comment]
> Quindi in pratica è uno short-cut per quello che già c'è con edit->test.
> 
> A questo punto la domanda è se non è stata selezionata la data source di default?
> 
> Per il limite automatico suggerisco apertura nuova issue

Si, esatto. Per non fare proprio la stessa cosa, suggerivo di introdurre il limit automatico per il Test Query. Così distinguiamo tra "Test Query" e "Evaluate Query".

Secondo me se non è stata selezionata la data source di default si inibisce il pulsante.

Ora apro la nuova issue.

**Comment by giacomoronconiobda** [comment]
Creata issue apposita per il punto 3: #390
