### ISSUE TITLE
Errore visualizzazione Ontology Rewriting e View Rewriting per query EQL

### ISSUE THREAD

**Issue by roodsey** [obdasystems/monolith#372]
A fronte di una query EQL eseguita con successo, l'interfaccia chiede quanto in oggetto usando l'ID della query EQL: le richieste andrebbero fatte per le singole SPARQL tables e l'interfaccia dovrebbe distinguere i risultati indicando da quale SPARQL table provengono le riscritture

<img width="1565" alt="Screenshot 2020-04-04 at 12 20 39" src="https://user-images.githubusercontent.com/20337479/78424584-f0674000-766e-11ea-9ac1-de62e9f58b0a.png">

**Comment by giacomoronconiobda** [comment]
@roodsey esiste una rotta per avere il codice sparql delle sparql tables?
