### ISSUE TITLE
Interruzione esecuzione Query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#373]
La query menzionata nella #369 impiega molto tempo ad essere eseguita (non so quanto, non ho completato l'esecuzione).
L'interruzione della query prima del suo termine sembra avere effetto lato Monolith, ma dal log di Mastro ho riscontrato che per diversi minuti dopo l'interruzione da interfaccia, sono continuati a venire fuori risultati (poi ho stoppato il server).

Dipende dal fatto che la query gira in modalità EQL? Bisogna intervenire sui singoli thread?

**Comment by roodsey** [comment]
Monolith non invia la richiesta "stop" per arrestare le query (smette solo di fare polling)

**Comment by giacomoronconiobda** [comment]
@roodsey specificare il modo di mandare la richiesta "stop" per arrestare la query. Tra i path ho trovato solo `@Path("/endpoint/{name}/query/{queryID}/stop")` ma sembra abbia a che fare solo con le query salvate nel catalogo.

**Comment by roodsey** [comment]
devi usare l'execution id, come sempre del resto
