### ISSUE TITLE
Gestione prefix manager per query EQL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#374]
Credo ci siano ancora dei problemi di gestione del prefix manager, però limitatamente all'esecuzione di query in modalità EQL.

Se ho sia l'ontologia imdb che l'ontologia books caricate dentro Monolith (condividono il prefisso : ), e provo ad eseguire la query all_books, ottengo questo errore:

[[[[[     E Q L     S E R V E R         S T A R T E D     ]]]]]
 -> 
 >>> {query.semantics=eql, expand.sparql.tables=true, advanced.query.mode=true}
 >>> {query.semantics=cq, expand.sparql.tables=true, advanced.query.mode=true}
it.uniroma1.dis.quonto.core.exceptions.OntologyAlphabetException: SPARQL Parser ERROR: cannot find concept symbol Book  (namespace: http://www.movieontology.org/ontology/) in ontology alphabet!
{*} 2020-04-06 21:48:01 [[OBDA_QUERY_RUNNER]] ERROR c.r.m.s.q.OBDAStreamQueryThread - Error setting up query thread: ThrowableType: class it.uniroma1.dis.quonto.core.exceptions.OntologyAlphabetException
	at it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getQuontoConcept(SparqlUCQParser.java:509)
 Message: SPARQL Parser ERROR: cannot find concept symbol Book  (namespace: http://www.movieontology.org/ontology/) in ontology alphabet!
 StackTrace: 
	at it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getAtom(SparqlUCQParser.java:480)
	at it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getBodyAtoms(SparqlUCQParser.java:777)
it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getQuontoConcept(SparqlUCQParser.java:509)
it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getAtom(SparqlUCQParser.java:480)
	at it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getBodyFromPathBlock(SparqlUCQParser.java:428)
it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getBodyAtoms(SparqlUCQParser.java:777)
	at it.uniroma1.dis.mastro.parsers.SparqlUCQParser.parseSparqlUCQ(SparqlUCQParser.java:386)
	at com.ruzzi.mastro.stream.queries.OBDAStreamQueryThread.init(OBDAStreamQueryThread.java:326)
it.uniroma1.dis.mastro.parsers.SparqlUCQParser.getBodyFromPathBlock(SparqlUCQParser.java:428)
it.uniroma1.dis.mastro.parsers.SparqlUCQParser.parseSparqlUCQ(SparqlUCQParser.java:386)

**Comment by roodsey** [comment]
Non si verifica: ho caricato books e imdb, creato ed avviato due endpoint, eseguito query EQL e CQ sia su uno che sull'altro... se riesci, prova a  ricostruire un percorso che generi l'errore, riapri la issue e allega tutto il necessario per riprodurlo

**Comment by valeriosantarelli** [comment]
Ho riprovato ora, e me lo fa sia con Books+imdb, sia con Books+wolf (books, wolf, imdb hanno tutt'e tre il namespace vuoto).
Non credo che l'avvio o meno di altri endpoint influisca, mi da l'errore sia con l'endpoint dell'altra ontologia avviata sia senza.

Può avere senso che ti allego tutta la mia mastro home?

**Comment by roodsey** [comment]
sì

**Comment by valeriosantarelli** [comment]
Eccolo. Riapro, ma se non ti si ripresenta ancora, chiudiamo e mettiamo in quarantena.

[mastro-home.zip](https://github.com/obdasystems/monolith/files/4446285/mastro-home.zip)

**Comment by roodsey** [comment]
Non si presenta

**Comment by valeriosantarelli** [comment]
Ok bene, come anticipato, ho messo la issue in quarantena, se riesce fuori vediamo, altrimenti apposto così.

**Comment by roodsey** [comment]
Ho almeno 4 ontologie (con varie versioni) che hanno tutte il prefisso vuoto, non so cosa altro fare per riprodurre l'errore.

**Comment by valeriosantarelli** [comment]
No no, niente infatti. Lasciamo chiuso.
