### ISSUE TITLE
Errore creazione nuovo mapping

### ISSUE THREAD

**Issue by savo-fabio** [obdasystems/monolith#377]
Specifica di prova: Book ontology. 
SO: Windows 10 

Dal tab Mappings->Ontology Mappings, se si seleziona un predicato e poi il simbolo + per creare un nuovo mapping il sistema riporta il seguente errore: 

"Server Error
Cannot read property 'currentEntity' of undefined"

e porta l'utente in una pagina completamente bianca. Se si aggiorna la pagina il sistema visualizza nuovamente monolith. 

La console non registra alcun errore.

**Comment by valeriosantarelli** [comment]
Replicazione di #378 
Abbiamo riportato lo stesso errore esattamente allo stesso tempo. Chiudo questo.
