### ISSUE TITLE
Errore apertura pagina SPARQL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#379]
All'apertura della pagina SPARQL sulla specifica Wolfoil (in allegato cartella zippata), Monolith (non MWS) restituisce questo errore:

Server Error
Cannot read property 'line' of undefined

Mi rendo conto che l'indicazione è molto vaga, se serve faccio vedere live quando succede così esploriamo Network.

[ONTO_n1110864384.zip](https://github.com/obdasystems/monolith/files/4445740/ONTO_n1110864384.zip)

**Comment by giacomoronconiobda** [comment]
Potresti vedere nella console lo stack e il numero di riga? Grazie

Il mar 7 apr 2020, 18:06 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Eccolo. Aggiungo che succede solo se l'endpoint Wolf è running.

index.js:1446 TypeError: Cannot read property 'line' of undefined
    at prefixFold.js:45
    at getRange (foldcode.js:23)
    at doFold (foldcode.js:38)
    at CodeMirror.foldCode (foldcode.js:85)
    at CodeMirror.yasqe.collapsePrefixes (main.js:115)
    at Object.addPrefixes (prefixUtils.js:20)
    at CodeMirror.yasqe.addPrefixes (main.js:178)

**Comment by giacomoronconiobda** [comment]
L'errore è dovuto al fatto che il mws restituisce 0 prefissi per l'ontologia. Ora faccio il controllo @valeriosantarelli valuta il caso se girare a Marco.

**Comment by valeriosantarelli** [comment]
Non ho capito bene....

L'ontologia ha i seguenti prefissi (mostrati anche dentro Monolith nella pagina Info):


: | http://www.obdasystems.com/wolfoilcompany/
-- | --
owl: | http://www.w3.org/2002/07/owl#
rdf: | http://www.w3.org/1999/02/22-rdf-syntax-ns#
woc: | http://www.obdasystems.com/wolfoilcompany/
xml: | http://www.w3.org/XML/1998/namespace
xsd: | http://www.w3.org/2001/XMLSchema#
rdfs: | http://www.w3.org/2000/01/rdf-schema#

Mi stai dicendo che in pratica nella pagina SPARQL mws non li sta passando?

**Comment by giacomoronconiobda** [comment]
Vedo che hai capito invece!

**Comment by valeriosantarelli** [comment]
Mi pare ci siano tutti i presupposti per #girarearoodsey

@roodsey

**Comment by roodsey** [comment]
Valutare se si vuole aggiungere l'allineamento dei prefissi (fra ontologia e mapping) alle modifiche per la retrcompatibilità
