### ISSUE TITLE
[Ontology] supporto a caratteri speciali

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#38]
Quali caratteri supportiamo ad esempio nelle descrizioni delle ontologie create?
Ho provato a scrivere una descrizione in italiano, ma la a accentata (à) non viene visualizzata correttamente.
![Schermata 2019-04-05 alle 16 27 55](https://user-images.githubusercontent.com/8250758/55635013-ff978180-57bf-11e9-8e78-6b706be4aa0b.png)

**Comment by roodsey** [comment]
Utilizzato encoding di default per il caricamento delle descrizioni
