### ISSUE TITLE
Riavvio dell'endpoint con mapping modificato

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#380]
Le modifiche effettuate su una specifica di mapping non vengono prese in considerazione se si stoppa e si riavvia l'endpoint. Bisogna proprio stoppare il server.

Per replicare:
1) Avviare l'endpoint su IMDB
2) Eseguire la query IMDB1_SPARQLTABLE2
questa esecuzione genererà una query SQL che impiega moltissimo tempo a girare
3) Stoppare l'endpoing e aggiungere alla vista movie_info_view una chiave sui campi movie_id e info_type_id
questa chiave dovrebbe far sì che la query IMDB1_SPARQLTABLE2 produca una query SQL diversa (che termina l'esecuzione subito senza risultati)
4) Riavviare l'endpoint e rieseguire la query IMDB1_SPARQLTABLE2
la query SQL prodotta sarà uguale a quella ottenuta al punto (2)
5) Riavviare il server, riavviare l'endpoint, e rieseguire la query IMDB1_SPARQLTABLE2
la query SQL prodotta sarà quella che impiega pochissimo tempo e non produce risultati

**Comment by roodsey** [comment]
Nonostante la presenza della chiave sulla vista indicata, ottengo comunque la stessa riscrittura SQL:
```
SELECT m_V_00066_1.info, m_V_00080_5.info, c_V_00088_3.person_id FROM movie_info m_V_00066_1, info_type i_V_00066_1, cast_info c_V_00088_3, role_type r_V_00088_3, movie_info m_V_00080_5, info_type i_V_00080_5 WHERE (m_V_00066_1.movie_id = c_V_00088_3.movie_id AND c_V_00088_3.movie_id = m_V_00080_5.movie_id AND i_V_00066_1.info = 'budget' AND r_V_00088_3.role = 'director' AND i_V_00080_5.info = 'gross') AND (m_V_00066_1.info_type_id = i_V_00066_1.id) AND (c_V_00088_3.role_id = r_V_00088_3.id) AND (m_V_00080_5.info_type_id = i_V_00080_5.id)
```
puoi riportare la query SQL che ottieni tu?

**Comment by valeriosantarelli** [comment]
Allora, questo esempio non lo riesco a riprodurre, perchè non capisco bene la query che sta producendo.

Ad ogni modo, ci sono due problemi di caching dei mapping, che si possono testare con un esempio più semplice:

1. sulla specifica Books, eseguire la query select ?x where {?x a :UneditedBook}. Questa query ha un'unica riscrittura, e dà risultati. Cancellare poi l'unico mapping per :UneditedBook, riavviare l'endpoint, e rifare la query. I risultati sono gli stessi, nonostante ora non ci dovrebbe essere alcuna riscrittura.
2. c'è un problema di caching della specifica dei mapping in base al nome. Per replicare: duplicare il mapping di books, e chiamarlo "books_mapping_test". Poi cancellare il mapping per :UneditedBook. Ora cancellare il mapping "books_mapping_test", duplicare di nuovo il mapping di books, e chiamarlo di nuovo "books_mapping_test". Ora il mapping "books_mapping_test" NON avrà il mapping per :UneditedBook.

**Comment by roodsey** [comment]
Ho lavorato sul cache manager e sono riuscito a far percepire a Monolith i cambiamenti (aggiungere mapping, vite e fare modifiche). Occorre ovviamente riavviare l'endpoint per renderle effettive. Viceversa, il problema segnalato da te originariamente sulla query IMDB1_SPARQLTABLE2 non riesco a riprodurlo: in pratica, anche utilizzando un file di mapping che in partenza contiene la chiave sulla vista, la riscrittura SQL che ottengo è la stessa. (owl file version 1.0.0, mapping versione 1.0.1)

**Comment by valeriosantarelli** [comment]
Confermo, ripercorrendo tutt'e due le situazioni evidenziate, non ci sono più problemi.
