### ISSUE TITLE
Richieste dopo stop del server

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#381]
Se si stoppa il server senza fare il logout, Monolith continua a mandare richieste: si viene quindi riportati sulla pagina di login, ma con una serie di errori Server Error che continuano ad arrivare finchè il server non è stato riavviato.

**Comment by giacomoronconiobda** [comment]
Se il server non è raggiungibile mi sembra giusto dare un Network Error

**Comment by valeriosantarelli** [comment]
Ma anche prima di aver fatto il login? 
Non è che sia bellissimo...

**Comment by giacomoronconiobda** [comment]
Be in realtà è l'eccezione network error che ti reindirizza sulla pagina di login: una specie di auto logout. Se non ti piace posso eliminare questa feature e poi devi fare il logout a mano.

**Comment by valeriosantarelli** [comment]
Mi sta anche bene che si venga riportati sulla pagina di login, in modo che si ha percezione dal browser che è successo qualcosa.
Quello che è brutto a vedersi è la comparsa di quella sfilza di errori di connessione. O ne esce fuori uno solo (tipo pgadmin per intenderci), oppure semplicemente non succede nulla a meno che uno non prova a fare il login (tipo graphdb).

Comunque non è urgente, sposto alla 0.4.0.
