### ISSUE TITLE
Errore consultazione risultati query Construct

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#384]
Non so bene come descrivere l'errore che ho riscontrato, quindi, for your viewing pleasure, ho preparato un video (con finale a sorpresa!):

![costructResults](https://user-images.githubusercontent.com/8250758/78888763-9695ba00-7a62-11ea-8ac7-a824ad0386c9.gif)

Da MWS non mi stanno arrivando errori, quindi lo segno come relativo a Monolith.

**Comment by valeriosantarelli** [comment]
Questa la query sulla specifica Superheroes se si vuole provare a replicare:

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX : <http://www.obdasystems.com/demo/superheroes/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sh: <http://www.obdasystems.com/demo/superheroes/#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {$ab a sh:Ability.
    $ab sh:name $ab_name}
WHERE {   
    $ab a sh:Ability.
    $ab sh:name $ab_name   }

**Comment by giacomoronconiobda** [comment]
Penso sia legata alla #383 inoltre la paginazione dei risultati della construct non funziona:
anche se passo pagesize=10 mi ritorna 50 risultati
