### ISSUE TITLE
Limit automatico per il Test Query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#389]
Limitare automaticamente a 100 i risultati prodotti e mostrati dal pulsante Test Query nell'editor di una SQL View.

_Originally posted by @giacomoronconiobda in https://github.com/obdasystems/monolith/issues/371#issuecomment-613545662_

**Comment by giacomoronconiobda** [comment]
Aggiungere un query param `limit` alla rotta:
```
@Path("/datasource/{id}/tables/results")
```

**Comment by valeriosantarelli** [comment]
Solo una domanda: il limit è settato di default a 50 invece che 100 giusto?
Va bene comunque, anche 50 è più che sufficiente.

**Comment by giacomoronconiobda** [comment]
L'ho messo a 100
