### ISSUE TITLE
Evaluate query per una SQL View

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#390]
Introdurre un pulsante nella card di una SQL View che valuta la query sulla datasource di default senza limit. Poichè la query potrebbe essere molto pesante e avrà verosibilmente molti risultati, introdurre un sistema di paging alla chiamata:
```
@Path("/datasource/{id}/tables/results")
```
similmente per quanto avviene già sulla rotta:
```
@Path("/endpoint/{name}/query/{queryID}/results")
```

**Comment by roodsey** [comment]
Questa modifica è superflua: in sostanza stiamo re-implementando un client SQL evoluto. Per fare il tuning delle query delle viste l'utente può utilizzare il client proprietario del DBMS: fare il paging richiede di tenersi i dati in memoria e far girare la query su un thread separato, vale a dure, un appesantimento eccessivo per il server (pensate a query molto generiche su tabelle grandi, che sono le prime che vengono fatte). Credo che la limit sia sufficiente
