### ISSUE TITLE
Esecuzione query su mapping creati dentro Monolith

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#394]
Il tentativo di eseguire una query SPARQL su una specifica di Mapping generata da zero dentro Monolith genera l'errore in fondo a questo messaggio.

[Archivio.zip](https://github.com/obdasystems/monolith/files/4491826/Archivio.zip)

Ovviamente nel file di mapping non è presente il tag "dataSource".

La query che si può provare è la seguente:

```
select ?x ?y
where {?x <http://www.obdasystems.com/wolfoilcompany/kTypeNumber> ?y}
```
e la datasource è quella di Wolf ovviamente.

FATAL ERROR!!!
ThrowableType: class java.lang.RuntimeException
Message: Using NoDatabaseDataSourceManager: you need to set the datasource name!
StackTrace: 
it.uniroma1.dis.quonto.mapping.impl.NewJdbcGeneralMappedEvaluationResult.<init>(NewJdbcGeneralMappedEvaluationResult.java:92)
it.uniroma1.dis.mastro.api.generalInterfaces.unfolderProcessor.UnfolderProcessor.process(UnfolderProcessor.java:136)
com.ruzzi.unfold.mastro.MastroStreamSQLEngine.run(MastroStreamSQLEngine.java:545)
java.lang.Thread.run(Thread.java:745)

**Comment by roodsey** [comment]
Impossibile verificare causa #398
