### ISSUE TITLE
[Ontology] aspetto

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#4]
- [x] Il pulsante Add Ontology è brutto che si sposti in continuazione a seconda di quante ontologie sono attualmente definite nel sistema. E' necessario trovare una posizione fissa in alto o in basso nella pagina

- [ ] Download dell’ontologia: utilizzare il nome dell’ontologia (eventualmente nome+versione) invece sempre di ontology.owl

- [x] Togliere i bordi bianchi ai pulsanti (in particolare quello tratteggiato su Add Ontology è un pò fastidioso)

**Comment by giacomoronconiobda** [comment]
Marco vedi tu il punto 2?

**Comment by roodsey** [comment]
No, a livello di repository dei file è preferibile avere sempre lo stesso nome (in effetti ogni versione ha la sua cartella). In fase di download, monolith restituirà un file che si chiama come l'ontologia (la versione continua ad essere espressa all'interno del file)

**Comment by roodsey** [comment]
@valeriosantarelli non posso riassegnare la issue: questa va passata a @giacomoronconiobda

**Comment by valeriosantarelli** [comment]
Riassegnata a @giacomoronconiobda
