### ISSUE TITLE
Interfaccia caricamento nuovo catalogo

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#406]
Related to #400 

Implementare una interfaccia che permetta all'utente di scegliere se il caricamento di un nuovo catalogo di query deve andare in aggiunta o in sostituzione alle query già presenti.

Ovviamente la richiesta deve essere fatta all'utente solo se nel catalogo sono già presenti delle query.

**Comment by giacomoronconiobda** [comment]
Come descritto nel commit https://github.com/obdasystems/monolith/commit/9d3778f90f67a7e4bdc0d533c93080880edf5eaa

Questa cosa è già stata fatta. Per il futuro: le descrizioni dei commit con cui chiudo le issue sono abbastanza parlanti quando si tratta di enhancements

**Comment by valeriosantarelli** [comment]
Si può aggiungere un pulsante "Cancel" alla finestra modale?
Altrimenti non è possibile uscire dalla finestra modale senza aver scelto una delle due opzioni (magari per qualsiasi motivo uno decide di tenersi il catalogo così com'è).
