### ISSUE TITLE
Triple restituite dai servizi per query construct

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#408]
In caso di query CONSTRUCT, le triple restituite dai servizi sono incomplete. Ne manca in pratica sempre una.
@NonnonePalmiro ha verificato che l'esecuzione della query lato Mastro avviene in modo corretto, e produce il numero giusto di risultati.
Inoltre, il numero di risultati conteggiati alla fine dell'esecuzione è corretto, semplicemente una tripla non viene mandata.

Inoltre, questa problematica si è venuta a creare successivamente al 15 Aprile, ovvero quando è stata rilasciata su Drive la versione 0.2.2 di Monolith stesso.

Per fare una verifica, si può lanciare questa query sulla specifica Books:

`construct {?x :name ?nome.
        ?y :editedBy ?x.}
Where { ?x a :Editor.
        ?x :name ?nome.
        ?y :editedBy ?x.
        ?z :hasEdition ?y.
         }`

Dovrebbe restituire 56 triple, ma ne arrivano a Monolith solamente 55 (abbiamo verificato insieme a @giacomoronconiobda e @NonnonePalmiro ).

**Comment by roodsey** [comment]
Coinvolgo @NonnonePalmiro in quanto l'errore pare essere circoscritto al motore di query construct.
Più precisamente, la tripla mancante non viene restituita a monte dal manager delle query construct: a scopo di esempio si utilizzi l'esempio com.ruzzi.unfold.mastro.test.TestIssue408 (in mastro-gui-api/src/test/java) avendo cura di specificare nel file di mapping collegato all'esempio la connessione ad un database contenente la tabella che segue:
```
create table triples (
sub varchar(255),
prd varchar(255),
obj varchar(255))

insert into triples values ( 
'<http://example.org/sub/1>',
'<http://example.org/prd/1>',
'<http://example.org/obj/1>')
```
Si noterà che la prima query standard restituisce una tupla, mentre la "gemella" construct ne restituisce zero.

**Comment by roodsey** [comment]
Verificato con esempio via codice ed esempio via monolith
