### ISSUE TITLE
Concetto non presente in ontology hierarchy

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#41]
Nella specifica [aci.zip](https://github.com/obdasystems/monolith/files/3054954/aci.zip) il predicato `aci:Stato_di_veicolo` non è presente nella risposta alla chiamata:

`https://obdatest.dis.uniroma1.it:8080/mws/rest/mwsx/owlOntology/ACI%20Domain%20Ontology/version/hierarchy?version=NO_VERSION_PROVIDED`

**Comment by roodsey** [comment]
Io lo vedo...

**Comment by valeriosantarelli** [comment]
Riapro, incollo sotto degli screenshot per dare ulteriore evidenza del problema di alcune entity che mancano dall'albero.

Nel primo screenshot si vede che nella pagina di Navigation del concetto Entita_non_avente_stati sono riportate diverse subclasses, mentre nel secondo screenshot si vede che nell'Entity tree ne viene riportata solo una.

L'ontologia è ACI Domain Ontology:
Ontology IRI: http://www.aci.it/ontology
Ontology Version IRI: NO_VERSION_PROVIDED

![screenshot1](https://user-images.githubusercontent.com/8250758/55914918-a462f600-5be8-11e9-9284-b6c70ccc268c.jpeg)

![screenshot2](https://user-images.githubusercontent.com/8250758/55914926-aaf16d80-5be8-11e9-867a-0fa4aa762af3.jpeg)
