### ISSUE TITLE
Errore visualizzazione di Navigation per ACI Open Data

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#414]
L'apertura della pagina Navigation sull'ontologia ACI Open Data, caricata con il file .graphol, produce l'errore che riporto qui sotto:

TypeError: Cannot read property 'toLowerCase' of null
(anonymous function)
src/pages/components/FastSearchTree.js:45
  42 | }
  43 | 
  44 | return arr.sort(function (a, b) {
> 45 |   var x = a.label.toLowerCase();
     | ^  46 |   var y = b.label.toLowerCase();
  47 |   if (x < y) { return -1; }
  48 |   if (x > y) { return 1; }
View compiled
SearchTree.convertData

**Comment by giacomoronconiobda** [comment]
Quale rendering stai utilizzando?

Il mer 22 apr 2020, 19:24 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
EntityPrefixIRI
