### ISSUE TITLE
Ontology Rewriting per ASK hanno SPARQL sbagliato

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#415]
Non viene applicato il syntax highlighting per le query SPARQL prodotte dall'Ontology Rewriting in caso di query con forma ASK.

![Schermata 2020-04-23 alle 10 35 49](https://user-images.githubusercontent.com/8250758/80077766-3caaef00-854e-11ea-8006-9054c697351b.png)

**Comment by giacomoronconiobda** [comment]
- non è una construct ma una ASK
- Fallisce il parser perchè la query SPARQL è sbagliata (nelle riscritture
la select non ha variabili)



Il giorno gio 23 apr 2020 alle ore 10:36 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by valeriosantarelli** [comment]
Eh, io ho scritto ASK infatti, dove hai letto CONSTRUCT?? Don't drink and post!

Sul secondo punto infatti stavo notando proprio questo, e mi chiedo se possa essere il motivo dei problemi che stiamo avendo con le query construct.

**Comment by giacomoronconiobda** [comment]
valeriosantarelli changed the title Syntax Highlighting per Ontology Rewriting di Construct Syntax Highlighting per Ontology Rewriting di ASK 3 hours ago

**Comment by valeriosantarelli** [comment]
Questa issue è in sostanza catturata dalla issue https://github.com/obdasystems/mastro/issues/9
Chiudo quindi questa.
