### ISSUE TITLE
Inibire query CONSTRUCT + EQL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#419]
Finchè non viene risolta questa issue: https://github.com/obdasystems/mastro/issues/12

Inserire un controllo da interfaccia che stoppa l'esecuzione in caso di scelta di esecuzione in modalità EQL di query CONSTRUCT.

Esporre un messaggio del tipo "EQL query execution for CONSTRUCT query forms not supported."

Ovviamente se non supportiamo queste query, non ha proprio senso passarle a Mastro.

**Comment by giacomoronconiobda** [comment]
Se l'utente è in modalità basic non è possibile fare questo controllo. Forse è il caso che venga fatto lato servizi e venga lanciata un eccezione apposita.
