### ISSUE TITLE
Eliminare endpoint all'eliminazione di una versione, mapping o datasource

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#422]
Attualmente un endpoint viene eliminato solo se viene cancellata tutta l'ontologia a cui fa riferimento.

Bisogna prevedere la cancellazione anche se viene eliminata la versione dell'ontologia, il mapping, o la datasource a cui fa riferimento.

**Comment by giacomoronconiobda** [comment]
Penso vadano risolti come nel primo caso che è stato già risolto lato beckend.

**Comment by valeriosantarelli** [comment]
Magari sarebbe carino mettere un warning quando si sta facendo la cancellazione in caso di endpoint che è definito sull'oggetto che si sta cancellando. Questo penso vada previsto front-end @giacomoronconiobda

**Comment by roodsey** [comment]
Aggiunte le seguenti rotte:
```
GET /endpoints/referencing/owlOntology/{name}/version
GET /endpoints/referencing/owlOntology/{name}/version/mapping/{ID}
GET /endpoints/referencing/datasource/{name}
```
che restituiscono rispettivamente gli endpoint che fanno riferimento a
- ontologia 'name'
- ontologia 'name', versione (query param) 'version' 
- ontologia 'name', versione (query param) 'version', mapping 'ID' 

Da utilizzare per produrre il warning sugli endpoint collegati a fronte dell'eliminazione di una ontologia, versione o mapping

**Comment by roodsey** [comment]
> Magari sarebbe carino mettere un warning quando si sta facendo la cancellazione in caso di endpoint che è definito sull'oggetto che si sta cancellando. Questo penso vada previsto front-end @giacomoronconiobda

Riaggiungo @giacomoronconi per aggiungere il messaggio di warning
