### ISSUE TITLE
Modifica di un mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#423]
Sto provando a modificare il mapping che segue (mapping della data property :title della specifica Books):

SELECT book_view.code AS code,
  book_view.title AS title 
FROM book_view 
WHERE book_view.title IS NOT NULL 

eliminando la condizione dentro la WHERE. Quindi farlo diventare così:

SELECT book_view.code AS code,
  book_view.title AS title 
FROM book_view 

Però quando premo il pulsante Submit, non succede nulla. Semplicemente mi fa vedere il mapping com'era prima.
Il server non mi restituisce alcun errore, e nemmeno la console.

**Comment by roodsey** [comment]
In effetti il monolith continua a mostrare la vecchia query SQL, ma la chiamata REST sottostante restituisce correttamente la query modificata.
Probabilmente si tratta di un problema di refresh.
Coinvolgo @giacomoronconiobda per un'analisi dettagliata.

![image](https://user-images.githubusercontent.com/20337479/80945150-75b74f00-8deb-11ea-90ce-1cabf76eaf26.png)

**Comment by giacomoronconiobda** [comment]
@roodsey la query da te evidenziata nello screen è quella relativa alla vista, il problema è nell'oggetto `bip`. Nel tuo screen si vede che c'è ancora is not null

**Comment by roodsey** [comment]
Questo di seguito è il JSON che viene passato come body della PUT:
```
[
  {
    "currentEntity": {
      "entityIRI": "http://www.obdasystems.com/books/title",
      "entityID": "DL_1",
      "entityPrefixIRI": ":title",
      "entityRemainder": "title",
      "entityLabels": [],
      "entityType": "DATA_PROPERTY"
    },
    "iri": {
      "shortIRI": "obda:m_book_title_1",
      "extendedIRI": "http://www.obdasystems.com/mappings/m_book_title_1"
    },
    "mappingDescription": null,
    "id": "m_book_title_1",
    "mappingBody": {
      "viewAtoms": [
        {
          "name": "book_view",
          "terms": [
            "code",
            "title",
            "type"
          ],
          "view": {
            "sqlViewHead": [
              "code",
              "title",
              "type"
            ],
            "sqlViewID": "book_view",
            "sqlViewDescription": null,
            "sqlViewCode": "SELECT bk_code as code, bk_title as title, bk_type as type\nFROM tb_books",
            "quarantineReasons": null,
            "quarantined": false
          }
        }
      ],
      "bip": [
        {
          "name": "IS_NOT_NULL",
          "terms": [
            "title"
          ],
          "view": null
        }
      ]
    },
    "template": {
      "template": "http://www.obdasystems.com/books/book-{code}",
      "terms": [
        "code"
      ]
    },
    "rangeTemplate": {
      "template": "title",
      "terms": []
    },
    "quarantineReasons": null,
    "quarantined": false
  }
]
```

**Comment by giacomoronconiobda** [comment]
Non riesco a riprodurre il bug. Quando cancello la where dal body il campo `bip` viene passato `null`. Ci possiamo sentire su skype così cerchiamo di capire che succede?
