### ISSUE TITLE
Campi null nelle pagine della documentazione

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#425]
Alcuni campi degli oggetti restituiti nella parte relativa la navigazione dell'ontologia (quelli che hanno `/logical` nel path del metodo) risultano null. Non è chiaro se bisogna considerare questi null liste vuote o ancora non sono stati implementati. In particolare:

- Disjoint Unions per le classi
- Inverse Properties per le object properties

**Comment by roodsey** [comment]
In effetti i campi non venivano popolati. Ho provveduto.
Effettuando delle prove, ho riscontrato delle singolarità: il pannello di visualizzazione delle disjoint unions, visualizza tali assiomi in modo strano e parziale. Strano perché gli assiomi vengono visualizzati come una lista verticale (cosa succederebbe se ce ne fosse più d uno?). Inoltre la visualizzazione è parziale, come se mancasse un elemento della union.
A titolo di esempio si può utilizzare l'ontologia in
```
./src/test/resources/individuals/Untitles.owl
```
Dallo screenshot si notano le singolarità:
![image](https://user-images.githubusercontent.com/20337479/81096007-1437d300-8f06-11ea-919b-18d7f0d86a0b.png)

Di seguito il JSON di descrizione della classe "Persona", in cui si vede che le classi nella disjoint union sono 3:
```
{
...
"disjointUnions": [
[
{
"entityIRI": "http://www.semanticweb.org/mr/ontologies/2020/4/untitled-ontology-26#Calabrese",
"entityID": "CL_2",
"entityPrefixIRI": ":Calabrese",
"entityRemainder": "Calabrese",
"entityLabels": [],
"entityType": "CLASS"
},
{
"entityIRI": "http://www.semanticweb.org/mr/ontologies/2020/4/untitled-ontology-26#Cane",
"entityID": "CL_4",
"entityPrefixIRI": ":Cane",
"entityRemainder": "Cane",
"entityLabels": [],
"entityType": "CLASS"
},
{
"entityIRI": "http://www.semanticweb.org/mr/ontologies/2020/4/untitled-ontology-26#Cinese",
"entityID": "CL_5",
"entityPrefixIRI": ":Cinese",
"entityRemainder": "Cinese",
"entityLabels": [],
"entityType": "CLASS"
}
]
]
}
```
Coinvolgo @giacomoronconiobda
