### ISSUE TITLE
Messaggio di errore per KG già esistente

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#426]
Attualmente se si prova a creare un nuovo KG inserendo una IRI già esistente, il sistema restituisce questo errore:

-------------------  E R R O R      S T A R T  -------------------------
java.lang.RuntimeException: Directory /Users/valeriosantarelli/mastro-home/kg/KG_625885747 already exists!
	at com.mwsx.engine.MwsxOntologyManager.addKnowledgeGraph(MwsxOntologyManager.java:408)
	at com.mwsx.services.MwsxKGService.post__knowledgeGraphs(MwsxKGService.java:102)
~[classes/:na]

E' possibile mettere un riferimento più chiaro all'IRI del KG che si è tentato di costruire?
Ad esempio " Knowledge Graph with IRI ....... already exists!"

**Comment by giacomoronconiobda** [comment]
Metto il controllo io prima della POST, come già faccio per ontologie query etc
