### ISSUE TITLE
Metrica Annotations per gli Individuals

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#427]
La metrica Annotations per gli Individuals non viene popolata (immagino sia una fix analoga a quanto fatto per disjoint unions nelle classi e inverse nelle obj properties).

![Schermata 2020-05-07 alle 11 05 14](https://user-images.githubusercontent.com/8250758/81275952-a8af4c00-9052-11ea-8df5-3095165ab88e.png)

**Comment by roodsey** [comment]
Il mio pannello si popola: quale versione stai utilizzando? Sai dirmi qual'è la chiamata REST che dovrebbe restituire cose e non lo fa?
![image](https://user-images.githubusercontent.com/20337479/81298575-3c920f80-9075-11ea-8239-d8cba05679d3.png)

**Comment by valeriosantarelli** [comment]
Si, il pannello in generale si popola, ma la voce "Annotations" no, mi pare anche nello screenshot tuo.

La chiamata è la GET di questa rotta: 
`Request URL: http://localhost:8989/mws_war/rest/mwsx/owlOntology/IMDBMovieOntology/version/alphabet/individual/IND_223/logical?version=NO_VERSION_PROVIDED
` 
e in particolare individualDescriptions ritorna vuoto (ti allego lo screenshot sotto).

![Schermata 2020-05-07 alle 15 36 23](https://user-images.githubusercontent.com/8250758/81301194-048ccb80-9079-11ea-8a75-64bdf21aa30f.png)

**Comment by roodsey** [comment]
Quell'informazione in realtà è ridondante: le annotazioni sono memorizzate nella entity che rappresenta l'individuo (analogamente a quanto avviene per classi e proprietà). Sarebbe una ridondanza: la vogliamo replicare?
![image](https://user-images.githubusercontent.com/20337479/81303888-98ac6200-907c-11ea-9f68-72a0faf94f23.png)

**Comment by valeriosantarelli** [comment]
Forse no... @giacomoronconiobda che ne pensi?

**Comment by roodsey** [comment]
In ogni caso, non ho problemi a duplicarle, ma a questo punto utilizzerò lo stesso oggetto, ovvero Label, in modo da avere anche l'informazione sulla lingua, come per la entity

**Comment by roodsey** [comment]
A proposito di individuals segnalo un paio di aggiustamenti:
19 La tabella degli assiomi (che contiene anche il conteggio degli assiomi sugli individui) andrebbe essere riproporzionata 
![image](https://user-images.githubusercontent.com/20337479/81307127-9815ca80-9080-11ea-9a53-2e8e6c00e6d0.png)
2) il pannellino delle metriche non contiene l'informazione sul numero di individui
![image](https://user-images.githubusercontent.com/20337479/81307597-2427f200-9081-11ea-918e-03fd806dda33.png)

**Comment by giacomoronconiobda** [comment]
Ok per il ridimensionamento. Per quanto riguarda la seconda ho notato che dentro l'oggetto `OntologyVersion` ci sono in realtà tutti gli individui forse è il caso di sostituire questa informazione con un count come nel caso di `classes`

```
ontologyDate: 1588255600496
ontologyDescription: null
ontologyID: "INAIL"
ontologyOwner: {name: "santaroni", roles: [{name: "ADMIN", permissions: [{domain: "*", action: "*", id: "*"}]}]}
ontologyVersions: [{ontologyID: "INAIL", versionID: "1.0", versionDescription: [], versionDate: 1588699116235,…}]
0: {ontologyID: "INAIL", versionID: "1.0", versionDescription: [], versionDate: 1588699116235,…}
catalog: {,…}
graphol: true
individualInfos: {individualInfos: [{,…}, {,…}, {,…},…]}
numAxioms: 1001
numClasses: 180
numDataProperties: 69
numObjectProperties: 54
ontologyID: "INAIL"
versionDate: 1588699116235
versionDescription: []
versionID: "1.0"
versionOwner: {name: "root", roles: null}
name: "root"
```

**Comment by roodsey** [comment]
Ho già aggiunto la metrica sugli individui (la troverai per le nuove ontologie, essendo un dato persistente su disco). Le informazioni sugli individui invece per il momento le lascio dove sono, piuttosto che creare un nuovo file separato (come per le classi e le proprietà). Se riterremo necessario separarlo, a fronte di evidenti necessità di prestazioni, lo separeremo, magari in una milestone futura.
![image](https://user-images.githubusercontent.com/20337479/81314579-9270b280-9089-11ea-8dfe-03133fd95511.png)
