### ISSUE TITLE
Anagrafica User

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#428]
Related to #194 

Censimento delle informazioni da raccogliere per ciascun utente:

- Nome
- Cognome
- Email
- Username
- Password

Ce ne sono altre?

Queste informazioni devono essere quindi gestite dalla tabella degli utenti (e quindi nel drawer di aggiunta di un nuovo User), e devono essere mostrate nel tab User dentro la pagina Settings per ciascun utente.
Nel tab User prevederei di lasciare a ciascun utente la possibilità di modificare la propria password.

**Comment by giacomoronconiobda** [comment]
Mock up completato

**Comment by roodsey** [comment]
Rotte aggiunte al webservice:
![image](https://user-images.githubusercontent.com/20337479/81555955-c4d02780-9389-11ea-8c71-7570f5e6f6e6.png)
