### ISSUE TITLE
Breadcrumb non cliccabile

### ISSUE THREAD

**Issue by roodsey** [obdasystems/monolith#429]
Sarebbe opportuno rendere gli elementi del breadcrumb cliccabili con relativa redirezione alla pagina corrispondente, altrimenti la sua presenza è poco utile

![image](https://user-images.githubusercontent.com/20337479/81283979-cc2bc400-905d-11ea-9b6e-34b7d7a8107e.png)

**Comment by giacomoronconiobda** [comment]
Non mi è chiaro qual'è la pagina corrispondente per ogni elemento. Il breadcrumb è stato introdotto per dire all'utente quale cosa è attualmente aperta; nel tuo caso il mapping `books_mapping` della versione `.../1.0` dell'ontologia BOOKS.

**Comment by valeriosantarelli** [comment]
Per come interpreto io il breadcrumb, sarebbe:
- (primo livello) Ontologia 
- (secondo livello) Versione dell'ontologia -> pagina Info della versione (ad esempio http://localhost:3000/#/open/ontology/Books/1.0/info/)
- (terzo livello) Mapping di quella versione -> pagina Info dei mapping (ad esempio http://localhost:3000/#/open/ontology/Books/1.0/mapping/books_mappings/info)

**Comment by giacomoronconiobda** [comment]
Quindi in pratica la stessa cosa di cliccare su info nei menù di ontologia e mapping?

**Comment by valeriosantarelli** [comment]
Secondo me si.
