### ISSUE TITLE
Gestione Info Utenti

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#432]
La logica della creazione/modifica/cancellazione di utenti e info degli utenti dovrebbe funzionare così:

- un utente Admin, dalla pagina Users, può aggiungere o cancellare un utente. Nel caso dell'aggiunta, imposta le informazioni dell'utente, in particolare username ed email obbligatoriamente, nome e cognome opzionalmente. **Non può assegnare la password**. La password infatti viene generata sinteticamente ed inviata all'email dell'utente al momento della creazione dello stesso. Poi l'utente può decidere se cambiarla o no. L'amministratore inoltre assegna all'utente uno o più ruoli **(da valutare se prevedere che dovrebbe esistere in qualsiasi momento uno ed un solo utente con ruolo ADMIN)**
- un utente Admin, dalla pagina Users, per un utente già esistente (compreso se stesso), può modificare solamente i ruoli a lui assegnati **(se non ci sono già altri ADMIN però non può togliersi il ruolo di ADMIN...)**
- un utente (di qualsiasi tipo) dal tab **User della pagina Settings** può modificare le proprio informazioni personali, **inclusa la password**. La password può essere modificata indicando quella vecchia e quella nuova, e può essere resettata attraverso sempre un invio tramite email, tramite un pulsante "Reset Password". Ovviamente dopo aver premuto il pulsante reset password, si viene sconnessi dall'applicazione, quindi serve una finestra di warning.

In pratica l'utente Admin crea, cancella, e assegna ruoli a utente. Ciascun utente però si gestisce le proprie informazioni personali.

Inoltre, riguardo la gestione dei ruoli:

- il ruolo **ADMIN** dovrebbe essere di default con privilegi * su dominio, azione, e risorsa. Questo ruolo non dovrebbe poter essere nè modificato nè eliminato (eventualmente si potrebbe proprio non mostrare tra i ruoli, è cablato dentro il sistema).

Vi sembra ragionevole?

Altrimenti ho paura che si possano creare delle situazioni incontrollabili...

**Comment by giacomoronconiobda** [comment]
se l'utente si dimentica la password non ha modo di riavere il suo utente se non facendolo  cancellare e ricreare dall'ADMIN invece che assegnargli una password che poi può essere cambiata

**Comment by roodsey** [comment]
La password andrebbe generata in modo sintetico e inviata via mail all'utente: in sostanza l'admin non deve mai poter loggarsi a nome di un altro, cosa invece potrebbe fare se assegna lui la password all'utente

**Comment by roodsey** [comment]
Ovviamente la logica di reset ed invio della password deve essere fatta da MWS, non da Monolith. Se @valeriosantarelli mi invia i parametri della webmail di obdasystems (quelli che ha utilizzato Manuel per Jenkins, per intenderci), inizio a predisporre la funzionalità lato server

**Comment by valeriosantarelli** [comment]
> La password andrebbe generata in modo sintetico e inviata via mail all'utente: in sostanza l'admin non deve mai poter loggarsi a nome di un altro, cosa che invece potrebbe fare facilmente se assegna lui la password all'utente che l'ha dimenticata

Eh si, esatto. Si potrebbe prevedere un pulsante "Regenerate password" che crea una password random e la manda direttamente tramite mail all'utente, così l'admin non la vede mai. Poi se l'utente la vuole, la cambia.

In generale, dovremmo cercare di fare cose non eccessivamente sofisticate, ma nemmeno che la prima azienda a cui lo diamo ci dice che dobbiamo rivedere le politiche di gestione degli utenti altrimenti non la possono usare.

**Comment by valeriosantarelli** [comment]
> Ovviamente la logica di reset ed invio della password deve essere fatta da MWS, non da Monolith. Se @valeriosantarelli mi invia i parametri della webmail di obdasystems (quelli che ha utilizzato Manuel per Jenkins, per intenderci), inizio a predisporre la funzionalità lato server

Per jenkins manuel mi aveva fatto creare un account apposito, faccio lo stesso con monolith?

**Comment by valeriosantarelli** [comment]
Anzi, forse meglio direttamente per mws...

**Comment by roodsey** [comment]
Ho collaudato ricezione / invio di email dall'indirizzo MWS tramite java, tutto funziona a dovere. Per gestire correttamente le password degli utenti provvederò a eliminare il dato sulla password dalla struttura dati dell'utente e la inserirò in un file a parte, a cui si accederà separatamente dai dati anagrafici dell'utente. L'amministratore potrà procedere al reset della password di ogni utente, e la nuova password verrà inviata via mail all'indirizzo presente nella struttura dati dell'utente. Questo indirizzo email, viceversa, sarà modificabile solo ed esclusivamente dal proprietario. Più avanti dovremo mettere in piedi il meccanismo di validazione dell'indirizzo email, come avviene di consueto. 
Cosa da tenere a mente: le email inviate in modo automatico finiscono quasi sempre nella cartella SPAM: questo problema non è facilmente aggirabile, poiché le impostazioni delle cartelle SPAM cambiano da provider a provider, e la cosa migliore è che l'utente configuri la sua cartella spam in modo da considerare "fidati" i messaggi provenienti da mws@obdasystems.com. Di questo occorrerà fare menzione nella documentazione.

**Comment by giacomoronconiobda** [comment]
Torna prepotentemente la issue #59 ! Da notare la rassegnazione nelle parole di valerio

**Comment by valeriosantarelli** [comment]
@roodsey @giacomoronconiobda modifico la issue con quanto deciso nella call di oggi.

**Comment by giacomoronconiobda** [comment]
Ok, @roodsey avvisami quando posso togliere la password dalla form degli admin

**Comment by giacomoronconiobda** [comment]
Forse è il caso di prevedere una rotta apposita per il cambio di password invece di lasciarla incapsulata nella rotta dell'utente. Che ne dici @roodsey ?

**Comment by roodsey** [comment]
Ho spostato le passwd fuori dall'oggeto "User": la prossima volta che fate update, cancellate il file "mastro.permissions" dalla MASTRO_HOME. Per semplicità, ho previsto la possibilità di impostare la password sui nuovi utenti mediante un parametro di query "secret" alla POST sugli User (la password va passata in hash md5 uppercase). Se il parametro non viene passato, la password viene generata automaticamente dal sistema e, per il momento, stampata a schermo (in attesa di integrare il codice per l'invio delle email, la recuperiamo dal log).

E' stata anche aggiunta la rotta per il reset della password di un utente
PUT /user/{username}/passwd?secret=<hash-md5-uppercase>

**Comment by giacomoronconiobda** [comment]
Forse è il caso di aggiungere un'altro param con la vecchia password per contro verificarla prima di modificare la password (come diceva Valerio)

**Comment by roodsey** [comment]
Parametro aggiunto
```
PUT /user/{username}/passwd?secret=<hash-md5-uppercase>&oldSecret=<hash-md5-uppercase>
```

**Comment by giacomoronconiobda** [comment]
Manca la rotta per resettare la password

**Comment by valeriosantarelli** [comment]
Questa issue mi pare si possa chiudere, ne creo una apposita per la gestione dei filtri, e poi eventuali bug o altre considerazioni li mettiamo in issue dedicate.
