### ISSUE TITLE
Inibire modifica ruoli Admin

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#434]
Non credo sia ragionevole poter togliere ad un amministratore il ruolo di Admin.
Io inibirei questa funzionalità.

Se lo facciamo poi dobbiamo gestire la situazione più complessa di garantire che ci sia sempre almeno un amministratore, sennò non si capisce bene cosa succede.

**Comment by giacomoronconiobda** [comment]
Mi sembra strano perchè poi non si può nemmero cancellare un utente amministratore. Un amministratore è per sempre!?

**Comment by valeriosantarelli** [comment]
Eh si, io pensavo proprio di non permettere, almeno da interfaccia, di eliminare un amministratore.
Mi pare un casino gestirlo, e non credo abbiamo le idee chiare su quali dovrebbero essere le politiche per farlo: un amministratore ne può cancellare un altro? Può cancellare se stesso? Che succede se si rimane senza amministratori?

Non credo valga la pena in questo momento mettersi nelle condizioni di doversi porre queste domande...

**Comment by giacomoronconiobda** [comment]
Forse l'amministratore non è un ruolo ma un utente

**Comment by giacomoronconiobda** [comment]
Poi il ruolo admin è in realtà uno che può fare tutto ma non necessariamente l'amministratore
