### ISSUE TITLE
Ruolo ADMIN

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#436]
Per la gestione dell'amministratore, la proposta di Giacomo è la seguente:

- prevedere di default un **utente** ADMIN (credenziali admin/admin), che sarà l'unico utente noto al sistema al momento del primo avvio (dobbiamo quindi rimuovere mastro/mastro e santaroni/ronconelli)
- questo utente sarà l'unico che avrà visibilità della pagina degli users, quindi sarà l'unico vero e proprio amministratore del sistema
- lui potrà creare utenti/ruoli/privilegi etc. etc., eventualmente dando anche */*/* a qualche altro utente, ma in ogni caso non potrà dare privilegi sulla pagina di Users
- il Dominio Users quindi deve essere tolto da quelli assegnabili, e l'accesso alla pagina degli Users va gestito vedendo non il ruolo ma l'utente
- l'utente admin/admin non sarà modificabile nè cancellabile, quindi non verrà proprio mostrato dentro l'elenco degli Users, saranno solo visibili le sue informazioni nella pagina User, da cui potrà ad esempio modificare l'email

@giacomoronconiobda fammi sapere se quanto riportato coincide con la tua idea.
@roodsey che ne pensi? Ti sembra che ci siano dei problemi che non stiamo al momento vedendo nell'adottare questa soluzione?

L'alternativa a questo è mettere in piedi dei meccanismi (tipo quelli suggeriti nella issue #434 ) che impediscano di creare una situazione in cui non esiste un amministratore nel sistema.

**Comment by roodsey** [comment]
Problemi non direi: in generale quando si sceglie di blindare qualcosa, al massimo, potrebbe capitare di doverci rimettere poi le mani per allentare la restrizione. Per me non ci sono problemi.

**Comment by roodsey** [comment]
In uno scenario reale, "admin" dovrebbe anche poter cambiare la password (dubito sia accettabile che rimanga fissa per sempre, vista l'importanza del ruolo).

**Comment by valeriosantarelli** [comment]
Si, io pensavo la stessa cosa: se in qualche contesto specifico non è sufficiente avere un solo amministratore, oppure si vuole usare qualcosa di diverso da admin/admin, si può fare ad-hoc.

**Comment by giacomoronconiobda** [comment]
Secondo me il nome admin è giusto che sia fisso. La password dell'admin può essere cambiata come ogni altro utente.

**Comment by valeriosantarelli** [comment]
Ok, allora facciamo che può cambiare la password dell'utente admin.

**Comment by valeriosantarelli** [comment]
Tolgo il tag question allora, visto che siamo in accordo su come procedere.
