### ISSUE TITLE
Aggiungere Permessi alla pagina dell'User

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#437]
Al momento nella pagina dell'User vengono specificati i suoi Ruoli.
Questo informazione però non è molto utile, perchè l'utente (non amministratore) non ha modo di capire a cosa corrispondono quei ruoli (nell'immagine sotto, a cosa corrisponde il ruolo "Reader"?).

Si potrebbero aggiungere i permessi legati al ruolo indicato per l'utente.

![Schermata 2020-05-22 alle 17 19 48](https://user-images.githubusercontent.com/8250758/82685358-5a09d080-9c54-11ea-8349-11b073ca92bf.png)

**Comment by giacomoronconiobda** [comment]
Vogliamo mettere un popup sul ruolo che spiega i permessi?
