### ISSUE TITLE
Pagina di mapping vuota per predicati che non hanno mapping definiti

### ISSUE THREAD

**Issue by roodsey** [obdasystems/monolith#44]
Quando nella pagina dei mapping si seleziona un predicato che non ha mapping definiti, la pagina rimane vuota: dovrebbe invece mostrare il nome del predicato (come avviene quando i mapping sono presenti) e riportare un messaggio del tipo "non ci sono mapping".
![Schermata da 2019-04-12 12-44-39](https://user-images.githubusercontent.com/20337479/56031916-0de62000-5d21-11e9-896d-186bccf4f0e5.png)
La riporto come BUG perché l'utente ha l'impressione che l'applicativo non stia funzionando.

**Comment by valeriosantarelli** [comment]
Avevo segnalato questo problema nella issue #18 , ma in effetti va bene evidenziarlo indipendentemente, e come bug. Modifico l'altra issue togliendolo da lì, e aggiungo anche la milestone (0.1).
