### ISSUE TITLE
Caratteri usati nel nome di una View

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#440]
Al parser dei mapping non piace il carattere "-" utilizzato nel nome di una View.
Se lo uso il parser rileva un errore SQL, e non sono poi più nemmeno in grado di definire un template correttamente, perchè il tasto "+" non funziona.

O non si permette di usare quel carattere (e altri caratteri che potrebbero dare fastidio) nei nomi delle viste, oppure si fa in modo che il parser SQL non impedisca di procedere quando trova un carattere di quel tipo.

Prima di effettuare modifiche, verificare se si riesce a replicare il comportamento, perchè magari sto sbagliando qualche altra cosa io. In caso lo vediamo insieme.

**Comment by giacomoronconiobda** [comment]
Chiaramente la cosa migliore è evitare caratteri strani, metto il controllo
nella form.

Il mer 27 mag 2020, 17:27 Valerio Santarelli <notifications@github.com> ha
scritto:
