### ISSUE TITLE
Completamento automatico dei template

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#442]
Domanda: attualmente c'è qualche meccanismo di completamento automatico dei template?
Non riesco a capire se quello che vedo è l'autocomplete di monolith oppure del browser.

**Comment by giacomoronconiobda** [comment]
Del browser. Non c'è l'autocompletamento lato monolith. Forse andrebbe
previsto...

Il mer 27 mag 2020, 17:49 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
O l'autocomplete, oppure permettere di cliccare su uno dei template dentro l'elenco nel menu Help.

Insomma, qualsiasi soluzione che non imponga di scriverli a mano per forza.

Cambio da domanda a enhancement.

**Comment by giacomoronconiobda** [comment]
Già c'è l'elenco in help!

Il mer 27 mag 2020, 18:10 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Si, ma non sono cliccabili. Devo fare copia/incolla, oppure lo devo riscrivere a mano. Non è proprio eccezionale...
