### ISSUE TITLE
Template mostrati

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#443]
Nel file di mapping in allegato vedo questi template, e non capisco come mai alcuni hanno le x dentro i placeholder, e altri gli underscore. Non dovrebbero essere tutti underscore?

Il mapping è creato da zero dentro Monolith, però ho copiato dentro una porzione di mapping che avevo creato dentro Protégé. Può dipendere da quello?

http://www.istat.it/esempio/Accatastamento-{x0}{x1}{x2}{x3}
http://www.istat.it/esempio/ParticellaCatastale-{x0}
http://www.istat.it/esempio/ProprietaUI-{_}{_}{_}{_}
http://www.istat.it/esempio/SubalternoCatastale-{x3}
http://www.istat.it/esempio/UnitaImmobiliare-{_}
http://www.istat.it/esempio/UnitaImmobiliare-{x0}

[Archivio 2.zip](https://github.com/obdasystems/monolith/files/4689938/Archivio.2.zip)

**Comment by giacomoronconiobda** [comment]
Penso sia un problema di quando vengono aggiunti i template direttamente nella creazione di un mapping assertion. Coinvolgo @roodsey
