### ISSUE TITLE
Errore creazione mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#449]
Forse collegato a #448 

Se provo a creare questo mapping:

<img width="850" alt="Schermata 2020-05-28 alle 00 34 44" src="https://user-images.githubusercontent.com/8250758/83079099-5bcffb80-a07b-11ea-88ce-ea6fd136d6d3.png">

il risultato che ottengo (sbagliato, perchè è stato proprio rimosso un elemento dalla select) è questo:

<img width="814" alt="Schermata 2020-05-28 alle 00 35 21" src="https://user-images.githubusercontent.com/8250758/83079120-6ab6ae00-a07b-11ea-93d0-1647208b31b6.png">

se provo a fare edit del mapping, questo è quello che viene fuori:

<img width="854" alt="Schermata 2020-05-28 alle 00 35 44" src="https://user-images.githubusercontent.com/8250758/83079145-799d6080-a07b-11ea-8245-b92ca47493b6.png">

In allegato la specifica per provare a ricreare l'errore, non so per quale motivo avviene qui e non per altri mapping.

[Archivio 4.zip](https://github.com/obdasystems/monolith/files/4692182/Archivio.4.zip)

**Comment by giacomoronconiobda** [comment]
Non sembra presentarsi dopo aver fissato il #448
