### ISSUE TITLE
[Ontology - Mapping] Passare alla sintassi SQL per i Mapping Rewriting

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#45]
Passare dalla sintassi basata su Viste alla sintassi SQL per i Mapping Rewriting.

**Comment by roodsey** [comment]
L'unfolding di alto livello viene ora mostrato in SQL, manca però la formattazione.

**Comment by roodsey** [comment]
![image](https://user-images.githubusercontent.com/20337479/71918003-af4fb480-3181-11ea-87bf-8ce653a1da7a.png)
