### ISSUE TITLE
Aggiungere Query SQL dei Mapping al file di mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#452]
Scrivere direttamente dentro il file dei mapping la query SQL che l'utente scrive in un mapping, in modo da poterla poi mostrare da interfaccia quando la richiede.
Quindi l'interfaccia passa al server sia l'SQL che la traduzione in Datalog.

Ad esempio ( in qualsiasi altro modo si preferisce nell'XML:

```
        <ontologyPredicateComplexMapping id="m_edited_by_1">
            <sqlQuery>Qui ci va il testo della query SQL esattamente come l'utente lo scrive</sqlQuery>
            <role string="http://www.obdasystems.com/books/editedBy">
                <domainTemplate>http://www.obdasystems.com/books/edition-{code}</domainTemplate>
                <rangeTemplate>http://www.obdasystems.com/books/editor-{id}</rangeTemplate>
            </role>
            <viewAtomsConjunction>
                <viewAtom>IS_NOT_NULL(edt)</viewAtom>
                <viewAtom>edition_view(code,type,date,edt,id,bk_id)</viewAtom>
            </viewAtomsConjunction>
        </ontologyPredicateComplexMapping>
```

**Comment by roodsey** [comment]
Elemento XML aggiunto: il nome deve essere "userQuery"

**Comment by roodsey** [comment]
Manca adeguamento della struttura dati lato Monolith

**Comment by giacomoronconiobda** [comment]
Sembra che la POST non abbia effetto sugli oggetti restituiti dalla GET mappingsByEntity.

Inoltre penso che questa cosa dell'SQL andrebbe estesa anche ai template (nel caso in cui non si usa l'alias delle colonne) altrimenti potrebbero vedersi dei mapping non consistenti.

**Comment by valeriosantarelli** [comment]
La query viene scritta correttamente dentro il file di mapping, ma questo non sembra aver nessun effetto al momento di visualizzare il mapping scritto.

Continuo a vedere il mapping con la segnatura sostituita con X0, etc. (questo sia usando alias nel mapping che non usandoli; nella vista ho usato alias).

Di seguito screenshot del mapping scritto e poi di quello visualizzato.

![Schermata 2020-06-09 alle 10 35 56](https://user-images.githubusercontent.com/8250758/84125755-5096ab80-aa3d-11ea-9a98-e2882cc2dffc.png)
![Schermata 2020-06-09 alle 10 36 22](https://user-images.githubusercontent.com/8250758/84125759-51c7d880-aa3d-11ea-9af7-37aaf9edf6a4.png)

**Comment by giacomoronconiobda** [comment]
Non riesco a riprodurre l'errore in develop. Penso sia stato risolto

**Comment by valeriosantarelli** [comment]
Io continuo a vederlo, non mi sta facendo differenza tra master e develop.
Se serve facciamo una prova live. 

In generale poi dovrei avere delle indicazioni precise su qual'è l'ambiente in cui fare il test delle issue chiuse (immagino sempre develop, giusto?).

**Comment by giacomoronconiobda** [comment]
Ho mergiato develop in master, richiudo la issue
