### ISSUE TITLE
Loop infinito per query Special Editions

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#455]
La query "special_editions_S_CQ" della specifica Books eseguita da Monolith non termina, sembra entrare in un loop infinito.
Da Protégé ci mette pochi secondi a produrre risultati.

La specifica è questa in allegato (solita specifica Books).

[Archivio.zip](https://github.com/obdasystems/monolith/files/4724381/Archivio.zip)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8250758/83656041-5ca6e700-a5bf-11ea-87ab-eab99c6082ea.gif)

**Comment by roodsey** [comment]
Ho caricato la tua specifica ed eseguito la query, che ha funzionato regolarmente (restituisce 6 risultati in 6 secondi circa). Unica nota di stranezza: non sono riuscito a caricare il catalogo che hai allegato alla issue, se non dopo averlo adattato a mano (la struttura del JSON non risultava compatibile). Prova ad entrarci in debug, in caso facciamoci una sessione skype insieme e vediamo

![image](https://user-images.githubusercontent.com/20337479/83730806-e4d1ce80-a649-11ea-8d30-6d03d45764b1.png)

**Comment by valeriosantarelli** [comment]
Modificando il file logback utilizzato, la query in effetti termina.
Sembra che i tempi siano dovuti all'eccessivo logging che veniva fatto sulla mia installazione.

Per ora chiudo, se riemerge qualcosa valutiamo.
