### ISSUE TITLE
[Ontology] User ontologies

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#46]
E' necessario trovare un meccanismo per regolare il comportamento del sistema quando una ontologia viene eliminata, ma non dall'utente attualmente loggato. Se questo succede, è possibile incorrere in situazioni come quelle dello screenshot sottostante: nel sistema risulta una sola ontologia, ma l'utente vede 5 "working ontologies".

<img width="959" alt="Schermata 2019-04-15 alle 16 29 38" src="https://user-images.githubusercontent.com/8250758/56141357-f4510c80-5f9c-11e9-9074-eb65bd02aac5.png">

Il sistema si comporta correttamente se è l'utente a cancellare l'ontologia: tutte le versioni dell'ontologia vengono cancellate dalle working ontologies.

La prima domanda è: le ontologie che vengono mostrate all'utente sono solo quelle caricate dall'utente attualmente loggato, oppure sono quelle che sono state caricate da tutti gli utenti loggati ad una particolare istanza di Mastro?
Da questo probabilmente dipende il comportamento atteso dal sistema.

Per il momento assegno a @giacomoronconiobda e @roodsey così se serve ragioniamo insieme su una soluzione.

**Comment by giacomoronconiobda** [comment]
Il bug non sussiste più in quanto non esiste più il concetto di "ontologia aperta"
