### ISSUE TITLE
mapping assertion ID

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#472]
Mentre facevo un mapping ho sbagliato l'entità da mappare ma me ne sono accorto dopo averlo salvato. 

Il mapping ID generato automaticamente era `entityA_0`. Per correggerlo ho fatto una **PUT** sullo stesso ID mappando però l'entità `entityB`. Quando successivamente ho mappato `entityA` il sistema ha generato un errore perchè il mapping ID generato automaticamente era `entityA_0` poichè `entityA` ha 0 mapping ma c'è un mapping di `entityB` che ha quell'ID.

Forse l'approccio di mettere l'entità nell'ID non è il massimo sarebbe meglio un semplice contatore secondo me.

**Comment by valeriosantarelli** [comment]
Un contatore mi pare inutile: quando si apre la pagina di tutti i mapping, non divisi per entità, si avrà un elenco di mapping tipo 1,2,3,4,5, ed è impossibile individuare quello che si vuole consultare.

Il problema mi pare piuttosto che quando è stata fatta la PUT del mapping sull'entità B, non è stato automaticamente modificato l'ID del mapping da entityA_0 a entityB_0 (ovviamente qualora l'entità B avesse avuto altri mapping, sarebbe stato più alto il numero del contatore).
Dato che non è l'utente a inserire l'id del mapping ma il sistema a farlo, lui può tranquillamente modificarlo senza generare confusione a livello di utilizzo.

Per inciso, non so nemmeno se sia il caso di iniziare la numerazione da 0 oppure da 1...per me sarebbe meglio da 1.

**Comment by giacomoronconiobda** [comment]
Inutile non è, forse è poco decifrabile dall'utente. La domanda è: **perchè un utente deve scegliere il mapping dall'ID?**

Forse vuole controllare una cosa su un mapping specifico che già conosce (per l'appunto di cui conosce l'ID) quindi basterebbe mettere l'informazione dell'ID del mapping tra i Mapping By Entity

Per quanto riguarda il cambio dell'ID automatico ora provo avedere se funziona.

**Comment by valeriosantarelli** [comment]
Si, dicevo inutile per quanto riguarda l'utente, ovviamente per il sistema no, è un modo come un altro per distinguerli.

Il punto è che se non c'è un id significativo, la schermata di scelta dei mapping "All Mappings" non è utilizzabile, perchè il menu è un elenco di item non distinguibili.
Però questo è l'unico menu in cui, ad esempio, è possibile vedere subito quali sono i mapping in quarantena; in generale poi avere un posto dove c'è l'elenco di tutti i mapping mi sembra possa avere un senso (magari sbaglio).
