### ISSUE TITLE
[Ontology - Endpoint] Supporto a query Construct

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#61]
Aggiungere supporto alle query construct, con produzione dei risultati in formato RDF (varie sintassi solite).

Le triple prodotte dalla query possono essere visualizzate in formato tabellare nell'area delle risposte o semplicemente con una colonna (una riga per triple), o (meglio) a tre colonne (soggetto-predicato-oggetto).

In prima istanza si potrebbe semplicemente far produrre il file RDF richiesto da scaricare, ma prima o poi una visualizzazione (anche solo una preview) delle risposte generate è il caso di implementarlo.

La scelta della sintassi RDF da usare possiamo inserirla nell'Endpoint oppure in Settings, vediamo come viene meglio.

Assegno a Giacomo, Marco, e Lorenza (quest'ultimo per il supporto lato backend), poi vedete voi.

**Comment by roodsey** [comment]
Aggiunte le rotte seguenti (con significati analoghi a quelli delle rotte "query"):
/owlOntology/{name}/version/mapping/{mapID}/cquery/start
/owlOntology/{name}/version/mapping/{mapID}/cquery/{queryID}/start
/owlOntology/{name}/version/mapping/{mapID}/cquery/{queryID}/results
/owlOntology/{name}/version/mapping/{mapID}/cquery/{queryID}/status

Le query del catalogo contengono ora un campo "isConstruct" per discriminare il tipo di query.
A livello di catalogo non c'è differenza nella gestione di query con o senza construct, ma quando si avvia una query il sistema ne controlla il tipo prima di avviare l'esecuzione.
