### ISSUE TITLE
[Knowledge Graph] Aggiungere un Ontologia ad un Knowledge Graph

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#62]
Implementazione dell'area dei Knowledge Graphs, in modo analogo a quanto fatto per le Ontologie.

Funzionalità principali:
- [x] Creazione di un nuovo KG (per i metadati da gestire vedere mock-up)
- [x] Popolamento di KG esistenti con risultati di una query oppure con importazione di triple da dataset esterni
- [x] Download di un KG in RDF (sintassi da scegliere)
- [x] Eliminazione di KG
- [x] Navigazione dei dati di un KG (anche solo in una forma preliminare)
- [ ] Aggiunta di una ontologia al KG (se tale implementazione è semplice, altrimenti si sposta ad un milestone successivo)

**Comment by roodsey** [comment]
Su questo fronte i servizi sono completi, mi rimuovo dalla issue.

**Comment by giacomoronconiobda** [comment]
Il servizio per importare i risultati di una query OBDA manca.
La delete mi restituisce 415 unsupported media type (sto passando una String come da pecifica)

**Comment by roodsey** [comment]
quale rotta delete resrtituisce 415?

**Comment by giacomoronconiobda** [comment]
Questa

delete__knowledgeGraph | /knowledgeGraph | javax.ws.rs.core.Response | DELETE | java.lang.String

**Comment by roodsey** [comment]
> Questa
> 
> delete__knowledgeGraph | /knowledgeGraph | javax.ws.rs.core.Response | DELETE | java.lang.String

il servizio si aspettava un JSON nel body, quindi la stringa avresti dovuto passarla in JSON, vale a dire, fra virgolette. Ho cambiato il "consumed" media-type: ora dovtebbe andare liscio senza mettere la stringa in formato JSON

**Comment by valeriosantarelli** [comment]
Che fai @giacomoronconiobda , chiudi e apri le finestre? Fai prendere aria?

**Comment by giacomoronconiobda** [comment]
Non mi ero accorto che mancavano delle check box

**Comment by roodsey** [comment]
Aggiunta di ontologia a KG credo vada posposto a dopo ISWC.
Pertanto, per ora il mio compito qui è finito.

**Comment by valeriosantarelli** [comment]
Sposto l'ultima checkbox ad una issue dedicata e chiudo

**Comment by giacomoronconiobda** [comment]
Manca la risorsa per aggiungere un Ontologia ad un Knowledge Graph

**Comment by giacomoronconiobda** [comment]
Duplicato della #139
