### ISSUE TITLE
[Ontology - Mappings] Mapping Version

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#66]
Related to #67 

Aggiungere Mapping Version alle informazioni mostrate sulla card, e al drop-down menu all'avvio di Mastro.
Così si evita una situazione come quella sotto (uno è mapping version 1.0 e uno mapping version 1.0.2).

<img width="1031" alt="Schermata 2019-05-02 alle 19 02 22" src="https://user-images.githubusercontent.com/8250758/57089385-035deb80-6d0d-11e9-99d1-38518781cec7.png">

<img width="651" alt="Schermata 2019-05-02 alle 19 05 05" src="https://user-images.githubusercontent.com/8250758/57089526-4750f080-6d0d-11e9-97ef-bbb200d4a8a9.png">

**Comment by giacomoronconiobda** [comment]
Quello che si vede in quel menu è l'ID del mapping che dovrebbe essere univoco. Dobbiamo capire se è necessario fare lo stesso discorso delle ontologie (nome + versione) anche per identificare i mapping

**Comment by valeriosantarelli** [comment]
Si, esattamente. Guarda issue #67

**Comment by valeriosantarelli** [comment]
La mia impressione è che la cosa più corretta sarebbe quella di utilizzare come identificatore la coppia (id, versione). Questo per omogeneità con le ontologie, e per praticità.
Immaginandosi uno scenario di lavoro, è improbabile che i mapping per una specifica, e.g., "ACI", avranno come ID qualcosa di diverso da "ACI", mentre potrebbero variare nella versione.

Comunque, in attesa di risolvere questo dubbio (che è più relativo alla issue #67 ), possiamo lasciare così com'è. Al limite poi ci torniamo sopra.
