### ISSUE TITLE
[Ontology - Mappings] Mapping identifier

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#67]
Related to #66 

E' necessario determinare l'identificatore di una specifica di mapping. O si introduce la versione, ed è quindi la coppia (nome,versione), oppure se è come mi pare sia ora, cioè solo il nome, bisogna introdurre una verifica al momento dell'inserimento di un nuovo file di mapping che non ci sia già un mapping con lo stesso nome. 
Ad esempio:
attenzione, c'è già un mapping con lo stesso nome.
- Opzione 1: cambia il nome del mapping che stai inserendo
- Opzione 2: sovrascrivi il vecchio mapping

(cosa analoga dovrebbe succedere per una versione di una ontologia)

Se così non è si creano comportamenti anomali (per esempio ho tre mapping con nome uguale e versione diversa, clicco delete su uno, e li cancella tutti).

**Comment by roodsey** [comment]
Implementato meccanismo di errore che impedisce di caricare due file di mapping con lo stesso ID: per il momento eviterei di introdurre il concetto di versione di mapping.
