### ISSUE TITLE
[Ontology - Mapping] Database info

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#69]
Bisogna modificare il comportamento della card per farsi dalle le info corrette (forse mancano risorse e servizi?)

<img width="520" alt="Schermata 2019-05-04 alle 08 50 45" src="https://user-images.githubusercontent.com/8250758/57174674-24c4f180-6e4b-11e9-94e2-31dbcda34dd3.png">

**Comment by giacomoronconiobda** [comment]
Non capisco la issue

**Comment by valeriosantarelli** [comment]
Per la sorgente "test" sono definite URL, user e password. Queste info però non vengono visualizzate, dice invece "No JDBC xxx provided".

**Comment by giacomoronconiobda** [comment]
Quello che viene visualizzato è quello che restituisce il server. Coinvolgo Ruxi

**Comment by roodsey** [comment]
Chiaramente appena @giacomoronconiobda fiuta il rischio di dover lavorare, chiama subito in ballo altri soggetti... Ma veniamo a noi, che è meglio...

Il comportamento potrebbe essere giusto: caricando un file di mapping senza info sul DB, ma solo con il riferimento alla data source (da leggere dal catalogo delle data sources), il sistema non trova JDBC info nel file di mapping e riporta "No JDBC xxx provided". Se vogliamo visualizzarli, occorre andarli a prendere dal catalogo delle sources, ma non lo farei direttamente, piuttosto, permetterei con apposito link di accedere alle info del catalogo delle data sources.
Lato servizi, quindi funziona tutto, ma non chiudo la issue: la giro a @giacomoronconiobda per aggiungere il link alla data source.
