### ISSUE TITLE
[Ontology - Documentation] Entity tree

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#7]
- [x] L’albero delle entità così è molto triste: è necessario trovare delle icone carine/colorate, oppure semplicemente qualche colore, da associare almeno a classi, ruoli, attributi

- [x] Valutiamo l’idea di riportare l’albero come menu sulla sinistra. 
Allo stato attuale la pagina inizialmente è quasi completamente vuota, e, oltre ad essere non bella, non si capisce immediatamente cosa si debba fare. Riportandolo sulla sinistra e tenendolo almeno parzialmente espanso, si riempie la pagina, e si è più portati a fare qualcosa. Inoltre il layout con 3 menu già c’è in Endpoint, e non è brutto.
Ovviamente al limite si può fare collassabile il menu con l'albero dentro.

In generale pagine molto vuote possono indurre un senso di smarrimento per un utente non esperto, quindi è bene evitarle.

- [ ] Togliere owl:Thing dall'albero delle entità

**Comment by roodsey** [comment]
@valeriosantarelli e @giacomoronconiobda questa issue non è di mia competenza: rimuovetemi dagli assegnatari

**Comment by valeriosantarelli** [comment]
@giacomoronconiobda diceva che l'eliminazione di owl:Thing dall'Entity Tree (punto 3 della checklist della issue...forse si vede poco, avrei potuto fare una issue a parte) fosse di competenza del back-end.
