### ISSUE TITLE
Etichetta tipologia predicati nell'albero dei predicati 

### ISSUE THREAD

**Issue by savo-fabio** [obdasystems/monolith#70]
@valeriosantarelli @giacomoronconi 

Nell'albero dei predicati "Ontology Entities" nella pagina Documentations "Class", "Object Properties" e "Data Properties" dovrebbero essere evidenziati in qulche modo per distinguerli dalle vere entità. Possiamo provare Grassetto più il colore scelto per il predicato?

**Comment by giacomoronconiobda** [comment]
Al momento abbiamo usato le icone di protege web per distinguere Class Object Properties e Data Properties. Avevamo provato con @valeriosantarelli diversi colori ma non ci paicevano.

**Comment by valeriosantarelli** [comment]
Credo che il punto della issue fosse che potrebbe essere il caso di evidenziare solamente "Classes", "Object Properties" e "Data Properties", così a colpo d'occhio subito si differenziano dalle entità dell'ontologia.

Ho fatto una prova con il colore e bold per i concetti (non posso evidenziare solo "Classes" modificando solamente il css credo), comunque viene così. Ovviamente il colore è opinabile, e va pensato scritto solo sul nodo Classes.

<img width="1243" alt="Schermata 2019-05-21 alle 22 57 04" src="https://user-images.githubusercontent.com/8250758/58130379-2b5db200-7c1c-11e9-8425-443b773cbd50.png">

Non so, devo dire che al momento non c'è una soluzione che mi convince del tutto nell'albero.

Forse però utilizzare il colore invece dell'iconcina dentro le pagine di Navigation non è male:

<img width="1195" alt="Schermata 2019-05-21 alle 23 02 13" src="https://user-images.githubusercontent.com/8250758/58130551-8db6b280-7c1c-11e9-8bf6-87debca62444.png">
