### ISSUE TITLE
[Ontology - Navigation] Assiomi nelle card

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#71]
Non vengono visualizzate le entità o espressioni equivalenti nella card Equivalent Classes.

Esempi (con riferimento l'ontologia ACI Open Data v1.0.3 attualmente caricata.

- Concetto "Stato"
Assiomi coinvolti:
EquivalentClasses(aci:Stato ObjectSomeValuesFrom(ObjectInverseOf(aci:ha_stato) owl:Thing))
EquivalentClasses(aci:Stato DataSomeValuesFrom(aci:inizio rdfs:Literal))
SubClassOf(aci:Stato aci:Entita_non_avente_stati)
ObjectPropertyRange(aci:determina_stato aci:Stato)
ObjectPropertyDomain(aci:est_predecessore aci:Stato)
ObjectPropertyRange(aci:est_predecessore aci:Stato)
ObjectPropertyRange(aci:ha_stato aci:Stato)
DataPropertyDomain(aci:fine aci:Stato)
DataPropertyDomain(aci:inizio aci:Stato)
SubClassOf(aci:Stato_corrente aci:Stato)
SubClassOf(aci:Stato_di_luogo aci:Stato)
SubClassOf(aci:Stato_di_veicolo aci:Stato)
SubClassOf(aci:Stato_rappresentato aci:Stato)

Assiomi visualizzati:
<img width="1001" alt="Schermata 2019-05-07 alle 10 57 59" src="https://user-images.githubusercontent.com/8250758/57287073-07945b00-70b7-11e9-8088-d17539e48330.png">

- Concetto "Agevolazione"
Assiomi coinvolti:
EquivalentClasses(aci:Agevolazione DataSomeValuesFrom(aci:effetto_sul_dovuto rdfs:Literal))
EquivalentClasses(aci:Agevolazione DataSomeValuesFrom(aci:tipo_di_agevolazione rdfs:Literal))

Assiomi visualizzati:
<img width="1023" alt="Schermata 2019-05-07 alle 11 01 17" src="https://user-images.githubusercontent.com/8250758/57287271-77a2e100-70b7-11e9-848d-303071979d3e.png">

**Comment by roodsey** [comment]
In realtà quello che non viene visualizzato sono le espressioni (nei casi di equivalent classes citati ci sono sempre delle espressioni, non classi semplici). 
Riguardo le espressioni di dominio invece, la risorsa "ClassInfo" non prevede la memorizzazione di informazioni sulle tipizzazioni di dominio e range di proprietà: occorre decidere come procedere. Lato interfaccia, sembrano esserci solo i riquadri per mostrare le partecipazioni obbligatorie.

**Comment by valeriosantarelli** [comment]
Ma intendi tutte le espressioni? Perché in caso affermativo non è così, le espressioni le vedo in generale (sotto screenshot a testimonianza). Forse sono solo le espressioni che non si vedono tra le equivalent classes?

Re: tipizzazioni e partecipazioni. Attualmente la politica che stiamo seguendo è questa: nelle card delle Classi, nei riquadri "Object Properties" e "Data Properties" vengono visualizzate solo le partecipazioni obbligatorie; nelle card delle Object Properties e Data Properties, nei riquadri "Domain" e "Range" vengono mostrate le tipizzazioni.
Forse rileggendo la segnalazione poteva essere fuorviante, relativamente alle espressioni di dominio e range è giusto che non vengano fatte vedere nello screenshot. Il problema è legato solo ed esclusivamente alle equivalent classes.

(In generale la filosofia che stiamo cercando di perseguire è di trovare una associazione 1:1 tra tipo di assioma OWL e riquadro in cui viene mostrato, per questo la politica spiegata sopra riguardo tipizzazioni e partecipazioni).

<img width="931" alt="Schermata 2019-06-11 alle 19 22 54" src="https://user-images.githubusercontent.com/8250758/59292977-751b4480-8c7e-11e9-986d-dfcf6d001459.png">

**Comment by roodsey** [comment]
Sì, parlavo delle espressioni per quanto riguarda le equivalent (e credo anche le disjoint) classes. Provvedo a fissare questa parte.

**Comment by valeriosantarelli** [comment]
Mi pare tutto ok.
