### ISSUE TITLE
[Ontology] OWL Rendering

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#73]
Sarebbe utile (soprattutto ai fini di debugging, ma anche in generale), prevedere una nuova funzionalità all'interno dell'area Ontology in cui visualizzare gli assiomi OWL dell'Ontologia.

In pratica come il tab Functional Syntax Rendering di Protégé: sarebbe "semplicemente" la lista di assiomi OWL che compongono l'ontologia.

Eventualmente si potrebbe pensare di introdurre delle funzionalità più interattive di filtri (su tipo di assioma, sulle entity coinvolte, etc.)

Sarebbe in sostanza il "gemello" della voce Graphol (la chiamerei proprio OWL infatti), e si potrebbe, nei casi in cui non è presente la versione Graphol dell'ontologia, invece che un messaggio di errore (quello nello screenshot sottostante), prevedere una finestra di dialogo che rimanda proprio a questa voce (l'OWL c'è sempre ovviamente).

<img width="816" alt="Schermata 2019-05-07 alle 10 22 12" src="https://user-images.githubusercontent.com/8250758/57288170-488d6f00-70b9-11e9-85fc-206d53245791.png">

**Comment by roodsey** [comment]
Ho bisogno che @giacomoronconiobda delinei le rotte necessarie

**Comment by giacomoronconiobda** [comment]
```
@Path("/owlOntology/{name}/version/owl")
@GET
@Produces("application/json")
@Consumes("application/json")
@MwsxAvailable
public Response get__owlOntology_name_version_owl(@Context HttpServletRequest request, @Context HttpServletResponse response, @PathParam("name") String name, @QueryParam("version") String version)```
Che restituisce una lista di `OWLAxiom`. Proverei proprio a usare l'oggetto delle OWLAPI o se non risulta serializzabile cercare di prendere il più possibile da quello.

**Comment by roodsey** [comment]
Un'istanza della classe OWLAxiom è intrinsecamente non serializzabile in JSON (ogni assioma ha dentro di se il riferimento all'ontologia e questa contiene ovviamente il riferimento allo stesso assioma). Per fare un lavoro completo occorre ridefinire la rappresentazione del modello degli assiomi OWL mediante oggetti POJO, ma questa operazione è molto lunga.
Nell'immediato è viceversa molto più agevole mostrare nella schermata citata da @valeriosantarelli il contenuto del file OWL caricato dall'utente: a fini di debugging probabilmente è proprio quello che si vuole vedere.

**Comment by valeriosantarelli** [comment]
> Un'istanza della classe OWLAxiom è intrinsecamente non serializzabile in JSON (ogni assioma ha dentro di se il riferimento all'ontologia e questa contiene ovviamente il riferimento allo stesso assioma). Per fare un lavoro completo occorre ridefinire la rappresentazione del modello degli assiomi OWL mediante oggetti POJO, ma questa operazione è molto lunga.
> Nell'immediato è viceversa molto più agevole mostrare nella schermata citata da @valeriosantarelli il contenuto del file OWL caricato dall'utente: a fini di debugging probabilmente è proprio quello che si vuole vedere.

Si, per il momento questo va più che bene, basta poter vedere cosa ci sta dentro il file OWL.

**Comment by valeriosantarelli** [comment]
Qualche piccola osservazione:

- nel menu, mettere OWL e non Owl (dato che è un acronimo, meglio maiuscolo)
- la voce del menu è inibita se è inibita anche Graphol (questo è un piccolo bug)
- si può aggiungere un pochino di padding a sinistra e sopra, tra gli assiomi e i pulsanti?
- usare sempre la dicitura OWL 2 QL invece che Approximated
- quando si switcha tra non approssimato e approssimato, sarebbe il caso di mettere una qualche rotellina di caricamento, dato che il passaggio potrebbe non essere proprio immediato

**Comment by valeriosantarelli** [comment]
Ultima osservazione: se è una cosa che possiamo in qualche modo avere gratis dal componente, aggiungiamo un pulsante toggle "word wrap", che manda a capo...alcuni assiomi possono essere lunghissimi.
Ma ripeto, solo se è gratis.
