### ISSUE TITLE
[Ontology - Navigation] Sintassi OWL

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#77]
La sintassi funzionale probabilmente non è la scelta più felice per il rendering delle espressioni o degli assiomi OWL (colpa mia, avevo indicato quella).

Si potrebbe provare ad utilizzare la sintassi Manchester (quella che usa Protégé), che dovrebbe essere più compatta. Si potrebbe anche pensare di rendere la cosa configurabile, ma credo non sia semplicissimo, è comunque una configurazione che deve arrivare a Mastro sotto, non è di pertinenza di Monolith, almeno di non fargli arrivare tutti gli assiomi in tutte le sintassi possibili (giusto?).

<img width="1440" alt="Schermata 2019-05-07 alle 15 07 23" src="https://user-images.githubusercontent.com/8250758/57301726-f872d480-70d9-11e9-9717-f9f35df0678c.png">

**Comment by roodsey** [comment]
Aggiunto query param "syntax" (opzionale) alla rotta POST /owlOntology/{name} per specificare la sintassi con cui precaricare le espressioni OWL (al momento non sarà possibile cambiare on the fly la sintassi utilizzata). 
I valori possibili per "syntax" sono i seguenti:
MANCHESTER_SYNTAX (default)
FUNCTIONAL_SYNTAX

**Comment by valeriosantarelli** [comment]
La sintassi Manchester è sicuramente più compatta e comprensibile, quindi mi pare efficace la scelta.
In futuro ovviamente si potrebbe rendere la sintassi di precaricamento delle espressioni OWL configurabile tramite un parametro dentro il pannello Settings.

Attualmente però c'è un problema con l'OWL che viene fuori nel pop-up: a volte è Manchester e a volte a Functional. Al momento ho riscontrato la differenza nelle pagine di Classes, tra la card con le subclasses/superclasses/etc. e quella con ruoli/attributi.
Allego screenshot per evidenziare il fenomeno:

<img width="944" alt="Schermata 2019-06-16 alle 18 13 39" src="https://user-images.githubusercontent.com/8250758/59566606-b175e880-9062-11e9-9894-146dcf2fe5e3.png">

<img width="686" alt="Schermata 2019-06-16 alle 18 14 59" src="https://user-images.githubusercontent.com/8250758/59566607-b89cf680-9062-11e9-97ee-e71a29f2a75d.png">

**Comment by roodsey** [comment]
ho utilizzato la manchester per le espressioni, non per gli assiomi...
provvedo ad uniformare

**Comment by roodsey** [comment]
chiedo a @giacomoronconi quale rotta utilizza per richiedere gli assiomi visualizzati in popup

**Comment by roodsey** [comment]
ziocaro @giacomoronconi rispondi

**Comment by giacomoronconiobda** [comment]
Penso che per risolvere al meglio la issue dobbiamo modellare le OWLapi almeno nella porzione che ci interessa. Quindi i metodi 
```
/owlOntology/{name}/version/alphabet/class/{ID}/logical
/owlOntology/{name}/version/alphabet/objectProperty/{ID}/logical
/owlOntology/{name}/version/alphabet/dataProperty/{ID}/logical
```
devono restituire degli oggetti che hanno al loro interno anche gli assiomi OWL nella sintassi che si preferisce. Per fare questo dobbiamo mettere mano alle risorse ma non penso che facciamo in tempo per ISWC. 

Quelo che facciamo in tempo a fare è cambiare la sintassi uniformamente a Manchester (solo lato interfaccia per quanto riguarda le entity) se pensate sia migliore.

**Comment by giacomoronconiobda** [comment]
> chiedo a @giacomoronconi quale rotta utilizza per richiedere gli assiomi visualizzati in popup

Le espressioni vengono generate lato interfaccia come chiedeva [questa issue](https://github.com/obdasystems/monolith/issues/10#issuecomment-483986025_)
