### ISSUE TITLE
[Ontology] No Version

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#78]
In caso di file OWL caricato senza una versione, eliminare ovunque la dicitura "NO_VERSION_PROVIDED".

Occorrenze che ho trovato:

<img width="758" alt="Schermata 2019-05-07 alle 16 30 57" src="https://user-images.githubusercontent.com/8250758/57307859-961fd100-70e5-11e9-9583-3eea24fbd539.png">

<img width="659" alt="Schermata 2019-05-07 alle 16 24 40" src="https://user-images.githubusercontent.com/8250758/57307913-aafc6480-70e5-11e9-841a-b78ae694339c.png">

<img width="797" alt="Schermata 2019-05-07 alle 16 31 57" src="https://user-images.githubusercontent.com/8250758/57307930-b18adc00-70e5-11e9-8f11-6dfb3166c41d.png">

**Comment by roodsey** [comment]
La stringa "NO_VERSION_PROVIDED" va intesa come una costante di sistema che rappresenta la versione quando essa è assente. Il valore tuttavia è utile perché necessario per accedere ai servizi sull'ontologia senza versione. Spetta all'interfaccia rimuovere l'etichetta o sostituirla con una alternativa.
