### ISSUE TITLE
[Ontology - Mapping] Caricamento file di mapping

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#79]
Se un primo caricamento di un file di mapping non va a buon fine, anche il successivo caricamento di un file di mapping con lo stesso nome (ma corretto) restituirà un errore. In sostanza il sistema dice che esiste già un file con quel nome:

<img width="763" alt="Schermata 2019-05-07 alle 16 43 02" src="https://user-images.githubusercontent.com/8250758/57308852-5659e900-70e7-11e9-9abd-424183527713.png">

**Comment by roodsey** [comment]
Difficile generare un errore per poter riprodure la issue: ad gni modo il meccanismo di gestione dei file di mapping è stato rivisto (il nome del file creato sul server viene generato automaticamente e si evitano collisioni).
