### ISSUE TITLE
[Ontology - Navigation]

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#82]
related to #77 

Il font che viene utilizzato per le entità e per le espressioni nelle card di Ontology Navigation è diverso.

<img width="756" alt="Schermata 2019-05-06 alle 18 25 19" src="https://user-images.githubusercontent.com/8250758/57514533-03637a00-7311-11e9-89fd-340ca9ad6e92.png">

**Comment by giacomoronconiobda** [comment]
L'avevo fatto a posta per diversificarli. Non ti piace?

Il ven 10 mag 2019 10:47 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by valeriosantarelli** [comment]
Ah, non avevo capito che fosse voluto. Non lo so in effetti...magari per il momento lasciamolo così poi vediamo.

**Comment by valeriosantarelli** [comment]
Forse in effetti si potrebbe usare lo stesso font e lasciare che la distinzione la fa il fatto che le classi atomiche sono cliccabili, e le espressioni di classe invece non lo sono.
