### ISSUE TITLE
[Ontology] Download (OWL/Graphol)

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#84]
Per le versioni di ontologie che sono state caricate tramite file .graphol, il sistema dovrebbe richiedere quando si clicca sul pulsante Download, se si vuole la versione .graphol o .owl.

**Comment by valeriosantarelli** [comment]
Scusate, mi sono dimenticato di indicare i pulsanti affetti dalla issue. Oltre a quello nella pagina Info dell'ontologia, c'è proprio quello sulla card della versione. Si può aggiungere anche a quello?

<img width="539" alt="Schermata 2019-05-23 alle 00 44 00" src="https://user-images.githubusercontent.com/8250758/58213874-0b99bd00-7cf4-11e9-9801-e67654cba334.png">

**Comment by roodsey** [comment]
Aggiunte le rotte seguenti:

**boolean GET /owlOntology/{name}/version/graphol/check (@pathparam name, @queryparam version)**
(restituisce true se il file graphol è presente per l'ontologia name/version)

**FileInfo GET /owlOntology/{name}/version/graphol (@pathparam name, @queryparam version)**
(restituisce il file Graphol)

**FileInfo GET /owlOntology/{name}/version/owl (@pathparam name, @queryparam version)**
(restituisce il file OWL)

Il resto dell'implementazione riguarda la parte di interfaccia utente

**Comment by giacomoronconiobda** [comment]
Pulsante download rimosso dalle card, spostato nella pagina ontology info

**Comment by valeriosantarelli** [comment]
Ma il pulsante di download dentro ontology info permette di scaricare la versione originale o quella approssimata dell'ontologia? Non mi è molto chiaro..

In ogni caso, se provo a cliccarlo mi rimanda ad una pagina di errore:

<img width="1116" alt="Schermata 2020-01-10 alle 11 21 15" src="https://user-images.githubusercontent.com/8250758/72145718-607d6700-339b-11ea-95c6-169b7e49b3ca.png">

**Comment by giacomoronconiobda** [comment]
Penso tu non abbia fatto pull del codice, la riga di MatroApi.js è diversa: https://github.com/obdasystems/monolith/blob/1fe079b8ce4e0904fd3f9cef28b31b6a86168aa9/src/api/MastroApi.js#L194
