### ISSUE TITLE
[Movie Ontology Query] Nessun risultato

### ISSUE THREAD

**Issue by giacomoronconiobda** [obdasystems/monolith#86]
Le query della specifica [movie](https://github.com/obdasystems/OBDA-Specifications/tree/master/movieontology) non producono nessun risultato su monolith mentre ne producono diversi sul plugin di protege.

**Comment by valeriosantarelli** [comment]
Le query SQL prodotte da Mastro nei due ambienti sono le stesse (assumo di si ovviamente)?
L'unica differenza tra i due ambienti è la forma del file di mapping, giusto?

**Comment by giacomoronconiobda** [comment]
Non vengono prodotti rewriting dall'unfolder su monolith. Su protégé ce n'è
uno.

Il gio 23 mag 2019 00:51 Valerio Santarelli <notifications@github.com> ha
scritto:

**Comment by roodsey** [comment]
Ma pensi sia possibile sapere a quale query fai riferimento? Oppure è tipo GOT?

**Comment by giacomoronconiobda** [comment]
Facendo un po' di debugging sul server ho visto che la query **q01** del catalogo gira su protege (3300 risultati circa in 1.7 sec) mentre su monolith il server dice che l'atomo **rating** non ha mapping. In realtà c'è un mapping se si va a esplorare la pagina relativa al concetto nela sezione mappings. 
Visto che i mapping su monolith sono stati caricati con il datasource staccato penso sia un problema legato a questo.
