### ISSUE TITLE
[URGENTE][BLOCCANTE] Definizione strutture dati per la navigazione istanze

### ISSUE THREAD

**Issue by roodsey** [obdasystems/monolith#87]
Definizione delle strutture dati (POJO) da utilizzare per la parte di navigazione delle istanze. (estrazione dal codice che le costruisce on-the-fly in RDFInstanceNavigation).
Specifica delle strutture dati suddette e delle rotte coinvolte nello spreadsheet condiviso su DRIVE. 

PS: mi ero autoassegnato il task, ma il tempo stringe e impiegherei troppo a dedurre la struttura dal codice che costruisce gli oggetti al volo. Quindi, assegno la issue a @giacomoronconiobda e @giacomoronconi

**Comment by giacomoronconiobda** [comment]
Marco per la demo non potremmo agganciare ai servizi direttamente gli
oggetti json che restituiscono i metodi? Poi costruiamo i pojo per bene
dopo la demo.

Il gio 23 mag 2019 16:06 Marco Ruzzi <notifications@github.com> ha scritto:

**Comment by roodsey** [comment]
Ma di quanti oggetti parliamo? Se sono 3 o 4 classi facciamolo adesso, se sono 30, 40 rimandiamo

**Comment by giacomoronconiobda** [comment]
Mi sembra di averne contati 13. Comunque non mi è ben chiaro come intendi usarle, dici di modificare RDFInstanceNavigation per costruire POJO? O costruire i POJO dai json restituiti?

**Comment by giacomoronconiobda** [comment]
[Qui](https://github.com/obdasystems/monolith/blob/master/src/api/fakeData.js#L929-L1240) ci sono esempi di ogetti necessari alla navigazioni. I nomi delle costanti coincidono con il nome del metodo che dovrebbe restituire gli ogetti.

**Comment by roodsey** [comment]
Ho definito tutti i POJO ispirati dal contenuto del JSON che hai convidiso qui sopra: vanno verificati (li trovi nel package "com.mwsx.model.kg" del progetto "mws"). Ho poi definito una classe com.mwsx.engine.KGUtilities con i metodi necessari per la navigazione delle istanze, sempre ispirati dal JOSN che hai condiviso. 
@giacomoronconiobda : rimpire il codice dei metodi di KGUtilities (specificando per tuti i metodi quali sono i parametri di input, cosa non deducibile facilmente dal JSON).

**Comment by roodsey** [comment]
Chiaramente per ora il codice di RDFInstanceNavigation può rimanere invariato, ma lato MWS non vorrei più doverci rimettere le mani, quindi per MOnolith usiamo gli oggetti POJO definiti.

**Comment by giacomoronconiobda** [comment]
Committato KGUtilities su SVN
