### ISSUE TITLE
[Ontology - Endpoint] Rewritings di una query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#88]
Il sistema restituisce un errore quando si tenta di visualizzare i rewriting di una query eseguita (per tutti e tre i tipi di rewriting).

![Schermata 2019-05-27 alle 10 27 05](https://user-images.githubusercontent.com/8250758/58406559-2bb9db00-806a-11e9-9950-916d71d9f70b.png)

**Comment by roodsey** [comment]
Sia i test unitari che i test di integrazione non rilevano alcun errore nella visualizazione dei rewriting: la problematica risiede al livello di chiamate HTTP emesse da Monolith. Giro a @giacomoronconiobda

**Comment by roodsey** [comment]
A titolo di esempio si considerino le classi seguenti:

- com.mwsx.unit.TestMovieQuery
- com.mwsx.test.Utils
