### ISSUE TITLE
[Ontology - Navigation] Individual pages

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#89]
Aggiungere alla sezione di Navigation le pagine per gli individui.

In linea di massima le informazioni da visualizzare dovrebbero essere le seguenti:

- IRI
- label
- descrizione
- Class di cui è istanza (se definita)
- ObjectPropertyAssertions a cui partecipa (se partecipa)
- SameIndividuals
- DifferentIndividuals

Metrics per Individuals

 Classes

 Same As

 Different

**Comment by roodsey** [comment]
Ho bisogno che @giacomoronconiobda mi faccia sapere di quali rotte necessita.

**Comment by giacomoronconiobda** [comment]
L'avevamo già definite in questo foglio. La rotta finisce per /individual

Il sab 11 apr 2020, 12:45 Marco Ruzzi <notifications@github.com> ha scritto:

**Comment by roodsey** [comment]
Temo che il file sia leggermente indietro rispetto alla situazione attuale dell'implementazione. Ad ogni modo, le uniche rotte che contengono la dicitura "individual" sono le seguenti:
![image](https://user-images.githubusercontent.com/20337479/79755663-c756d880-8319-11ea-891e-c71aaf63ae0e.png)
ma devo confessare di non riuscire a comprenderne la semantica. Sarebbe meglio avere qui in issue una descrizione accurata di ciò che serve.

**Comment by giacomoronconiobda** [comment]
IndividualInfo | currentEntity | Entity |   |   |  
-- | -- | -- | -- | -- | --
IndividualInfo | iri | IRI |   |   |  
IndividualInfo | entityDiagrams | List | DiagramNode |   |  
IndividualInfo | individualDescriptions | List | Label |   | List of Labels (to support different languages) contained in the "rdfs:comment" annotations (Giusta osservazione copiata da Rootsie)
IndividualInfo | sameIndividuals | List | Entity |   |  
IndividualInfo | differentIndividuals | List | Entity |   |  
IndividualInfo | individualTypes | List | Entity |   |

**Comment by roodsey** [comment]
Riformulo la domanda con maggiore dettaglio:
1) considerando la rotta
/owlOntology/{name}/version/alphabet/individual/{ID}/logical
- cosa viene passato nel parametro di query "ID"?
- cosa si intende per "logical" e come impatta sul risultato?

2) considerando la rotta
/owlOntology/{name}/version/alphabet/search/individual
- come deve essere utilizzato il parametro di query "search"?
- perché la rotta restituisce una lista di Entity e non una lista di IndividualInfo?

**Comment by roodsey** [comment]
Le rotte sono state implementate e collaudate. In mancanza di indicazioni precise sulla rotta per la ricerca, ho incapsulato la logica applicativa nel metodo
```
public static Collection<Entity> search(Collection<Entity> sources, String criteriaBase64) {
	return sources;
}
```
della classe 
```
com.mwsx.engine.IndividualSearchEngine
```
Come si vede il metodo attualmente non fa niente, pertanto va implementato.
Lascio a voi il divertimento e mi rimuovo dalla issue.

**Comment by roodsey** [comment]
Dimenticavo: per il corretto popolamento del campo "entityDiagrams" contenuto in IndividualInfo, occorre implementare il metodo
```
public static List<DiagramNode> searchNodes(Entity indEntity, Path grapholFilePath) {
	List<DiagramNode> nodes = new LinkedList<DiagramNode>();
	// add search code here
	return nodes;
}
```
della classe
```
com.mwsx.engine.GrapholEntityEngine
```
