### ISSUE TITLE
[Ontology - Endpoint] Query Info per Construct query

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#90]
In caso di query construct, il tab Query Info non sta mostrando risultati (mentre Ontology Rewritings, View Rewritings, e SQL Rewritings si).

Se per il momento vogliamo non far vedere i dettagli dell'esecuzione di una query per le query con la construct va bene, togliamo semplicemente quella sezione. Altrimenti, se le informazioni riportate nei tab dei rewriting sono corrette allora anche Query Info dovrebbe riportare informazioni giuste.

<img width="938" alt="Schermata 2019-05-28 alle 11 58 19" src="https://user-images.githubusercontent.com/8250758/58485355-2b9e0600-8164-11e9-837d-976504b9a60f.png">

**Comment by roodsey** [comment]
@valeriosantarelli sarebbe possibile verificare se questa issue è ancora valida o no?

**Comment by valeriosantarelli** [comment]
Mi pare che il problema sussista. Ho provato su obdatest e mws-dev.

<img width="770" alt="Schermata 2019-06-11 alle 19 30 16" src="https://user-images.githubusercontent.com/8250758/59293428-7d27b400-8c7f-11e9-9f58-a0ec7e1099c2.png">

**Comment by roodsey** [comment]
Ok, non avevo ben compreso la problematica. Al momento per le construct non abbiamo quel tipo di informazione (la construct fa riferimento a diverse query standard), opterei per rimuovere tutti i TAB che non vengono popolati.

**Comment by giacomoronconiobda** [comment]
tolti i tabs per le construct
