### ISSUE TITLE
[Ontology - Navigation] Rimuovere link a individuals

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#91]
Se nella card Individuals delle classi in Ontology Navigation sono mostrati effettivamente degli individuals, questi sono cliccabili, ma portano ad una pagina vuota.

<img width="1028" alt="Schermata 2019-05-28 alle 00 11 51" src="https://user-images.githubusercontent.com/8250758/58485146-c4805180-8163-11e9-955e-9c6d290c4818.png">

**Comment by giacomoronconiobda** [comment]
Rimosso link a pagina degli individui
