### ISSUE TITLE
[Ontology - Navigation] Ontology entity drawer

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#94]
Relativa a #70 

Proposta per ristrutturare il drawer degli Ontology Entity.

Al momento abbiamo un paio di problemi:
1. Per ontologie vere con tante classi, bisogna scorrere un pò per arrivare a object properties e poi a data properties
2. L'utilizzo delle iconcine a fianco di tutti i predicati non è il massimo esteticamente (almeno a mio parere), ed è pure copiata tale e quale da Protégé, ma è altrettanto vero che non abbiamo trovato una colorazione efficace

Per ovviare a questi problemi, ecco la proposta:
introdurre all'interno del drawer un menu orizzontale (tipo quello dei mapping), con tre voci (Classes, Object Properties, e Data Properties), spezzando quindi l'albero in tre parti. Quando avremo anche la gestione degli Individuals potremo aggiungere una quarta voce del menu, e gestire anche quelli quindi in modo più omogeneo.

Se serve un elemento radice dei tre alberi, si può usare tranquillamente owl:Thing, owl:TopObjectProperty e owl:TopDataProperty.

Suggerirei anche di introdurre del colore nel menu, scegliendo un colore di riferimento per ciascuno delle tre categorie e usandolo per il testo nel menu.
Ad esempio, per classi usare il colore #ADC965, per obj properties il colore #90C4E9, e per data properties il colore #FAC172 (sono quelli della palette che io e Fabio avevamo creato qualche tempo fa, ma si possono cambiare). 

Se questa soluzione ci piace, suggerirei altre due modifiche:
1. Utilizzare il colore scelto anche nella pagina dell'entity, nel titolo (vedi screenshot sotto)
2. Ristrutturare in modo simile anche il drawer dei progetti aperti, creando un unico drawer (quindi un solo pulsante sul menu) diviso in tre parti, ontologie, KG, e dataset [VEDERE COMMENTO SOTTO PER QUESTO PUNTO]

<img width="1195" alt="Schermata 2019-05-21 alle 23 02 13" src="https://user-images.githubusercontent.com/8250758/58130551-8db6b280-7c1c-11e9-8bf6-87debca62444.png">

**Comment by valeriosantarelli** [comment]
Prima di implementare le modifiche indicate nel bullet point 2. della issue riguardo il drawer dei progetti aperti, aspettiamo un attimo perchè stavo ragionando su una possibile variazione che lo renderebbe in sostanza inutile (o comunque non cruciale).

**Comment by giacomoronconiobda** [comment]
Non so se 1) sia efficace perchè poi non puoi cercare in tutto l'albero.
Forse serve anche un menu All che contiene l'albero che c'è adesso.

Le icone a lato dei predicati sono importanti quando filtri l'albero in
quanto altrimenti non sai il tipo dei risultati filtrati.

Il giorno dom 2 giu 2019 alle ore 09:45 Valerio Santarelli <
notifications@github.com> ha scritto:

**Comment by valeriosantarelli** [comment]
Francamente non ho mai ravvisato l'esigenza di effettuare una ricerca che prescinda dal tipo di entity che sto cercando. Di solito so se sto cercando una classe, un obj property o una data prop.
Diciamo che credo sia più lo svantaggio di dover scrollare centinaia di entity piuttosto che il vantaggio di poter fare una ricerca su tutte le entity stesse.
Ad ogni modo, si potrebbe anche pensare di mettere un ulteriore tab "All" che permetta di cercare ovunque.

Nota che la visualizzazione di tutte le entity in un unico albero è una cosa che non fa nessuno (a cominciare da noi stessi in Mastro Studio, ma nemmeno Protégé, mobi, etc. etc.) credo proprio perchè se ci sono tante entity non è gestibile la cosa.

La funzionalità di ricercare in tutto l'albero delle entity si potrebbe comunque fare, ma staccandolo dall'albero, proprio come facciamo in mastro studio ad esempio (screenshot sotto).

Re: le icone. A prescindere dalla loro bruttezza, che è soggettiva, il problema di sapere il tipo di risultato sussiste appunto solo se non c'è una separazione tra i vari tipi di entità.

<img width="382" alt="Schermata 2019-06-03 alle 11 05 07" src="https://user-images.githubusercontent.com/8250758/58789885-7e0d7580-85ef-11e9-96b1-e82f0cfd1e74.png">
