### ISSUE TITLE
Icons 

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#95]
Individuare le icone da incorporare nel sistema, e per ciascuno il colore da assegnargli.

Le prime icone che ho trovato sono reperibili qui: https://github.com/obdasystems/monolith/tree/master/src/icons

Per alcune voci da "iconizzare", ho inserito varie opzioni, scegliamo quelle che preferiamo.

**Comment by giacomoronconiobda** [comment]
Sarebbe meglio prendere le icone tutte dallo stesso set, in particolare da uno di questi definiti qui.
`[](https://github.com/react-icons/react-icons)`

**Comment by valeriosantarelli** [comment]
Provo a elencare le icone che ci servono ed associare qualche opzione per le icone che trovo da Font Awesome (che purtroppo non è tutto gratuito).

- Ontology: 
  - https://fontawesome.com/icons/sitemap?style=solid
  - https://fontawesome.com/icons/project-diagram?style=solid
- Knowledge Graph: 
  - https://fontawesome.com/icons/project-diagram?style=solid
  -

**Comment by valeriosantarelli** [comment]
Metto la lista di sopra come checkbox in modo tale da poter marcare le icone che sono scelte in via definitiva.
Suggerirei anche in linea di massima di ingrandire le dimensioni delle icone un pochino (in particolare nei menu laterali).

**Comment by valeriosantarelli** [comment]
@giacomoronconiobda quelli che vedi checkati sopra vanno bene per me e Fabio. Per gli altri vediamo un pò...

**Comment by valeriosantarelli** [comment]
@giacomoronconiobda Possiamo provare con questo per Knowledge Graph? L'ho preso da Feather Icons, sempre tra quelli di react. In mancanza di meglio...

[share-2.svg.zip](https://github.com/obdasystems/monolith/files/3341655/share-2.svg.zip)

A quel punto possiamo rimettere https://fontawesome.com/icons/project-diagram?style=solid per Graphol, che quello che ci sta adesso fa schifo.

**Comment by savo-fabio** [comment]
mmmm, quel simbolo ormai è universalmente riconosciuto per share. 

Io suggerisco quella che era già nella collezione di icone che avevi preparato: 
https://github.com/obdasystems/monolith/blob/master/src/icons/kg.svg

**Comment by giacomoronconiobda** [comment]
Per l'icona di Graphol ho messo quella attuale di grapholscape

**Comment by valeriosantarelli** [comment]
Questa issue si può chiudere, abbiamo tutte le icone che ci servono al momento. 
Se ne serviranno altre, le cercheremo.
