### ISSUE TITLE
[Endpoint] Risultati persi

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#96]
Related to #27 

Questa issue riguarda sia l'endpoint su ontologie che l'endpoint su KG.

Al momento il sistema preserva lo "stato" dell'endpoint in termini delle query del catalogo che erano aperte la momento di cambiare pagina. Tuttavia vengono persi i risultati delle query eseguite. Non ricordo se avevamo già affrontato la questione ed eravamo giunti alla conclusione che l'attuale comportamento è accettabile, ma ragionandoci non credo lo sia.

La soluzione ideale sarebbe ovviamente che nella pagina dell'endpoint venga mantenuto tutto lo stato, quindi risultati compresi; una soluzione temporanea accettabile potrebbe essere che se ci sono query che sono state eseguite e l'utente decide di lasciare la pagina, esce una finestra di warning che segnala che i risultati delle query verranno persi se non esportati.

**Comment by giacomoronconiobda** [comment]
Quando si lancia una query viene salvato l'id di esecuzione. Se si ritorna all'endpoint i risultati vengono mostrati nuovamente (se non sono stati buttati via dal server)

**Comment by valeriosantarelli** [comment]
> Quando si lancia una query viene salvato l'id di esecuzione. Se si ritorna all'endpoint i risultati vengono mostrati nuovamente (se non sono stati buttati via dal server)

Se provo a fare questo mi compare una pagina vuota....a te sta funzionando? 

<img width="1092" alt="Schermata 2019-06-20 alle 08 14 23" src="https://user-images.githubusercontent.com/8250758/59825141-778f3580-9333-11e9-97aa-7556145dd547.png">

**Comment by giacomoronconiobda** [comment]
è rimasta sporca la memoria del browser. Naviga sulla pagina del sito apri la console e scrivi
`localStorage.clean()`

**Comment by valeriosantarelli** [comment]
Ok perfetto. Chiudo.
