### ISSUE TITLE
[Home/Open Projects] Open Projects Drawer e Home Page

### ISSUE THREAD

**Issue by valeriosantarelli** [obdasystems/monolith#99]
Rimuovere del tutto il drawer con Open ontologie/KG/dataset, e sostituirlo con la Home Page (le rispettive sezioni), in cui mostrare, sempre sotto forma di Cards, i progetti aperti più di recente, ordinati dal quello aperto più di recente a quello aperto meno di recente.

L'idea sarebbe quella di avere subito nella Home Page i progetti su cui si sta lavorando.

Si può pensare di mettere un numero massimo di card per ogni riga della home page (con scroll orizzontale), tipo 7 o 10.

Manterrei la forma delle card nella home page identica a quella di Ontology Versions e Knowledge Graphs, togliendo ovviamente i pulsanti in basso.

**Comment by valeriosantarelli** [comment]
Sposto questa issue a ISWC2019, perchè credo che in un modo o nell'altro la home page vada sistemata per la demo, e a questo punto tanto vale farlo come ce la stavamo immaginando.
Che ne dici?

**Comment by giacomoronconiobda** [comment]
Sono d'accordo ma dobbiamo coinvolgere @roodsey per i servizi!

**Comment by roodsey** [comment]
Chiedete e vi sarà dato: specificare rotte e risultati attesi.

**Comment by giacomoronconiobda** [comment]
PATH | HTTP METHOD | BODY | RESPONSE | LIST TYPE
-- | -- | -- | -- | --
/lastLoaded/ontology | GET |   | List | Ontology
/lastLoaded/knowledgeGraph | GET |   | List | KnowledgeGraph
/lastLoaded/dataset | GET |   | List | Dataset
/owlOntology | GET |   | List | Ontology

**Comment by roodsey** [comment]
Prime due rotte implementate: i dataset verranno demandati ad una issue successiva.
Le rotte restituiscono liste di istanze dei seguenti oggetti:
- OntologyOpeningEvent (contiene un OntologyID e un timestamp)
- KGOpeningEvent (contiene una IRI di KG e un timestamp)
I timestamp sono relativi a quando l'ontologia/kg è stato aerto l'ultima volta.

**Comment by valeriosantarelli** [comment]
Si, assolutamente, togliamo dal sistema qualsiasi riferimento ai dataset per la versione che manderemo ai revisori ISWC.
